### ISSUE TITLE
Easier deployment

### ISSUE THREAD

**Issue by leendertvanwolfswinkel** [nens/threedi-results-analysis#10]
(the .bat doesn't work for me: `C:\Users\leendert.vanwolfswin\OneDrive - Nelen & Schuurmans\Documents 1\GitHub\threedi-results-analysis>xcopy "C:\Users\leendert.vanwolfswin\OneDrive - Nelen \threedi-results-analysis" "C:\Users\leendert.vanwolfswin\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\threedi-results-analysis" /s/i/h/e/k/f/c File not found - threedi-results-analysis 0 File(s) copied`

Perhaps include a zip_plugin.py and/or deploy.py?

**Comment by erpas** [comment]
Added a Python script for deployment.

However, I suggest to remove the ampersand from your path if possible. It can be the source of many troubles...
