### ISSUE TITLE
[Bug]: QgsProcessingParameterNumber(): arguments did not match any overloaded call

### ISSUE THREAD

**Issue by daanvaningen** [nens/threedi-results-analysis#1002]
### Contact Details

daan.vaningen@nelen-schuurmans.nl

### Complexity

easy

### Priority

low prio

### What happened?

Opened QGIS, got a pop-up with error msg

### How to Reproduce?

Linux
Install 3Di schematisation editor plugin
close Qgis
open Qgis

### What did you expect and what was the actual result?

no pop-up

### Add screenshots, video's etc

The maximum size for files is 25MB and the maximum size for images is 10MB.

### Relevant log output

```shell
TypeError: QgsProcessingParameterNumber(): arguments did not match any overloaded call:   overload 1: argument 'type' has unexpected type 'int'   overload 2: argument 1 has unexpected type 'str' 
Traceback (most recent call last):
  File "/home/daan/.local/share/QGIS/QGIS3/profiles/default/python/plugins/threedi_schematisation_editor/processing/alghorithms_inflow.py", line 120, in initAlgorithm
    storm_pref = QgsProcessingParameterNumber(
TypeError: QgsProcessingParameterNumber(): arguments did not match any overloaded call:
  overload 1: argument 'type' has unexpected type 'int'
  overload 2: argument 1 has unexpected type 'str'


Python version: 3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0] 
QGIS version: 3.36.3-Maidenhead Maidenhead, 2df9655469b
```

### Additional info

I can close the pop-up and everything seems to work, so low prio

**Comment by leendertvanwolfswinkel** [comment]
Can't reproduce
