### ISSUE TITLE
Load simulation results: sort by revision ID as integer not string

### ISSUE THREAD

**Issue by leendertvanwolfswinkel** [nens/threedi-results-analysis#1008]
In the example, revision 11 is listed before revision 8:

<img width="667" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMzR0QlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d5e96ad0122f4188b3b3a70c5f3b5c6affbf9a45/image.png" alt="image.png" />

Please ask @ldebek for advice, he has looked into this issue in other contexts before

**Comment by leendertvanwolfswinkel** [comment]
@hoanphungt I tested this, but the implementation is not as I had in mind. The previous implementation sorted on Schematisation name, then revision ID, but the sorting on revision ID was alphabetically instead of numerically. The new implementation seems to sort on Revision ID only, not on schematisation name.

BTW how difficult would it be to re-sort when users click on a column header?

**Comment by hoanphungt** [comment]
@leendertvanwolfswinkel 
Yes, I managed to do both:

1. At first, sort table by schematisation name and then revision ID using number
2. Add feature to re-sort the table when users click on a column header

Can you test again?
