### ISSUE TITLE
Simulation wizard: add option to use constant substance concentrations for laterals and boundary conditions

### ISSUE THREAD

**Issue by leendertvanwolfswinkel** [nens/threedi-results-analysis#1025]
Design is given in the image below (for laterals)

<img width="953" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNExRQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--2d5be5df50eef8d3d0125a6e910f78c43a1d1cd2/image.png" alt="image.png" />

This user input should be converted to time series, in which each time step has the same value

**Comment by Overmeen** [comment]
I checked out the design and tested the functionalities.

1. Design: it wrongfully says ‘laterals’ in the text of the ‘Boundary conditions’ tab.
<img width="940" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNlVGQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--0d918eb4406947b29327a0c112a3038ff2a3d56d/image.png" alt="image.png" />

2. The functionality does not work when using laterals from simulation template. When trying to type in the constant value, the message "No laterals uploaded yet" pops up and it doesn’t allow me to fill in any value.
<img width="940" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNmdGQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--689ba0a97d043f0c8216662377657e9cc4f28e6b/image.png" alt="image.png" />
<img width="520" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNmtGQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f10fd2b8224a6337c9716d5a96266fae2f9c639f/image.png" alt="image.png" />

3. It seems that the constant concentration is not added correctly to the simulation information. There are no issues in the widget when using the 'Upload CSV' functionality. However, checking the results and no concentration seems to have been added. The laterals are added (see discharge in flowlines), but no concentration.

<img width="940" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNjhGQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f6a8131c2970bafdf987424cef81136be9e579e0/image.png" alt="image.png" />

**Comment by hoanphungt** [comment]
@leendertvanwolfswinkel I fixed the bugs that Stijn mentioned above. Could you take a look again?

**Comment by leendertvanwolfswinkel** [comment]
Hi, I have checked it out. My feedback:

1. I see that you have replaced "laterals" by "steps", so that the same text can be used for both laterals and boundary conditions. I don't think this is clear for the users; please use "laterals" on the laterals page and "boundary conditions" on the boundary conditions page.
2. Seems to work correctly now
3. I tested this by using laterals from the simulation template + constant substance concentration. I still see the same behaviour as Stijn saw. There is a substance in the simulation events overview, but in the laterals, there is no substance concentration.

**Comment by leendertvanwolfswinkel** [comment]
@benvanbasten-ns this can be merged!
