### ISSUE TITLE
Watershed tool: 2D flowlines intersecting obstacles are shown as 1D flowlines

### ISSUE THREAD

**Issue by leendertvanwolfswinkel** [nens/threedi-results-analysis#1034]
<img width="750" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK2RjQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c50eb91d58ea4a4090ea7d8ccc524fe446e5e4a4/image.png" alt="image.png" />

Die stippellijntjes laten 1D flowlines zien, maar die worden dus ook meegeteld als een 2D line over een v2_obstacle gaat

**Comment by benvanbasten-ns** [comment]
@leendertvanwolfswinkel exampledata? And could you please elaborate on the problem?

**Comment by leendertvanwolfswinkel** [comment]
tested, please merge @benvanbasten-ns
