### ISSUE TITLE
Time series plotter: Attribute error when selecting substance in model that contains pumps TOPDESK 2406 0082

### ISSUE THREAD

**Issue by leendertvanwolfswinkel** [nens/threedi-results-analysis#1044]
How to reproduce:
- Add the simulation results from this dataset to the project: https://nelenschuurmans-my.sharepoint.com/:f:/g/personal/leendert_vanwolfswinkel_nelen-schuurmans_nl/EuvNX92q3vdGibq4RCymN4UBZ4DQBVH8K4dfHtJIKeSz_A?e=Vqb08l
- Open the Time series plotter
- Click on a node
- As variable, select "Breach" (this is a bit confusing, but "Breach" is the name of the substance)
- The error below is raised

At first glance, to me this looks as an inconsistency in threedigrid (Lines and Nodes having a Meta property but Pumps not?), that would better be fixed there rather than in 3Di Results Analysis. But I may be wrong.

```
AttributeError: 'Pumps' object has no attribute 'Meta' 
Traceback (most recent call last):
  File "C:\Users\leendert.vanwolfswin\AppData\Roaming\3Di\QGIS3\profiles\default/python/plugins\threedi_results_analysis\tool_graph\graph_view.py", line 582, in parameter_change
    self.graph_plot.set_parameter(self.current_parameter, time_units)
  File "C:\Users\leendert.vanwolfswin\AppData\Roaming\3Di\QGIS3\profiles\default/python/plugins\threedi_results_analysis\tool_graph\graph_view.py", line 246, in set_parameter
    item.plots(self.current_parameter["parameters"], time_units=self.current_time_units, absolute=self.absolute)
  File "C:\Users\leendert.vanwolfswin\AppData\Roaming\3Di\QGIS3\profiles\default/python/plugins\threedi_results_analysis\tool_graph\graph_model.py", line 122, in plots
    ts_table = self.timeseries_table(
  File "C:\Users\leendert.vanwolfswin\AppData\Roaming\3Di\QGIS3\profiles\default/python/plugins\threedi_results_analysis\tool_graph\graph_model.py", line 152, in timeseries_table
    pump_fields = set(list(ga.pumps.Meta.composite_fields.keys()))
  File "C:\Users\leendert.vanwolfswin\AppData\Roaming\3Di\QGIS3\profiles\default\python\plugins\threedi_results_analysis\deps\threedigrid\orm\base\models.py", line 194, in __getattribute__
    attr = super().__getattribute__(attr_name)
AttributeError: 'Pumps' object has no attribute 'Meta'
``

**Comment by leendertvanwolfswinkel** [comment]
@hoanphungt can you confirm that this issue should be solved in threedigrid?

**Comment by hoanphungt** [comment]
@leendertvanwolfswinkel I just looked at the code in the ThreediToolBox and the threedigrid. It's indeed an issue that should be solved in the threedigrid.

The error comes from this line: https://github.com/nens/ThreeDiToolbox/blob/refactor/tool_graph/graph_model.py#L152

It refers to the gridadmin file of the threedi result. The Pumps model is defined in the threedigrid and it doesn't contain a Meta property.

**Comment by margrietpalm** [comment]
Tried to reproduce this with master of threedigrid and the files Leendert mentioned:

```python
from pathlib import Path
from threedigrid.admin.gridresultadmin import GridH5ResultAdmin

basedir = Path()
result_file = basedir.joinpath( "results_3di.nc")
grid_file = basedir.joinpath("gridadmin.h5")
gr = GridH5ResultAdmin(str(grid_file), str(result_file))
print(gr.has_pumpstations)
> True
print(gr.pumps.Meta.composite_fields)
> {'q_pump': ['Mesh1D_q_pump'], '_mesh_id': ['Mesh1DPump_id']}
```

But can reproduce with
```
gr = GridH5Admin(str(grid_file), str(result_file))
print(gr.pumps.Meta.composite_fields)
```

This is because the `PumpsResultMixin`, that adds `Meta`, is only added to the `GridH5ResultAdmin` and not to the `GridH5Admin` (https://github.com/nens/threedigrid/blob/master/threedigrid/admin/gridresultadmin.py#L140). This is the case for all these mixings. So either threedigrid should be modified to include the `Meta` field in the `GridH5Admin` or the results plugin should use the `GridH5ResultAdmin` objects instead of the `GridH5Admin`.

This also holds for lines and nodes, so this observation is incorrect

> At first glance, to me this looks as an inconsistency in threedigrid (Lines and Nodes having a Meta property but Pumps not?), that would better be fixed there rather than in 3Di Results Analysis. But I may be wrong.



@hoanphungt @leendertvanwolfswinkel @daanvaningen What do you think?

**Comment by daanvaningen** [comment]
`composite_fields` specifies which fields are present in the result file, `composite_fields` has no meaning outside the domain of results. Therefore I think that `GridH5Admin.pumps.Meta.composite_fields` does not make sense. I don't think we can include `Meta.composite_fields` on the normal `Nodes`, `Lines` etc without a results file.

So I think this can be solved by either using a different interface in the result analysis or not relying the Meta field

**Comment by leendertvanwolfswinkel** [comment]
@benvanbasten-ns could you please have a look at this issue with the additional insights from @daanvaningen? I would really like this issue to be resolved, it affects very many cases with WQ simulations.

**Comment by benvanbasten-ns** [comment]
@leendertvanwolfswinkel  please test

**Comment by leendertvanwolfswinkel** [comment]
@benvanbasten-ns tested please merge
