### ISSUE TITLE
Let user customize visualisation of nodes and flowlines on map canvas

### ISSUE THREAD

**Issue by leendertvanwolfswinkel** [nens/threedi-results-analysis#1046]
[threedi_result_legend_class_bounds](https://github.com/nens/threedi-results-analysis/blob/4e8aa0b27a2301350810df0ad815974477e4f1a8/tool_animation/map_animator.py#L48) has three arguments that the user currently has no control over, that should be customizable by the user:

-    lower_cutoff_percentile (current default value is 2)
-    upper_cutoff_percentile (current default value is 98)
-    method (current default value is 'pretty', other option is 'percentile')
-    nr_classes (current default value is 24, must be an even number)

These settings should be customizable for nodes and flowlines separately.

UI proposal:

- Add a button with a "customize" symbol https://www.flaticon.com/free-icon/equalizer_2989861?term=customize&page=1&position=2&origin=tag&related_id=2989861 in both the "Flowline variable" and "Node variable" group boxes
- When user clicks the button, show a dialog with the settings above
- Settings widgets should be prepopulated with the defaults
- New settings should be applied after user clicks OK
- Settings should be remembered per variable and per simulation result. I.e. should be interpreted as user telling us "I want to style discharge for this simulation result with these settings"
- Settings should be reset when user switches variables (either to the defaults or to the previously user-defined values)

<img width="548" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMS9aQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--519f3d05b559b5fd35e6c8b5fabb413d8fc8d720/image.png" alt="image.png" />

**Comment by benvanbasten-ns** [comment]
@leendertvanwolfswinkel 

Please test

Note we do not store the settings for simulation result, only per variable

Note that we do store these settings in the qgis project, when saved

As the combobox is filled with the intersection of the parameters of the results (all results should contain this parameter), a stored setting is removed when the parameter is no longer present in the intersection of the results. But I'm not sure if this is the desired behavior and that the settings should just be remembered... Any ideas?
