### ISSUE TITLE
[animation-settings] Feedback from user testing

### ISSUE THREAD

**Issue by leendertvanwolfswinkel** [nens/threedi-results-analysis#1053]
- [x] Make the cutoff percentile `0 <= x <= 100` instead of `0 < x < 0`
- [x] In Pretty breaks mode, a class `< 1e-06` is added if the variable cannot be < 0. Please add this same behaviour to to the "Equal count" mode. The reason for this is that users want to be able to easily show/hide all lines with a value of 0(ish). In Pretty breaks mode, it looks like this:
<img width="647" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd0VyQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--fd0744223339fcae8f457314ef6eb0fd36875d5c/image.png" alt="image.png" />

- [x] Typo in "Number of classes should be greater than 0 and less **then** 42" -> "Number of classes should be greater than 0 and less **than** 42" (but see also next item)

- [x] The message suggests that 42 is not allowed, but it is allowed. Perhaps we can make it "The maximum number of classes is 42". And perhaps just automatically interpret any value < 1 as 1?

- [x] "Preferred number of classes" is confusing.  Let's rename it back to "Number of classes" and add an explainer: "🛈 The number of classes used in the styling may differ slightly from the number of classes set here." Either using a tooltip (on both the label and the input widget) or a label, like so:

<img width="357" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN1VxQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--78da80fdcd85ef4cbb783112b4a4f7d94496c02f/image.png" alt="image.png" />

- [x] Visualisation is with an "s" in British English (which we use) : <img width="395" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOE1xQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--2a14e5f93f5ae7e71259d1b04a194001157a2a46/image.png" alt="image.png" />

**Comment by benvanbasten-ns** [comment]
@leendertvanwolfswinkel I think I correctly added a zero-class for this case (equal count). Perhaps you can quickly review it (https://github.com/nens/threedi-results-analysis/pull/1048/commits/5b5ece56806f30677c35f2ca6980239a8d2be5e6) and test it.

**Comment by leendertvanwolfswinkel** [comment]
I think it all works wonderfully now, please merge
