### ISSUE TITLE
Sideview for systems with embedded 1d elements

### ISSUE THREAD

**Issue by bastiaan-roos** [nens/threedi-results-analysis#109]
The sideview does not work with 1d systems with embedded elements (for example the model \rotterdam\archive\lombardijen_8_hybrid_rainevent_23june2016_lom).

On generation of the graph layer, the error is:

file \views\sideview.py, line 1249,in create_comined_layers
  for line in channel_calc_points[channel['id']]:
KeyError: XX

**Comment by bastiaan-roos** [comment]
Een paar oplossingsrichtingen:
1. alle embedded 1d elementen  negeren (hier kan je dan geen sideview over trekken).
2. constateren dat er geen rekenpunten zijn en doorgaan. Er kan dan wel een sideview worden gemaakt, maar er verschijnen geen waterstanden. 
3. De waterstanden voor de embedded kanalen halen uit de 2d gridcellen waarin ze 'ge-embed' zijn.

3e oplossing is veel werk. Daarom lijkt de 2e de meest wenselijke - je kan toch de schematisatie controleren en waar mogelijk de waterstanden zien.

**Comment by arnoldvantveld** [comment]
Was deze melding nu wel of niet al opgepakt?
Ik dacht dat ik al een keer sideviews had getrokken in embedded in een test versie van de plugin, maar kan het ook verkeerd onthouden hebben...

**Comment by bastiaan-roos** [comment]
De sideview zou het moeten doen als je alleen een spatialite kiest en geen resultaat (alleen staat het knopje voor de sideview dan uit). Het kan dus dat je het daarom ooit gezien hebt in een oude versie. 
Melding is verder nog niet opgepakt.

**Comment by arnoldvantveld** [comment]
Kunnen we het knopje makkelijk aanzetten of optie 2 alsnog verwerken?

**Comment by bastiaan-roos** [comment]
zie branch  'sideview-enabled-without-result'. Niet getest, maar probeer het eens uit (zou in theorie moeten werken).

**Comment by Jonasvsl** [comment]
This ticket was made when we didn't have the grid admin. Shouldn't it be much easier to implement option 3 now?

**Comment by leendertvanwolfswinkel** [comment]
@benvanbasten-ns quick test indicates that it works as it should. one addition: the start/end of embedded flowlines are not shown as nodes (currently vertical dashed lines) in the sideview. please change this

**Comment by benvanbasten-ns** [comment]
@leendertvanwolfswinkel  Those nodes do not have an "height", to solve this, see issue #831
