### ISSUE TITLE
Add extra model views

### ISSUE THREAD

**Issue by bastiaan-roos** [nens/threedi-results-analysis#110]
CREATE VIEW v2_1d_lateral_view AS
SELECT a.*, b.the_geom
FROM v2_1d_lateral a
JOIN v2_connection_nodes b ON a.connection_node_id = b.id;

And maybe:
- pumpstations_beginpunt (pumpstation_point_view)
- 1d_bounday_conditions (1d_boundary_conditions_view)

**Comment by Jonasvsl** [comment]
out of date
