### ISSUE TITLE
v2_impervious_surface  geometrie is niet zichtbaar op kaart

### ISSUE THREAD

**Issue by ghost** [nens/threedi-results-analysis#113]
v2_impervious_surface  geometrie is niet zichtbaar op kaart

**Comment by bastiaan-roos** [comment]
@beralbers  - problem is the spatialindex of the v2_impervious_surface layer. This is not working properly. Cause is probably the way it is created by the export_to_spatialite. A had a look with Lars, and their are probably some clues in the south migration scripts. I think it is good to fix this in the export.

For now I automatically recover the spatial_index of this layer, when the model is loaded through the plugin.
