### ISSUE TITLE
convert_to_gpkg: Output layers

### ISSUE THREAD

**Issue by leendertvanwolfswinkel** [nens/threedi-results-analysis#12]

**Comment by erpas** [comment]
Just to be clear, here are the sources for the layers as I understand them:

- "Node": ga.nodes
- "Cell": ga.cells
- "Flowline": ga.lines
- "Linear obstacle": ga.levees

Could you please confirm? #1 mentions also breaches.

**Comment by leendertvanwolfswinkel** [comment]
I will discuss about this with Martijn and get back on this asap

**Comment by leendertvanwolfswinkel** [comment]
"Node": ga.nodes
"Flowline": ga.lines
"Linear obstacle": ga.levees
"Cell": ga.cells

Breaches is deprecated

**Comment by leendertvanwolfswinkel** [comment]
will be implemented in threedigrid
