### ISSUE TITLE
remove netcdf cause error

### ISSUE THREAD

**Issue by ghost** [nens/threedi-results-analysis#122]
•    Als ik een netcdf verwijder terwijl ik alles leeg heb gegooid in mijn Layers Panel, krijg ik de volgende Python error:

![image](https://cloud.githubusercontent.com/assets/3777412/20964616/87b541ba-bc72-11e6-88bf-59230fdb66ba.png)

 o    Als ik daarna een nieuw bestand inlaadt, zowel sqlite als netcdf krijg ik weer een python error:
 o    Ik krijg nu niet meer de Animatie aan. Hij maakt niet opnieuw de line_results en node_results lagen aan. Moet ik hiervoor altijd QGIS opnieuw opstarten?

**Comment by Jonasvsl** [comment]
out of date
