### ISSUE TITLE
import_sufhyd aansluiten op nieuwe db schema

### ISSUE THREAD

**Issue by arnoldvantveld** [nens/threedi-results-analysis#127]
import_sufhyd crasht omdat het "nieuwe" code veld niet wordt ingevuld door de plugin.
De plugin maakt echter wel, net als vroeger, het veld _code aan. 
Lijkt me netter als dit veld verdwijnt als het wordt geupdate

> An error has occurred while executing Python code: 
> 
> IntegrityError: (psycopg2.IntegrityError) null value in column "code" violates not-null constraint DETAIL:  Failing row contains (1, 1, 5.0, null, null, rectangle_w5.0_open). [SQL: 'INSERT INTO v2_cross_section_definition (width, shape, _code) VALUES (%(width)s, %(shape)s, %(_code)s)'] [parameters: ({'width': 5.0, 'shape': 1, '_code': 'rectangle_w5.0_open'}, {'width': 6.0, 'shape': 1, '_code': 'rectangle_w6.0_open'}, {'width': 2.3, 'shape': 1, '_code': 'rectangle_w2.3_open'})]

**Comment by jackieleng** [comment]
Arnold, kun je ook de *gehele* stacktrace plaatsen? Dan is het makkelijker traceren waar in de code het zit. @bastiaan-roos enig idee of dit makkelijk op te lossen is?

**Comment by bastiaan-roos** [comment]
Dit is goed te doen. Heb Nici gevraagd wat er nog meer is gewijzigd, dan kan ik dat direct meenemen. 
@arnoldvantveld kan ik zo'n nieuwe database maken met de productie turtle omgeving?
