### ISSUE TITLE
Melding als NetCDF niet meer ingeladen kan worden

### ISSUE THREAD

**Issue by arnoldvantveld** [nens/threedi-results-analysis#129]
Bij inladen van een grafiek/animatie als verbinding verbroken is met de NetCDF verschijnt deze melding:
Wens is om een betere melding te krijgen, zodat mensen snappen dat ze hem opnieuw moeten inladen.
> 
> 
> An error has occurred while executing Python code:
> 
> RuntimeError: Invalid argument
> 
> Traceback (most recent call last):
>   File "C:/Users/Arnold.vantveld/.qgis2/python/plugins\ThreeDiToolbox\views\graph.py", line 242, in on_insert_locations
>     self.current_parameter['parameters'], index))
>   File "C:/Users/Arnold.vantveld/.qgis2/python/plugins\ThreeDiToolbox\models\graph.py", line 99, in plots
>     result_ds_nr=result_ds_nr)
>   File "C:/Users/Arnold.vantveld/.qgis2/python/plugins\ThreeDiToolbox\models\graph.py", line 124, in timeseries_table
>     fill_value=np.NaN)
>   File "C:/Users/Arnold.vantveld/.qgis2/python/plugins\ThreeDiToolbox\datasource\netcdf.py", line 550, in get_timeseries
>     vals = ds.variables[variable][:, netcdf_id]
>   File "netCDF4\_netCDF4.pyx", line 3634, in netCDF4._netCDF4.Variable.__getitem__ (netCDF4\_netCDF4.c:37084)
>   File "netCDF4\_netCDF4.pyx", line 4326, in netCDF4._netCDF4.Variable._get (netCDF4\_netCDF4.c:46971)
> RuntimeError: Invalid argument

**Comment by Jonasvsl** [comment]
out of date
