### ISSUE TITLE
Predic_calculation_points werkt niet op DB

### ISSUE THREAD

**Issue by EveApa** [nens/threedi-results-analysis#132]
File "C:\Users\evelyn.aparicio\.qgis2\python\plugins\ThreeDiToolbox\external\sqlalchemy\engine\default.py", line 385, in connect
			    return self.dbapi.connect(*cargs, **cparams)
			  File "C:\PROGRA~1\QGIS2~1.14\apps\Python27\lib\site-packages\psycopg2\__init__.py", line 164, in connect
			    conn = _connect(dsn, connection_factory=connection_factory, async=async)
			OperationalError: (psycopg2.OperationalError) could not translate host name "nens-3di-db-03.nens.local " to address: Unknown

**Comment by jackieleng** [comment]
@larsclaussen enig idee? Lijkt erop dat ie hostname niet kan resolven.

**Comment by larsclaussen** [comment]
Inderdaad. Ik heb nog een keer local getest en kon het probleem niet reproduceren. Ik neem aan dat je @EveApa qgis op windows draait? Misschien helpt het als je de hostname/ip adres combinatie aan je hosts file toe voegt. 

[https://technet.microsoft.com/en-us/library/cc940089.aspx](url)
