### ISSUE TITLE
Set QGIS minimum version to 3.16

### ISSUE THREAD

**Issue by leendertvanwolfswinkel** [nens/threedi-results-analysis#14]
Unless there > 3.16 parts of the API are used.

I couldn't get it to work on 3.22 (due to problems with installing h5py I think, not something to worry about for now), but it worked fine on 3.16

**Comment by erpas** [comment]
QGIS min version is now set to 3.16. 

It is not the API but different Python versions and their h5py incompatibilities. 
Let's assume users have a proper h5py and HDF lib installed - as it was in your case @leendertvanwolfswinkel.
