### ISSUE TITLE
[RFC] breach location tooling

### ISSUE THREAD

**Issue by larsclaussen** [nens/threedi-results-analysis#149]
Enhancement existing tools
------------------------------------

__Implement re-run command__ [2 days]

As of now the tool ``predict_calc_pnts`` will populate the tables 'v2_calculation_point' and 'v2_connected_pnt' only once. Upon a second execution the tool will give an error. Therefore users manually have to delete the existing entries before running the tool again. This of course can be automated but clearly needs a warning before deleting the entries because all manually edited entries will be lost then.   

__Add a second entry to the 'v2_connected_pnt' table for double connected points__ [0.5 days]

Connected points that are derived from 1D objects with a calculation type "double connected" should be generated in twofold (at the moment only one point will be produced).     

New tools
-------------

__Add a tool to automatically move connected points across a levee__ [7 days] 

Users need to move the generated connected points to the desired location manually at the moment. For parts of their model it is desired to automate this operation. The following requirements apply: 

- the user must be able to set a maximum search distance in which a levee must be encountered 
- the user must be able to select a subset of connected points which should be moved
- the search algorithm must be able to distinguish between single and double connected points
- for single connected points the search should be considered successful after the intersection with a levee at a minimum distance
- for double connected points the search must be performed on both sides of the channel. The search direction must be vertical to the channel geometry (~avg 5 meters at the given location?). If the channel is being crossed a warning must be issued.

**Comment by ghost** [comment]
besides maximum search distance, the user wants to set a distance to place the breach location after it crosses the first levee

**Comment by ghost** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[QGIS plugin] bres tooling [10]](https://trello.com/c/ccJ6ClcE/1898-qgis-plugin-bres-tooling-10)

**Comment by Jonasvsl** [comment]
@larsclaussen 
is this still an active RFC or can I close it?

**Comment by larsclaussen** [comment]
I'll close it, not active anymore
