### ISSUE TITLE
[RFC] Statistieken versnellen

### ISSUE THREAD

**Issue by jackieleng** [nens/threedi-results-analysis#157]
## Probleem

De statistieken zijn nu erg traag. Er wordt door de features van de lagen gelooped en **iteratief** statistieken berekend, wat traag is in Python.

## Voorstel oplossing

Maak gebruik van Numpy gevectoriseerde operaties om de statistiekoperaties te versnellen. De vereist een andere opzet t.o.v. hoe het nu is geimplementeerd. I.p.v. iteratief per feature de statistieken te berekenen, moet dan een statistiek van te voren voor alle features worden berekend (gebruikmakend van de snelle vector operaties die werken op gehele arrays). Als eenmaal zo'n array met een bepaald statistiek is berekend, is het een kwestie van de statistiekwaarde toewijzen naar een bepaalde feature ID.

**Comment by ghost** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[QGis plugin - productiewaardig] improve performance [?]](https://trello.com/c/ghw8vEmx/1734-qgis-plugin-productiewaardig-improve-performance)

**Comment by Jonasvsl** [comment]
out of date
