### ISSUE TITLE
toolbox widget uifile inconsistency

### ISSUE THREAD

**Issue by jackieleng** [nens/threedi-results-analysis#16]
Opening `threedi_toolbox_dockwidget_base.ui` in Qt designer gives this error/warning:
`Attempt to add a layout to a widget 'Form' (QDockWidget) which already has an unmanaged layout of type QDockWidgetLayout. This indicates an inconsistency in the ui-file.`
The file also doesn't have the correct layout in Qt designer.

However, using the file in the code itself doesn't seem to give any problems. It's probably a good idea to recreate the file using Qt designer so we can edit it again in Qt designer.

**Comment by Jonasvsl** [comment]
out of date.
