### ISSUE TITLE
Inconsistency QGIS graph

### ISSUE THREAD

**Issue by GeOdin** [nens/threedi-results-analysis#173]
De schaal van de y-as van grafiek lijkt niet overeen te komen bij in- en uitzoomen.

![image](https://user-images.githubusercontent.com/13179397/30025320-45b1f87c-9178-11e7-8253-3b0f1776901e.png)

![image](https://user-images.githubusercontent.com/13179397/30025329-4e6cea6c-9178-11e7-8f4b-e974a42b0ad6.png)

De top gaat van 64 um3/s naar 0.064 mm3/s en wordt dus met een factor 1000 verkleint, maar de eenheid zou um/s en mm/s moeten zijn.

Het probleem komt van een functie die in QGIS zelf zit (Ber).

**Comment by Jonasvsl** [comment]
@RichardB9 
is this still relevant ? I think we can close this, right?

**Comment by RichardB9** [comment]
I can't reproduce the bug so I'll close it.
