### ISSUE TITLE
[RFC] Control structures: known issues/ wensen

### ISSUE THREAD

**Issue by GeOdin** [nens/threedi-results-analysis#179]
* Validatie invoer van alle velden (in eerste instantie table oplopendheid en weigths opgeteld 1)
* Toevoegen van 'name' en 'description' voor v2_measure_map en v2_measure_group, zoat het voor de gebruiker duidelijker is om welke meetpunten en meetgroepen het gaat.
* Selecteren van control group id in v2_global_settings voor nu nog handmatig. Dialoogvenster/menu/dockwidget moet nog gemaakt worden. 
* Wie gaat documentatie schrijven/docuvensters vullen?
* Load measuring stations by selecting them on the map

**Comment by renierkramer** [comment]
**Table Control probleempje:** ik heb een table control regelingen in jenkins (testje 259) waarin ik tegen de volgende "lastigheid" aanliep. In de control_table moet de meetwaarde oplopend zijn in de tabel (onafhankelijk van of je < of > regeling hebt). Dat is nu verplicht (anders krijgt gebruiker tijdens bin/pyflow een fortran error en wordt die ene regeling geskipped. Mijn wens is dat de QGIS plugin dit afvangt voor de gebruiker.

**Voorbeeld:** Ik heb een stuw die ik wil laten reageren op bovenstroomse randvoorwaarde die van 10mNAP naar 0mNAP loopt. Mijn regeling is bijvoorbeeld:

als meetwaarde < 8mNAP dan stuwhoogte 7mNAP en vervolgens
als meetwaarde < 5mNAP dan stuwhoogte 4mNAP
Wat ik dan invul in de (<) table control is 8;7#5;4 <-- En dat gaat dus fout.

**Oplossing:** zou kunnen zijn dat onafhankelijk van hoe de gebruiker zijn table_control invult (oplopend, aflopend, random) dit achter de schermen oplopend in de control_table komt. Dat gaat een hoop ellende schelen ;)
