### ISSUE TITLE
Release to plugins.3di.live

### ISSUE THREAD

**Issue by leendertvanwolfswinkel** [nens/threedi-results-analysis#18]
Same implementation as https://github.com/nens/threedi-schematisation-editor/issues/43

**Comment by leendertvanwolfswinkel** [comment]
do you need the code to be on the master branch to prepare the release? @erpas is still fixing a few things so I can test the stuff that is supposed to be released, that's why it is not yet on the master branch

**Comment by benvanbasten-ns** [comment]
Ok, it doesn't need to be on the main branch, but I do need the metadata.txt etc. So for now, I'll branch off the "gpkg_converter" branch.
