### ISSUE TITLE
Processing algorithm to generate computational grid

### ISSUE THREAD

**Issue by leendertvanwolfswinkel** [nens/threedi-results-analysis#2]
In 3Di, the computational grid is generated from the schematisation. A schematisation always consists of a sqlite. Most schematisations also have a DEM, but this is not strictly necessary. The computational grid is stored in a `gridadmin.h5` file. This file is generated on the server after users upload their data. This functionality is available in github.com/nens/threedigrid-builder

However, users that are building/editing their schematisation often want to see the computational grid while they are making their edits. We want to make it possible for users to generate the gridadmin.h5 file locally in QGIS / 3Di Modeller Interface. 

The way we want to implement this now is as a Processing Algorithm, named 'Generate computational grid'. There are already various processing algorithms provided by the 3Di Toolbox (https://github.com/nens/ThreeDiToolbox/tree/master/processing). Please add this new algorithm to the group '3Di' > 'Schematisation'.

input: spatialite + dem (.tif)
output: gridadmin.h5
test data: https://we.tl/t-UU0ttdSXLI

Requirements:
- If a `SchematisationError` occurs, please give user feedback (popup window) with the text "The selected Spatialite does not have the latest migration. Please migrate your Spatialite to the latest version." Use `tuindorp_old_schema_version.sqlite` to test this
- Check if the DEM is the same as referenced in the spatialite (`v2_global_settings.dem_file`; this is a path relative to the location of the spatialite). If there is a mismatch, please give user a warning (popup window) with the text "Warning! The selected DEM is different from the DEM that is referenced in the Spatialite. Continue? [OK] | [Cancel]" 
- Later, when the 'convert to geopackage' algorithm is ready, the 'generate computational grid' will have to be changed so that it outputs a geopackage (i.e. chain this algorithm to the 'convert to geopackage' algorithm. The reason that we want to first convert to gridadmin.h5 and then to geopackage is that we want to make sure that all gridadmin.h5 files (generated locally or on the server) are handled in the exact same way.

In the future, we will probably further integrate this functionality with the other plugins (e.g. Models & Simulations, Schematisation Editor). "Integration" means e.g. not having to browse for the spatialite and not having to manually select an output directory for the `gridadmin.h5`. For now, we can just let users select the Spatialite,  DEM and output file path manually.

**Comment by leendertvanwolfswinkel** [comment]
Feedback from testing:

- [ ]  Please set 'Save as type' filter to '*.h5', so that if I type 'my_gridadmin', the file will be saved as 'my_gridadmin.h5' I save the file 
![image](https://user-images.githubusercontent.com/26224299/161755021-3e2ac73c-6270-44be-97b0-d9c97cdf5c90.png)

- [ ] If I select only a spatialite and no DEM, the algorithm fails. Processing algorithm feedback: ```
QGIS version: 3.16.9-Hannover
QGIS code revision: 9f8d2f7942
Qt version: 5.11.2
GDAL version: 3.1.4
GEOS version: 3.8.1-CAPI-1.13.3
PROJ version: Rel. 6.3.2, May 1st, 2020
Processing algorithm…
Algorithm 'Generate computational grid' starting…
Input parameters:
{ 'ALLOW_DIFF_DEM' : False, 'INPUT_DEM' : '', 'INPUT_SPATIALITE' : 'C:\\Users\\leendert.vanwolfswin\\OneDrive - Nelen & Schuurmans\\Documents 1\\3Di\\Eygelshoven - Huidig-verbeterd\\work in progress\\schematisation\\eygelshoven-huidig-verbeterd.sqlite', 'OUTPUT' : 'C:/Users/leendert.vanwolfswin/Downloads/my_gridadmin.h5' }

Reading DEM settings from: C:\Users\leendert.vanwolfswin\OneDrive - Nelen & Schuurmans\Documents 1\3Di\Eygelshoven - Huidig-verbeterd\work in progress\schematisation\eygelshoven-huidig-verbeterd.sqlite|layername=v2_global_settings

C:\Users\leendert.vanwolfswin\OneDrive - Nelen & Schuurmans\Documents 1\3Di\Eygelshoven - Huidig-verbeterd\work in progress\schematisation\rasters/dem_huidig.tif
Warning! The selected DEM is different from the DEM that is referenced in the Spatialite.
Execution failed after 0.23 seconds

Loading resulting layers
Algorithm 'Generate computational grid' finished
```

- [ ] For all sqlites that I have tried to process, I get the message "The selected Spatialite does not have the latest migration. Please migrate your Spatialite to the latest version.":
```
QGIS version: 3.16.9-Hannover
QGIS code revision: 9f8d2f7942
Qt version: 5.11.2
GDAL version: 3.1.4
GEOS version: 3.8.1-CAPI-1.13.3
PROJ version: Rel. 6.3.2, May 1st, 2020
Processing algorithm…
Algorithm 'Generate computational grid' starting…
Input parameters:
{ 'ALLOW_DIFF_DEM' : False, 'INPUT_DEM' : 'C:\\Users\\leendert.vanwolfswin\\Downloads\\grid admin generator test schematisations\\tuindorp\\rasters\\dem_tuindorp_oostzaan.tif', 'INPUT_SPATIALITE' : 'C:\\Users\\leendert.vanwolfswin\\Downloads\\grid admin generator test schematisations\\tuindorp\\tuindorp_migrated.sqlite', 'OUTPUT' : 'C:/Users/leendert.vanwolfswin/Downloads/my_gridadmin.h5' }

Reading DEM settings from: C:\Users\leendert.vanwolfswin\Downloads\grid admin generator test schematisations\tuindorp\tuindorp_migrated.sqlite|layername=v2_global_settings
C:\Users\leendert.vanwolfswin\Downloads\grid admin generator test schematisations\tuindorp\rasters\dem_tuindorp_oostzaan.tif
C:\Users\leendert.vanwolfswin\Downloads\grid admin generator test schematisations\tuindorp\rasters/dem_tuindorp_oostzaan.tif
Reading input schematisation...
Reading subgrid input...
Constructing 2D computational grid...
Constructing 1D computational grid...
Incorrect input Spatialite file:
The selected Spatialite does not have the latest migration. Please migrate your Spatialite to the latest version.
Execution failed after 0.53 seconds

Loading resulting layers
Algorithm 'Generate computational grid' finished
```

**Comment by erpas** [comment]
As it turns out, the underlying `threedigrid_builder` method for creating grid files has a non-optional parameter for DEM.
It would return `SchematisationError` when DEM is not defined, so users are obliged to specify a DEM for the algorithm.

Schematisation errors are now properly recognized and reported - no more "please migrate your Spatialite".

**Comment by leendertvanwolfswinkel** [comment]
What I mean with making the DEM optional is that users should only specify it if they want to use a different DEM than what is specified in the spatialite. But now that I think about it again, that would be confusing for many users. I propose to remove the DEM parameter from the Processing Algorithm and always find it by reading the reference in the spatialite's global settings table

**Comment by leendertvanwolfswinkel** [comment]
Also, it should be possible to generate a grid without a DEM for pure 1D schematisations... so i am a bit surprised that this parameter is non-optional

**Comment by erpas** [comment]
The DEM parameter was removed as suggested.

It is possible to create a gridamin file without DEM only for non-2D cases. Otherwise a SchematisationError is raised with a warning that a DEM is required.

**Comment by leendertvanwolfswinkel** [comment]
In general it works well. Feedback:

- [ ] If I select the option to output to temporary file, I get the following error:
```
QGIS versie: 3.22.3-Białowieża
QGIS coderevisie: 1628765ec7
Qt versie: 5.15.2
Python versie: 3.9.5
GDAL versie: 3.4.1
GEOS versie: 3.10.0-CAPI-1.16.0
PROJ versie: Rel. 8.2.1, January 1st, 2022
PDAL versie: 2.3.0 (git-version: 9f35b7)
Algoritme begonnen om: 2022-06-15T10:37:43
Algoritme 'Generate computational grid' starten...
Parameters invoer:
{ 'INPUT_SPATIALITE' : 'C:\\Users\\leendert.vanwolfswin\\OneDrive - Nelen & Schuurmans\\Documents 1\\3Di\\Test Spatialite 4 op productie\\work in progress\\schematisation\\Test Spatialite 4 op productie.sqlite', 'OUTPUT' : 'TEMPORARY_OUTPUT' }

Reading DEM settings from: C:\Users\leendert.vanwolfswin\OneDrive - Nelen & Schuurmans\Documents 1\3Di\Test Spatialite 4 op productie\work in progress\schematisation\Test Spatialite 4 op productie.sqlite|layername=v2_global_settings
DEM raster referenced in Spatialite settings:
C:\Users\leendert.vanwolfswin\OneDrive - Nelen & Schuurmans\Documents 1\3Di\Test Spatialite 4 op productie\work in progress\schematisation\rasters/dem_tuindorp_oostzaan.tif
Traceback (most recent call last):
File "C:\Users/leendert.vanwolfswin/AppData/Roaming/QGIS/QGIS3\profiles\3Di Results Analysis/python/plugins\threedi-results-analysis\processing_provider\gen_comp_grid.py", line 124, in processAlgorithm
make_gridadmin(input_slite, set_dem_path, output, progress_callback=progress_rep)
File "C:\Users/leendert.vanwolfswin/AppData/Roaming/QGIS/QGIS3\profiles\3Di Results Analysis/python\threedigrid_builder\application.py", line 243, in make_gridadmin
raise ValueError(f"Unsupported output format '{extension}'")
ValueError: Unsupported output format '.file'

Execution failed after 0.70 seconden
```

**Comment by leendertvanwolfswinkel** [comment]
Yes!
