### ISSUE TITLE
Initieel technisch ontwerp

### ISSUE THREAD

**Issue by bastiaan-roos** [nens/threedi-results-analysis#21]
**Samenvatting functionele behoefte**
Om goed met 3di te kunnen werken heeft de (interne) 3di modelleur behoefte aan tools voor:
1. Resultaten bekijken en verwerken;
2. Maken van model en controle van data en schematisatie.

Voor beide handelingen is een basic opzet aanwezig en aangevuld met queries van modelleurs kunnen deze taken (moeizaam) worden uitgevoerd. Betere tools, met name rond het werken met resultaten, zijn noodzakelijk. Ook is er nog geen ondersteuning voor openwater schematisaties. 
Voor het maken van modellen is het ideaal een standaard werkwijze met stappenplan en ondersteunende tools in de vorm van een toolbox (zoals we vroeger hadden voor Sobek modellen), het huidige werken met tools (queries) is vrij technisch en er zijn veel versies van (door modelleurs ontwikkelde) queries.
De gewenste functionaliteiten zijn voor de modelleur/ hydroloog, een specialist die een unieke rol heeft bij het begin en eind van de zogenaamde modellentrein, zie het volgende figuur. Bij het begin (modellen maken en aanpassen) en het eind (analyse en naverwerking) is vrijheid en flexibiliteit gewenst.

![image](https://cloud.githubusercontent.com/assets/1068991/14830704/45b5a3f8-0bf2-11e6-84df-5ff2a8b886f9.png)

In de memo ‘Tools voor 3di modelleurs – 8 maart 2016’ is de functionele behoefte verder uitgewerkt. De eerste prioriteit ligt in het werken met 3di resultaten voor versie 2 (zowel riolering als oppervlaktewater).

**Technische uitwerking**
Het volgende moet duidelijk worden om een technische lijn uit te zetten voor de ontwikkeling van tools voor de 3di modelleur:
1. Op welk ‘systeem’ bouwen we de ondersteunende tools;
2. Hoe verhouden de tools zich tot de andere systemen in het 3di landschap;
3. Wat zijn de (technische/ kwaliteits) eisen/ uitgangspunten die we aanhouden bij de ontwikkeling.

**Keuze van het systeem waarbinnen de tools worden ontwikkeld**
We hebben de volgende ‘logische’ mogelijkheden voor de ontwikkeling van de tools. Per mogelijkheid staan ook de voordelen en nadelen genoemd. De mogelijkheden zijn:
_1. Bouw in Lizard (of site op basis van de Lizard backend):_
- \+ bestaand platform waarop veel kennis aanwezig is binnen N&S. Tevens B&O en support  geregeld;
- \+ synergievoordelen. Nieuwe functionaliteiten kunnen direct breder worden ingezet.
- +/- bestaande functionaliteiten kunnen hergebruikt worden. Data is al aanwezig en functionaliteiten rond 2d resultaten komen eraan. 1d resultaten nog niet ondersteund. De wensen van modelleurs zijn waarschijnlijk wel te specialistisch voor wat we met Lizard willen ondersteunen.
- – Te weinig flexibel voor de beoogde doelgroep (specialisten)
- – Met name geschikt voor resultaten, niet voor het interactief maken van modellen. 

_2. Ontwikkeling in een 3di-turtle-server (combinatie PostGIS/ scripts via API eventueel met beperkte QGIS plugin):_
- \+ bestaand platform binnen N&S. Kennis aanwezig, zeker met bewerkingen met PostGIS databases (queries, etc.)
- \+ Door link me QGIS (via standaard PostGIS link) veel andere tools beschikbaar – gewenste flexibiliteit binnen handbereik.
- \+ PostGIS wordt momenteel al gebruikt door (interne) modelleurs. 
- \+ Meer code herbruikbaar (ook als bijvoorbeeld iets via ArcGIS moet gaan werken).
- – voor QGIS plugin deel nog weinig ervaring
- – Installatie van een Ubuntu server noodzakelijk (verbinding of via internet of installatie lokaal)
- – Geen infrastructuur aanwezig voor resultaten, moet ontwikkeld worden (link met Lizard?).

_3. Plugin in QGIS (gebruikmakend van lokale bestanden: spatialite en netCDF’s):_
- \+ QGIS wordt veel gebruikt door de (interne) modelleurs. Door volledige integratie in QGIS kan de beste ‘user experience’ worden geleverd.
- \+ er zijn veel andere tools beschikbaar in QGIS, waarmee de gewenste flexibiliteit wordt bereikt. 
- \+ (en een beetje -) Model en resultaten kunnen met allerlei andere data worden gecombineerd, de gebruiker is zelf de baas over de (model en resultaten) bestanden. Verantwoordelijkheid over data/ resultaten beheer kan bij gebruiker worden gelegd.
- \+ de tool kan ‘offline’ worden gebruikt (voordeel in buitenland).
- \+ naast QGIS hoeft er niks/ weinig worden geïnstalleerd. Daarmee laagdrempelig t.o.v. gebruik PostGIS.
- – nieuw platform. Als Nelen & Schuurmans hebben we hier weinig ervaring mee. Vraag is hoe snel we opgang zijn met ontwikkeling en of we een schaalbare architectuur kunnen vinden. 
- – Er zal relatief weinig code herbruikbaar zijn (alleen via copy-paste).
- – distributie. De plugin wordt op elke computer geïnstalleerd, dit mag niet te veel werk/ ondersteuning met zich meebrengen.
- – support. Installatie is decentraal, daardoor lastiger bij problemen op te lossen.

Vanuit de modelleur gezien is een integratie van de tools in QGIS, de omgeving waarin ze vaak werken, het meest ideaal. Optie 1, Lizard, valt hierdoor (voorlopig) af. We zien wel een mogelijkheid met integratie van een resultaten database, waarbij resultaten uit de lizard-backend worden geserveerd (via WMS/ WFS) of worden gedownload vanuit Lizard naar QGIS.

Vanuit de gebruiker is optie 3 het meest ideale. Met name voor de resultaten is het handig als iemand de resultaten in QGIS kan gebruiken en zijn model (beperkt) kan bewerken, zonder dat hiervoor zware installaties nodig zijn.  Zo kunnen we klanten resultaten meegeven, die ze zelf nog kunnen bekijken en verwerken.

Optie 2 blijft een goede optie voor de (zwaardere) en geavanceerdere bewerkingen bij het model maken. Deze worden alleen maar uitgevoerd door degene die nieuwe modellen opzetten, en dit is maar een (deel)  van de modelleurs. Een link naar/ opzetten van een Ubuntu server met PostGIS is in dat geval te rechtvaardigen.

Voor het werken met resultaten (de eerste stap in onze ontwikkelingen) is ons voorstel om – onder voorbehoud dat we een paar minpunten kunnen ondervangen - optie 3 te kiezen, een volledige QGIS plugin, gebruik makend van de spatialite en netCDF bestanden.

**Pilot**

Succes is afhankelijk in hoeverre we goed met de minpunten kunnen omgaan. Om dit uit te zoeken hebben we tijd besteed aan het opzetten van onze eerste opzet van 3 tools (grafieken, sideview, naverwerkings tool). Onze ervaringen hierbij waren:

Nieuw platform: 
- Voor QGIS interface onderdelen moet je een steile leercurve door. Het interface platform QT waarop QGIS is gebaseerd (1) kan veel, (2) is erg C++ georiënteerd, (3) maar er zijn genoeg voorbeelden te vinden (kwestie van veel Googlen). 
- Voor een schaalbare opzet moet een MVC opzet worden gehanteerd. Het is gelukt om deze structuur binnen de gestelde termijn op te zetten. De code blijft daardoor overzichtelijk (en daarmee waarschijnlijk schaalbaar).
- QGIS onderdelen zijn minder goed gedocumenteerd, zeker als bijzondere functies nodig zijn. Het lezen van de c++ source code helpt in deze gevallen (het is opensource software, dus dit kan!).
- Er kunnen op deze manier heel gebruiksvriendelijke tools  worden gemaakt (in een specialistische omgeving met veel knoppen) die de modelleur bij zijn werk kan ondersteunen.
- Herbruikbaarheid van code is inderdaad zeer beperkt, omdat door de lokale distributie het gebruik van (externe) pakketten lastiger wordt.

Distributie: 
- Hier was al ervaring mee binnen N&S voor een grondwater tool. De afhankelijkheid van een gecompileerde C++ binding (voor netCDF4) was een mooie use-case onder Windows. Het is gelukt om deze mee te leveren bij de installatie, waardoor de installatie binnen een minuut te doen is.

Support:
- Dit moeten we duidelijk aangeven in readme/ disclaimer/ about. Geen garantie op ondersteuning (tenzij je ervoor betaald natuurlijk). Verder is het opensource, dus iedereen kan altijd een pull request maken met een bug-fix.  

Op basis van deze bevindingen willen we voor het resultaten deel voorlopig doorgaan met optie 3 (waarbij we met 2d resultaten kijken hoe we kunnen aansluiten bij Lizard) en zodra we gaan kijken naar tools voor model ontwikkeling zullen we ook optie 2 bekijken (Postgis + tools op Ubuntu server). 

**Verhouding met andere tools**

Zie het volgende figuur. Er is een overlap met 3di-Turtle, spatialite en de model generatie scripts (afstemming erg belangrijk + nadere afspraken over wie waarvoor verantwoordelijk is). Belangrijk overdrachtspunt is de modellendatabase. 

_plaatje_

Aan de resultaten kant zullen de resultaten gedownload worden van de FTP server of uit Lizard (resultaten database). In eerste instantie zullen we vooral de bestanden downloaden, maar integratie met de back-end van Lizard ligt voor de hand en is ook wenselijk. Stap 1 zou zijn een selectie en download, stap 2 het gebruiken van de 2d resultaten en mocht het beschikbaar komen kan ten slotte ook de 1d resultaten ‘gestreamd’ worden naar de QGIS plugin. Afstemming en integratie dus ook aan deze kant. 

Omdat er gebruik wordt gemaakt van resultaten zal afstemming over wegschrijven van resultaten, metadata, etc ook nodig zijn.

**Technische eisen en uitgangspunten bij ontwikkeling**

Functioneel-Technisch:
- Installatie is binnen 5 minuten te doen. Een update binnen een minuut.
- Te gebruiken (en getest) onder Windows (7 +10) en Ubuntu.
- Support/ getest onder de laatste LTS en laatste versie (momenteel 2.08 en 2.14)

Data bestanden en omliggende systemen:
- Voor resultaten nemen we de netCDF’s en Spatialite als uitgangspunt
- In de spatialite komen geen resultaten (die linken we bijvoorbeeld via een csv of iets dergelijks). In de spatialite komen eventueel wel resultaten van model checks.
- Voor werken met datasets worden zoveel mogelijk abstractie lagen gebruikt (datasources), zodat we in de toekomst goed kunnen switchen van bron (bijvoorbeeld naar Lizard data of van de spatialite naar PostGIS).
- .....

Code/ ontwikkeling:
- Opbouw code volgens Models en views, gebruikmakend van signals om interacties te linken.
- Alle onderdelen die communiceren met de 3di data bestanden moeten voorzien zijn van unit-test, zodat we kunnen garanderen dat de juiste data wordt gebruikt. Voor de interface onderdelen wordt een testplan opgesteld, die handmatig wordt doorlopen.
- Docstrings google style

**Vervolgstappen**
- [ ] Technische eisen en uitgangspunten nog verder uitwerken en categoriseren
- [ ] Figuur toevoegen met links naar andere systemen
- [ ] Ontwerp laten reviewen door WOM.
- [ ] De eerste 3 tools afmaken en intern laten gebruiken.
- [ ] Code structuur zelf reviewen en verbeteren op basis van ervaring na eerste fase.
- [ ] TO updaten.
- [ ] Wensen rond netCDF's en Lizard resultaten database overleggen en vastleggen in een RFC
- [ ] Code en geupdate TO laten reviewen door WOM
- [ ] Ontwerp maken voor de eerst volgende tools en budget regelen

**Comment by JoepGrispen** [comment]
Bastiaan ik zou onderstaand punt niet benoemen. Het is namelijk onzeker (woordje waarschijnlijk") en ik kan me niet herinneren dat we dit op deze manier met elkaar besproken hebben. 

– Vanwege de hoge standaarden die worden gehanteerd, zal de ontwikkeling waarschijnlijk langer duren.

Belangrijkste negatieve punt staat nu ook onderaan. ik zou die als eerste noemen.

– Te weinig flexibel voor de beoogde doelgroep (specialisten)

**Comment by ghost** [comment]
FTP voor NetCDF download komt te vervallen.
Met welke versies van QGIS werkt de plugin?

**Comment by bastiaan-roos** [comment]
@JoepGrispen : verwerkt, 
@beralbers : 
- Als je FTP komt te vervallen ga ik ervan uit dat er een alternatief is waar we zowel de netCDF als de id_mapping halen. Is hier al iets over bekend?
- Plugin is getest onder 2.08 en 2.14. Zal deze toevoegen aan de uitgangspunten.

**Comment by ghost** [comment]
Ja ze krijgen een nieuwe plek. Vanmiddag heb ik hier overleg over met de Lizarders, zal het terugkoppelen als duidelijk is waar dit gaat worden.

**Comment by arjenvrielink** [comment]
op verzoek van @beralbers en @JoepGrispen wat opmerkingen over het ontwerp (als mosterd na de maaltijd):

ik vind het moeilijk om op details in te gaan omdat ik waarschijnlijk niet genoeg context / domeinkennis heb. Dat brengt mij tegelijkertijd tot de volgende algmene punten ter verbetering:
1. Het heeft er de schijn van dat voor dit ontwerp geschreven werd het doel al bekend was en dat het daar naar toe geschreven is. Dat is een beetje raar. (net als deze opmerking :) )
2. De systemen van Nelen & Schuurmans hebben tot nu toe nogal last van wat 'stream of consciousness architecture' heet: de architectuur van het systeem volgt de gedachtengang van de, in dit geval, modelleur. Dit ontwerp neigt daar ook naar, zeker het 'modellentrein' plaatje. Dat is typisch zoals een modelleur zich het systeem voorstelt. Dat wil niet zeggen dat dat technisch ook de beste architectuur is.
3. De systemen van Nelen & Schuurmans hebben tot nu toe nogal last van het feit dat politieke keuzes onderdeel worden van de technische architectuur. Die zaken moeten los van elkaar staan. In dit ontwerp wordt ook weer gesproken over 'de NetCDF' en 'de spatialite'. Dat zijn politieke randvoorwaarden die de techniek in geslopen zijn en vervolgens uitgangspunt geworden zijn. Het is niet wenselijk dat politieke keuzes invloed hebben op de de technische architectuur.
4. De technische architectuur van de systemen van Nelen & Schuurmans hebben nogal de neiging om een afspiegeling te zijn van de marketingfolder: in dit ontwerp wordt ook weer gesproken over 'systemen in het 3di landschap' en 'site op basis van de Lizard backend'. Er is technisch geen '3di landschap' en 'Lizard backend'. Technisch is er een rekenkern, een plek waar we assets opslaan, een plek waar we timeseries opslaan, een plek waar modellen staan, een module om modellen te editen, enz.
5. "Bij de ontwikkeling is haast, ..." hoera maar dat hoort niet thuis in een ontwerp. Daarmee impliceer je dat je jezelf een alibi verschaft voor alles wat niet optimaal is in het ontwerp. Het uitgangspunt van het ontwerp moet het beste ontwerp zijn. Daarna kun je op basis van randvoorwaarden concessies doen. Randvoorwaarden dienen niet verward te worden met uitgangspunten.

Technisch gezien zit de QGIS plugin prima in elkaar. De uitgangspunten zijn dubieus en geen gezonde basis om systemen op te ontwerpen. Met een beetje meer visie hadden we nu een QGIS plugin gehad die breder en vooral consistenter inzetbaar was geweest.

**Comment by bastiaan-roos** [comment]
@arjenvrielink . Al hoewel het eerder had gekund, is het zeker geen mosterd na de maaltijd. We hebben nu de eerste 3 tools ontwikkeld, maar er zijn plannen om verder te gaan met '3di tools voor modelleurs'. Het technisch ontwerp blijft daarbij relevant met de vraag hoe we verder gaan. Zeker de keuze waar we wat maken zouden we (zoals aangegeven) bijna per tool moeten bekijken.
Verder nog een reactie op je punten:
1. Ja, het is opgeschreven toen we een voorkeurs richting hadden, maar deze afweging is zeker wel gemaakt. Zo heb ik gekeken naar iD (https://github.com/openstreetmap/iD) als online tool - een tool waarvan ik de interactie goed genoeg vind, custom ontwikkelingen hiermee is echter nog lastig. Ook is gekeken naar Postgres - Python Procedural Language - en Foreign data wrappers. 
2. Dit plaatje is gezet in de functionele context en afbakening. Dit is inderdaad zoals het modelleer proces eruit ziet. Een werkproces (met knelpunten) als functioneel uitgangspunt lijkt mij een goede manier om tot iets te komen waar de modelleur iets aan heeft.
3. Ik snap werkelijk niet wat 'spatialite' en 'NetCDF' te maken hebben met politieke keuzes. Voor mij zijn het 2 (technische) bestandstype die nu binnen 3di worden gebruikt en de keuze daarvoor is ooit op functionele gronden gemaakt. Kan je dit verder toelichten?
4. Als dit niet de benamingen zijn die bij de ontwikkelaars worden gebruikt, heb je dan een overzichtsplaatje met hoe jullie onderdelen benoemen, dan zal ik deze naamgeving aanpassen.
5. Heb ik aangepast, alhoewel ik van mening ben dat tijd constraints zeker horen tot de functionele uitgangspunten (daar gaat de eerste paragraaf over) en dus wel input zijn voor een ontwerp. Niet als excuus, maar wel om te kijken hoe je binnen deze grenzen gefaseerd kan werken naar een 'ideaal plaatje'.

Nu er plannen liggen om door te ontwikkelen, ben ik benieuwd wat jou betere uitgangspunten lijken om  tot een breder inzetbare plugin te komen.
