### ISSUE TITLE
Move functionality to 3Di Toolbox

### ISSUE THREAD

**Issue by leendertvanwolfswinkel** [nens/threedi-results-analysis#22]
The two processing algorithms should be grouped under 3Di > Computational Grid

**Comment by leendertvanwolfswinkel** [comment]
Why? For users I think it is easier to have just one single group. Is there any technical reason to want separate groups?

**Comment by ldebek** [comment]
No technical reason. Just to make it more visible to user that there is something new to play with. :)

**Comment by ldebek** [comment]
Available under: https://github.com/nens/ThreeDiToolbox/tree/results_analysis_providers
