### ISSUE TITLE
qgis segmentation fault when importing h5py

### ISSUE THREAD

**Issue by jackieleng** [nens/threedi-results-analysis#247]
Using Ubuntu 18.04
Steps to reproduce:
installed QGIS 2.18.20 with LTR repo:
```
sudo apt install qgis python-qgs qgis-plugin-grass
```

Then installed hdf5:

```
$ sudo apt install libhdf5-serial-dev
```

Checking the version:

```
$ h5cc -showconfig

...
                   HDF5 Version: 1.10.0-patch1                                                                                                                                                                                                
...
```

Installed h5py 2.7.1:

`sudo pip install h5py`

```
>>> print h5py.version.info

Summary of the h5py configuration
---------------------------------

h5py    2.7.1
HDF5    1.8.18
Python  2.7.15rc1 (default, Apr 15 2018, 21:51:34)
[GCC 7.3.0]
sys.platform    linux2
sys.maxsize     9223372036854775807
numpy   1.14.3
```

Using this setup, QGIS crashes with a segfault when you try to import `h5py` in QGIS. I think the problem is with the h5py wheel being built against HDF5 1.8.18 and apt version of HDF5 being 1.10.0-patch1. Strangely enough it only crashes in QGIS and not in a normal python shell. This might have to do with QGIS being also built against a specific HDF5 version.

I've been able to fix this by building h5py instead of using the wheel, e.g. using:

```
$ sudo pip install --no-binary=h5py h5py
```
```
In [2]: print h5py.version.info
Summary of the h5py configuration
---------------------------------

h5py    2.7.1
HDF5    1.10.0
Python  2.7.15rc1 (default, Apr 15 2018, 21:51:34) 
[GCC 7.3.0]
sys.platform    linux2
sys.maxsize     9223372036854775807
numpy   1.14.3
```

**Comment by reinout** [comment]
Fixed by using ubuntu 18.04 LTS and the qgis 3.4.x LTR now.
