### ISSUE TITLE
v2_surfaces worden niet ingeladen

### ISSUE THREAD

**Issue by leendertvanwolfswinkel** [nens/threedi-results-analysis#251]
Bij het inladen van een model wordt v2_impervious_surface ingeladen, maar soms heeft je model v2_surfaces ipv v2_impervious_surfaces en wil je dus die zien.

**Comment by jackieleng** [comment]
staat in Jira. Weet niet wanneer het wordt opgepakt, is het dringend?

**Comment by leendertvanwolfswinkel** [comment]
Naar mate er meer internationale gebruikers komen wordt het dringender
lijkt me. Die gebruiken de impervious surfaces niet denk ik

Op ma 9 jul. 2018 18:05 schreef Jackie Leng <notifications@github.com>:

**Comment by jackieleng** [comment]
Weet je toevallig een model waar een v2_surface in zit? En heb je toevallig ook een styling QML bestand die we zouden kunnen gebruiken ervoor?

**Comment by Jonasvsl** [comment]
is solved in current version
