### ISSUE TITLE
[RFC] RasterChecker

### ISSUE THREAD

**Issue by renierkramer** [nens/threedi-results-analysis#314]

**Comment by renierkramer** [comment]
**Introduction**
Users would like to be able to check the quality of the rasters of ther 3Di model.
Quality is represented by multiple technical requirements (below).

**Current situation**
Users get feedback at a late stage (1. model creation locally in QGis, 2. push to models.lizard.net, 3. then INPY server runs makegrid and gives feedback (on 3di.lizard.net/models)
Problem is that:
C1. this feedback is late (we can already do some checks at stage 1 (in QGIS, before push)
C2. this feedback is most of the times somewhat critical

**Requirements**
R1) enable rasterchecks in Qgis 3.xx (python 3)
R2) check for all possible raster mistakes
R3) return readable feedback to user
R4) enable tool for rasters from 4 pixels up to 1 billion (data+nodata) pixels
R5) this tool must return feedback faster than the 'push-to-modellendb' route
R6) tool leest padverwijzing naar raster uit de sqlite. De tool moet werken voor sqlite van nu, maar ook op sqlite die zegmaar 3 jaar geleden is gemaakt..

**gebruik checks:**
1. gebruiker opent qgis en opent de 3Di toolbox (rode gereedschapskist jonge!)
2. onder 'Step 1 - Check data' zit dan 'raster_checker.py'
3. gebruiker selecteert de sqlite en klikt op 'ok'
![image](https://user-images.githubusercontent.com/13031554/50091597-182d5d00-020c-11e9-8a8f-fd69459e0a90.png)
4. gebruiker krijgt feedback:
a) een .log file waarin - per model entree - raster check feedback is gesommeerd
b) een .shp file met daarin point geometry daar waar 
b1) dem = data en andere raster = nodata
b2) dem = nodata en andere raster = data 

**Raster checks**
1. bestaat de referentie uit de v2_global_settings wel ?
2. Geen speciale chars in referentie ? *
3. Is extensie wel een .tif ?
4. kun je het raster inlezen ?
5. single band ?
6. float_32 ? 
7. is het raster gecomprimeerd? compression=deflate ?
8. is de nodata=-9999 ?
9. is de projectie compleet ? 
10. pixels zijn vierkant ?
11. logische min, max waarden ?
(( in geval van meerdere rasters per entree: ))
12. is de extent van het raster gelijk aan andere rasters ? *
13. komen alle raster overeen ? 

2* windows: aantal chars filename moet <257 chars zijn (maar daar lopen windows users zelf wel tegenaan. De max len absolute padverwijzing lopen windows users ook zelf tegenaan)
13* dem is leiden als we rasters gaan vergelijken of nodata in het ene raster wel nodata is in het andere raster (zelfde geldt voor data pixels)

**Technische uitdagingen**
1. een uitdaging is om de tool snel te houden voor grotere rasters (zie R4) Dit kan middels:
a We willen raster blockwise gaan scannen
b Met gdal kun je raster in memory inlezen (zonder het hele raster eerst inlezen en dan slicen)

2. de meeste rasterverwijzingen komen uit de global_settings, maar ook uit bijv v2_groundwater. Het wordt een uitdaging om alle rasterverwijzingen uit de sqlite te halen. Omdat  
a) de kolommen vd v2_global_settings de afgelopen jaren is veranderd
b) er zijn tabellen naast de v2_global_settings gekomen waarin ook rasterverwijzingen staan
c) het raster checken moet met global_settings entree gebeuren







**Gedaan:** 
1. inmiddels zijn alle checks geschreven. 
2. de schempjes zijn klaar
3. schempjes reageren op onderhangende functies
4. .log file wordt weggeschreven naar gebruiker local machine
5. .shp file wordt weggeschreven naar gebruiker local machine
6. technische uitdaging 2 is opgelost

**Openstaand** 
1. De .log file gebruiksvriendelijk invullen (per global settings entree) --> 1 dag
2. Technische uitdaging 1 heb ik nu werkend voor kleine rasters. Echter bij raster van 10m pixels loopt geheugen vol. Ik heb daar nog wat oplossingen voor bedacht (in het kort: op een slimme manier de generators gebruiken ipv op een domme..) --> 2 dagen
3. testen --> 1 dag
3. test schrijven --> 3 dagen
4. alles naar python 3 omschrijven --> 1 dag

**Risico**
Als mn oplossing voor openstaand punt nr 2 niet werkt, dan klop ik bij Jelle aan (want dat moeten we waarschijnlijk fundamenteel raster checker anders opbouwen zodat ie grote rasters kan handelen)

**Comment by Jonasvsl** [comment]
Wat is rastercheck 9 'is de projectie compleet ?' Wat check je dan?
rastercheck 11: 'wat zijn logische waarden? geeft gebruiker die op? 
Wat is rastercheck 13 'komen alle raster overeen ?' precies? Gaat het dan om dat alle pixels exact op elkaar liggen? 
Schrijft de improve over het origineel heen? of wordt er een nieuw raster aangemaakt? 
Werkt het ook op postgis?
Als R6 limiterend werkt op de doorlooptijd is dit geen harde eis.

**Comment by renierkramer** [comment]
final checks are 18 checks:

RC does 18 checks:
1: Are all filenames of rasters within one setting_id unique? (3Di can handle this, but RC not).
2: Do the referenced rasters (in all v2_tables) exist on your machine?
3: Is the raster file extension .tif / .tiff?
4: Is the raster filename valid? (no special characters, no space, max one '.' and '/')
5: Is the raster single- (not multi-) band?
6: Is the raster nodata value -9999?
7: Does the raster have a projected coordinate system (unit: meters)?
8: Is the raster data type float 32?
9: Is the raster compressed? (compression=deflate)
10: Does the pixelsize have max three decimal places?
11: Are the pixels square?
12: Are there no extreme pixel values? (dem: -10kmMSL<x<10kmMSL, other rasters: 0<x<10k)
13: Is the cumulative number of pixels of all rasters per setting_id lower than 1.000.000.000?
14: Is the projection equal to the dem projection?
15: Is the pixel size equal to the dem pixel size?
16: Is the number of data/nodata pixels equal to the dem.
17: Is the number of rows-colums equal to the dem?
18: Are pixels correctly aligned (data and nodata locations) with the dem?

**Comment by RichardB9** [comment]
@renierkramer can this RFC be closed?
