### ISSUE TITLE
create installer

### ISSUE THREAD

**Issue by Jonasvsl** [nens/threedi-results-analysis#447]
Marco Duiker has made an installer available to use. The data can be found here:

I:\Data_Sources\work\J_vSchrojenstein\3Di\MI

@reinout has looked at it before and roughly understands how it works. 
Missing icons that are required for installation have been created by lirry and are available in the same directory.

**Comment by Jonasvsl** [comment]
questions:
tbc: Versioning in name
versioning in script possible?

**Comment by Jonasvsl** [comment]
@RichardB9 
Why is it assigned to me?

**Comment by Jonasvsl** [comment]
https://github.com/nens/ThreeDiCustomizations

**Comment by Jonasvsl** [comment]
open points:

1. License of '3Di Modeller Interface @Jonasvsl 
2. icons Lirry so they show up under windows

**Comment by RichardB9** [comment]
Closed in https://github.com/nens/ThreeDiToolbox/pull/472
