### ISSUE TITLE
Test and perhaps adjust plugin to work under new QGIS LTR

### ISSUE THREAD

**Issue by Jonasvsl** [nens/threedi-results-analysis#452]
Starting 21-02-2020 a new QGIS LTR is out. No mayor changes are expected, but we still need to test our plugin under this new version.

https://www.qgis.org/ca/site/getinvolved/development/roadmap.html#release-schedule

**Comment by RichardB9** [comment]
duplicate issue https://github.com/nens/ThreeDiToolbox/issues/482
