### ISSUE TITLE
bugje in QML

### ISSUE THREAD

**Issue by Jonasvsl** [nens/threedi-results-analysis#456]
De defaults in qml zijn voor de volgende features:
v2_impervious_surface:
v2_surface:

voor:
zoom_category: -1

-1 bestaat niet. beste is om deze weg te halen denk ik.

**Comment by RichardB9** [comment]
Willen we helemaal geen defaul value of willen we de -1 veranderen in een andere default?

**Comment by Jonasvsl** [comment]
Volgens mij willen we geen defailt value want -1 is gelijk aan niks toch?
En hij hoeft niet ingevuld te zijn voor 3Di bij mijn weten
