### ISSUE TITLE
terugmelding van Emiel over plugin

### ISSUE THREAD

**Issue by Jonasvsl** [nens/threedi-results-analysis#458]
Feedback Emiel:

1. Ik had weer problemen met de h5py installatie. Gelukkig had ik nog het mapje van h5py versie 2.10 ergens opgeslagen dus toen ik 2.9 hiermee vervangen had werkte het weer.

2. In de vorige versie was dit ook al het geval. De selectie van flowlines / nodes voor het maken van grafieken kan niet meer met behulp van de animated lagen, dan krijg je een python error (index out of bound). Je kan wel een v2_connection_node selecteren en een waterstand opvragen, maar dit is niet dezelfde waterstand als het onderliggende rekenpunt. Ik wil hier wel over nadenken wat een handige manier is om resultaten te selecteren, volgens mij kan hier veel op gebruiksvriendelijkheid worden gewonnen.

3. In de vorige versie was dit ook al het geval. Er is een v2_cross_section_location en een v2_cross_section_location_view. De view heeft ook de data van de v2_cross_section_definition eraan gekoppeld maar kan dit niet gewoon met behulp van een join in QGIS? Of is hiervoor een andere reden?

4. Het automatisch toevoegen van de sqlite connection is handig, maar als grootgebruiker van 3di modellen krijg ik wel snel een hele waslijst hier omdat hij ze de connection laat staan. Het lijkt mij fijn om een verbinding te hebben bijvoorbeeld genaamd '3Di model' welke bij het afsluiten van QGIS weer wordt verwijderd of bij het laden van een nieuw model wordt overschreven.

**Comment by Jonasvsl** [comment]
@RichardB9 1 en 2 graag oppakken. Nummer 3 en 4 ga ik nog even over in gesprek

**Comment by RichardB9** [comment]
Moved nr. 2 to a separate issue: #461 
If we want to pick up nr. 3 and 4 we should also create separate issues of them.

**Comment by RichardB9** [comment]
Nr. 1 kan ik niet reproduceren, Martijn ook niet. Ook is het vreemd dat Emiel versie 2.9 moest vervangen met (eigen) 2.10. Wij leveren nu juist een h5py 2.10.

**Comment by Jonasvsl** [comment]
Kasper heeft hetzelfde probleem. Ik denk dat het te maken heeft met osgeo installer

**Comment by Jonasvsl** [comment]
Ik kan het probleem ook niet reproduceren. Voorlopig geen prio

**Comment by leendertvanwolfswinkel** [comment]
Issue 3 no longer relevant, will be fixed in new model editing tool
Moved issue 4 to separate issue
