### ISSUE TITLE
Graph tool on node/line results from animation tool

### ISSUE THREAD

**Issue by RichardB9** [nens/threedi-results-analysis#461]
Using the graph tool on nodes/lines results created by the animation-tool leads into a runtime error:

```
Traceback (most recent call last):
  File "/home/nens/.local/share/QGIS/QGIS3/profiles/default/python/plugins/ThreeDiToolbox/tool_graph/graph_view.py", line 860, in add_objects
    self.h_graph_widget.add_objects(current_layer, selected_features)
  File "/home/nens/.local/share/QGIS/QGIS3/profiles/default/python/plugins/ThreeDiToolbox/tool_graph/graph_view.py", line 656, in add_objects
    "Active database (%s) doesn't look like an sqlite filename" % conn_info
RuntimeError: Active database () doesn't look like an sqlite filename
```

Steps to reproduce the bug:
1. Select a netcdf-result via the result-selector tool.
2. Activate the animation tool and set the time-slider to some timestep.
3. Activate the graph-tool.
4. Select a node-result/line-result from the layers added by the animation-tool
5. Use the graph-tool to display a graph.

**Comment by RichardB9** [comment]
@renierkramer @Jonasvsl was this possible before? Or is this a new feature?

**Comment by Jonasvsl** [comment]
To be honest I don't know. It might have been a 'lucky' feature.
@renierkramer do you know? For me it is acceptable to not have this option, but we shouldn't have this error message
