### ISSUE TITLE
load dem 

### ISSUE THREAD

**Issue by Jonasvsl** [nens/threedi-results-analysis#466]
When loading a 3Di model a user always has to manually load the dem.

For user friendliness we should add a button which loads all rasters belonging to a certain global settings id. 
We then also provide the styling for these rasters. 
Emiel has made an example in this plugin: 
https://github.com/threedi/beta-plugins/tree/master/threediresultstyler

**Comment by leendertvanwolfswinkel** [comment]
is part of new model loading & editing prototype
