### ISSUE TITLE
Result Selector Datasource(s)

### ISSUE THREAD

**Issue by RichardB9** [nens/threedi-results-analysis#468]
The result-selector tool is the basis for several other tools in the ThreediToolbox. It allows you to select a single model (sqlite file) and you can select multiple results files (netcdf files).

![image](https://user-images.githubusercontent.com/11858775/69426578-d9fac080-0d2d-11ea-8503-ccee79c4403f.png)

However, the use of multiple result files and how the other tools interact with multiple result-files is unclear. It seems that most (all?) tools operate on **one** result file. What is the use of adding multiple result files?
When you add multiple result-files, it is unclear on which result file the tools operate. Do they all operate on the same result-file? Is this the last loaded result-file or the first? What does the delete button do?

Throughout the code there is an `active_ts_datasource` (single entity) and `ts_datasources` (list of entities) (ts stands for timeseries). However, its use is very inconsistent. Sometimes the `active_ts_datasource` is used and sometimes the first entry in the `ts_datasources` is used. Furthermore the user is not informed in any way which is the `active_ts_datasource`.

I believe that these inconsistencies/uncertainties are a cause of many bugs/confusion for users and developers.

In this RFC I want to agree on how the result-selector should work with regards to the other tools and then make a plan to implement consistently in the ThreediToolbox.

**Comment by Jonasvsl** [comment]
Users perceive it as a strong point that they can load in multiple scenario's. So I would really like to have this feature. 
However it does make less sense to have this for the animation toolbar (unless make perhaps new group layers with results), I do think it is a really strong thing to have for graph tool and sideview tool.

**Comment by RichardB9** [comment]
Ah, that's a good use of multiple datasources! Is the graph-tool the only tool to make use of multiple datasources? 
Other tools don't seem to make use of multiple and here it's confusing which results are processed:
- Sideview tool
- Statistics tool
- Waterbalance tool
- Animation tool

**Comment by Jonasvsl** [comment]
The most logic implementation from a user perspective would be:
- add a legend to the graph tool so users know which line is which could be dotted lines versus normal lines
- include the different multiple datasources in the sideview tool (and also a legend)
for statistics, waterbalance, animation tool: let the user select one of the results (only if there are multiple results loaded)


my first thought (not a good one):
for the animation toolbar we can maybe make seperate group layers? or is that complex with regard to the time toolbar? I can image that users start to compare scenario's with different times then this wouldn't work. ok. I'll leave this last thought here as a reminder to myself

**Comment by RichardB9** [comment]
One idea I was thinking of is to add some extra display which shows the active result file. I made a quick label (also to help me debug):
![image](https://user-images.githubusercontent.com/11858775/69536249-ef662980-0f7d-11ea-85f6-2956f6087be9.png)

And once a user has select a result file:

![image](https://user-images.githubusercontent.com/11858775/69536283-fc831880-0f7d-11ea-9582-9df97b66ac4c.png)

Two result files, and now I can see which one is being used by the animation-tool:
![image](https://user-images.githubusercontent.com/11858775/69536695-c72afa80-0f7e-11ea-9c73-8b90cc7131b9.png)

Note that this is a quick and dirty mock to give some idea/inspiration.
I was thinking to make this a dropdown to be able to switch between all loaded result file.

**Comment by Jonasvsl** [comment]
A drop down sounds like a proper approach. How do you decide what name to put in the drop down? 
Or do we make the name editable in the load screen (see your last screenshot) so users can distinguish between the results? It might be confusing if they can choose between 'results_3Di' and 'results_3Di'. In our new API users give a scenario name, I think it would be best to start using that one
