### ISSUE TITLE
Robust check on NetCDF validity

### ISSUE THREAD

**Issue by RichardB9** [nens/threedi-results-analysis#471]
The ad-hoc way of detecting the netcdf version is unreliable: https://github.com/nens/ThreeDiToolbox/blob/ac28950614d41c88395663beeb2c69c5ee1abe06/tool_result_selection/result_selection_view.py#L497
This results in the user getting incorrect messages that their result-file is too old:
```
"The selected result data is too old and no longer "
"supported in this version of ThreediToolbox. Please "
"recalculate the results with a newer version of the "
"threedicore or use the ThreediToolbox plugin for QGIS 2",
```
For example, open the netcdf with some program. Now try to load in the netcdf with ThreediToolbox and our detection method will fail.

**Comment by Jonasvsl** [comment]
@RichardB9 
does this only happen when a user opens the netcdf with a different program than QGIS? or is it in all cases?

**Comment by RichardB9** [comment]
Likely in all cases, but I have not tested opening a result file with two instances of Qgis.

**Comment by Jonasvsl** [comment]
new and current API version?

**Comment by leendertvanwolfswinkel** [comment]
I think we need a robust validity check on the netcdf and if it is not valid, give a range of possible causes as feedback to the user, e.g.

"{path_to_file} is not a valid 3Di result dataset. The file may be incomplete or corrupt. If the result file is older than [year groundwater was introduced], recalculate the results with the current version of 3Di"

**Comment by leendertvanwolfswinkel** [comment]
Duplicate of #584

**Comment by arjanverkerk** [comment]
@benvanbasten-ns tackles checking the 3Di version for a result elsewhere. I propose to handle only the file integrity in this issue, how does that sound @leendertvanwolfswinkel?

**Comment by arjanverkerk** [comment]
It turns out that the HDF5 library already checks if the file is "complete" (not truncated) so by just opening the file with h5py we can already verify if it is not truncated.

**Comment by leendertvanwolfswinkel** [comment]
Ok, sounds good. In your implementation, what will the user see if they try to load an incomplete NetCDF?

**Comment by arjanverkerk** [comment]
Well, currently (in the refactor branch) it is "Results file cannot be opened.", but I sense in your question that this happens often enough to justify something along the lines of "The HDF5 library detected an incomplete file." and maybe even: "This could be caused by a copy or download error."?

**Comment by arjanverkerk** [comment]
Will do a secial kind of log message.

**Comment by leendertvanwolfswinkel** [comment]
My suggestion: "Results file {path} cannot be loaded, because it is incomplete. A common cause for this are problems during downloading or copying the file."

**Comment by leendertvanwolfswinkel** [comment]
I tried with this file:
[https://app.zenhub.com/files/55498704/4811e7e7-dc7c-4f50-8635-6a0d0c71d3c5/download](https://app.zenhub.com/files/55498704/4811e7e7-dc7c-4f50-8635-6a0d0c71d3c5/download)

The results manager shows a warning triangle, but no feedback message is shown:
![image.png](https://images.zenhubusercontent.com/62bedb7b667872a01ff3bdff/dc408b00-c92d-43e6-a496-7910f45b7688)

Please make sure the feedback message is shown to the user ("Results file {path} cannot be loaded, because it is incomplete. A common cause for this are problems during downloading or copying the file.")

**Comment by arjanverkerk** [comment]
There was a message in the logs, but now I replaced that with a messagebar message (in the main viewport)

**Comment by leendertvanwolfswinkel** [comment]
-[ ] In the message "3Di Model Validator: Unexpected file name for results file", please replace "3Di Model Validator" by "3Di Results Manager"

**Comment by arjanverkerk** [comment]
Allright.
