### ISSUE TITLE
Schematisation checker: check for line connections shorter than 0.05 m

### ISSUE THREAD

**Issue by Jonasvsl** [nens/threedi-results-analysis#483]
topdesk issue 2003 0084 

connections shorter than 0.05 m gives an issue. we need to check this for all line geometry connections (including views like pipe_view)

**Comment by RichardB9** [comment]
Do you mean the distance between the start- and end node of the following objects:
- Channel
- Pipe
- Culvert
- Weir
- Orifice
- Pumpstation

Or the length of the `LINESTRING` geometry in the following objects:
- GridRefinement
- ConnectionNode
- Channel
- Culvert
- Obstacle
- Levee

Note that the length between two connection nodes is a straight line while the `LINESTRING` does not have to be.

**Comment by Jonasvsl** [comment]
@martijn-siemerink can you please help out here? I think it is about the Linestring between connection nodes. Is that correct?

**Comment by martijn-siemerink** [comment]
Het om de afstand van de Linestring Geometrie indien aanwezig. Anders gaat het om de afstand tussen de connection nodes omdat deze anders de geometrie van een verbinding bepaald.
Voor deze objecten moet het gecontroleerd worden:
- Channel
- Pipe
- Culvert
- Weir
- Orifice
