### ISSUE TITLE
The schematisation checker gives users an inrcorrect 'Invalid timeseries' error for boundary conditions. 

### ISSUE THREAD

**Issue by Jonasvsl** [nens/threedi-results-analysis#486]
The schematisation checker gives users an 'Invalid timeseries' error for boundary conditions. This is weird as the boundary conditions look exactly the same. 

Is it possible that the check also looks at empty spaces and/or lines?

**Comment by RichardB9** [comment]
The description and the title of this issue don't seem to match. This description is the same as #485. @Jonasvsl can you update this description?

**Comment by RichardB9** [comment]
> Is it possible that the check also looks at empty spaces and/or lines?

Yes, the check is currently quite strict. 
No spaces at the end of a entry in a timeseries are allowed. For example the following timeseries is incorrect as the fourth entry contains a space at the end.
```
0,-0.5
59,-0.5
60,-0.5
61,-0.5 
9999,-0.5
```
Spaces are also **not** allow before an entry or between the comma separating the timestamp and value. Example space before:
```
 0,0.5 
```
Example space between:
```
0, 0.5 
```

Furthermore, the last entry must **not** end with a newline.
This is all done intentionally.

**Comment by Jonasvsl** [comment]
@martijn-siemerink 
there seems to be a difference in strictness for boundary conditions between the schematisation checker and what the calc core accepts. 
@RichardB9 can we give a clear message to the user where the space is found that is unacceptable? at the moment it is a bit puzzling for most users.

**Comment by martijn-siemerink** [comment]
Belangrijkste is volgens mij dat de next line correct is opgegeven. Die spaties maken volgens mij niet zo veel uit. Maar dat is er afhankelijk hoe python de database tabel parsed. De rekenkern verwacht space seperated values in zijn input bestand voor 1D boundaries en komma seperated values voor zijn 2D boundaries. Met name voor de 1D boundaries is het van belang dat er 1 spatie is volgens mij.

**Comment by Jonasvsl** [comment]
ah so the space is relevant because of the python code later on in the process.... 
@RichardB9 we should avoid that the checkers gives an error for similar looking time series that are both okay for the calc core. I suggest adding a message to the Error saying which line contains a space with a message like 'a space is found on line xxx of boundary condition xxx' this can cause problems in the calculation core, please remove the space

**Comment by leendertvanwolfswinkel** [comment]
Assuming this has been fixed since Klondike
