### ISSUE TITLE
ks in graphs

### ISSUE THREAD

**Issue by Jonasvsl** [nens/threedi-results-analysis#495]
I have seen in the lutra plugin https://github.com/nens/threedi-api-qgis-client 
that htey have solved the issue that we had with our graphs.

Somehow we always have ks instead of hours, days, weeks etc

Please check their plugin and use the same approach for our graphs.

**Comment by leendertvanwolfswinkel** [comment]
I still get time in ks...
![image](https://user-images.githubusercontent.com/26224299/169840216-5c8a7faa-2b96-4518-91b4-38a488d00784.png)

**Comment by ldebek** [comment]
@leendertvanwolfswinkel Which graph is it? I thought that it only applies to Water Balance graphs, where I've added dropdown menu with option to pick time units (seconds/minuutes/hours). If there are some other graphs that needs to be updated - could you please then list them? I'm not an experienced user of the Toolbox. :)

**Comment by leendertvanwolfswinkel** [comment]
Ok I see the ticket is not quite clear indeed. The main issue is with the Graph Tool, but it's good that you also took the water balance tool into account.

**Comment by leendertvanwolfswinkel** [comment]
It works, but I'm not really happy about how it switches from one time unit to another. I expect the time period to remain the same when I switch units. E.g.:

- Units is in seconds. I zoom in to a period starting at 300 s, ending at 3600 s.
- I switch units. I would like the graph to show me the same period (5 to 60 minutes), but instead it now shows me 300 to 3600 minutes.

**Comment by ldebek** [comment]
@leendertvanwolfswinkel That's quite tricky to implement, because each units change needs recalculation of time series to selected units. Current plot drawing architecture would require some deeper refactoring to implement tracking of plot scene range changes + time units recalculations. For now I've added zooming out to full data range extent after each units selection change as a compromise solution. Is that ok for you for a time beign?

**Comment by leendertvanwolfswinkel** [comment]
Good suggestion. I moved the request for keeping time range the same to #639. 

As discussed on slack, only remaining issue is that initially, the graph does not zoom to full extent
