### ISSUE TITLE
schematisation checker: Pumpstation.lower_stop_level should be higher than Manhole.bottom_level false error

### ISSUE THREAD

**Issue by Jonasvsl** [nens/threedi-results-analysis#503]
The schematisation checker gives this error:
Pumpstation.lower_stop_level should be higher than Manhole.bottom_level

for the model of papendrecht u0238_papendrecht-papendrecht_int_snel_integraal-14-2602caf5138245e3d
download here: https://3di.lizard.net/models/models/6888/

however stop levels are higher than bottom level
e.g. in manhole 1354 bottomlevel is -4.98 and stoplevel -4.7

**Comment by lisannewapstra** [comment]
New ticket by Emiel 2101 0179. This is confusing, please fix this.

**Comment by Jonasvsl** [comment]
@RichardB9 wasn;t this fixed already in a new version of the toolbox? or did I miss this one?

**Comment by RichardB9** [comment]
Now I'm confused as well. I see I made a change which is not yet released but I'm not sure if this is correct.

Is the following statement correct?
In a correct 3di model the following condition should hold: "Pumpstation.lower_stop_level > Manhole.bottom_level"

**Comment by Jonasvsl** [comment]
yes your statement is correct

**Comment by RichardB9** [comment]
Related: https://github.com/nens/threedi-modelchecker/issues/25 and where the bug was introduced

**Comment by RichardB9** [comment]
closed in https://github.com/nens/threedi-modelchecker/pull/34
