### ISSUE TITLE
create water depth maps locally

### ISSUE THREAD

**Issue by Jonasvsl** [nens/threedi-results-analysis#504]
Lizard backend team is going to provide a python script that can run standalone

We need to incorporate it in qgis in the processing framework using this tutorial:
https://www.qgistutorials.com/nl/docs/processing_python_scripts.html

**Comment by RichardB9** [comment]
I assume the standalone script is the library https://github.com/nens/threedidepth?

Why do we want to add this to the Processing-framework scripts?
Wouldn't it be more logical to place it under the 3Di tool commands: "Step 5: Post-process Results"
![image](https://user-images.githubusercontent.com/11858775/94272221-0df0d480-ff43-11ea-8644-bbda55651e82.png)


Or maybe integrate it into the Timeslider widget so users can easily select the requested timeframe once their results are loaded?
![image](https://user-images.githubusercontent.com/11858775/94272433-590ae780-ff43-11ea-89af-4ed8d631499a.png)

For example, add an additional button 'generate waterdepth image' next to the time-slider. This button then only becomes enabled/clickable once you loaded an sql-model and results.

**Comment by Jonasvsl** [comment]
That is true but I expect users would in some cases like to do a batch run for all time steps and then calculate the max waterdepth from that. The QGIS processing framework allows for use in models like this without a need to code:

![image](https://user-images.githubusercontent.com/1453159/94400704-d6b03c80-0169-11eb-8f9e-b7c0ed448507.png)

Is that also something we can achieve when we add the tool to step 5 - post-processing results?

I like your suggestion of integrating with the timeslider widget how much work is that?

**Comment by RichardB9** [comment]
Summary of discussion with @Jonasvsl :

The "Processing Toolbox" of qgis is more powerful than our custom command toolbox:
- It adds options for batch-processing
- Allows user to combine algorithms using the graphical modeller or the python console. 
- It automatically generates a user-interface based on the inputs and outputs of the algorithm. 

Furthermore, this is qgis default way of creating algorithm/scripts. Thus experienced qgis users will be familiar with the Toolbox and we will benefit from future developments from qgis in the Processing Toolbox.

Therefore we want to migrate our custom commands to the qgis Processing Toolbox, starting with this new command to create the waterdepth.
Other important commands which will need to be migrated are:
- raster-checker
- model-checker
- import sufhyd

The command 'control structures' is almost never used and does not need to be migrated.
The other commands:
- guess indicators
- create breach locations
- add connected points
- predict calc points

**Comment by Jonasvsl** [comment]
@RichardB9 To be complete: the control structures are not to be migrated but we will keep available in the toolbox

**Comment by RichardB9** [comment]
Closed in https://github.com/nens/ThreeDiToolbox/pull/506
