### ISSUE TITLE
Netcdf error with graph after not using the tool for some time

### ISSUE THREAD

**Issue by bastiaan-roos** [nens/threedi-results-analysis#51]
The graph tool works fine, but when the tool is open for some time without using, The following netcdf error shows when continue using the graph tool.

![hfjddakdfhkbgini](https://cloud.githubusercontent.com/assets/1068991/17248878/8b8378ca-559d-11e6-83cc-4b5405800576.png)

**Comment by jackieleng** [comment]
probably a network disk connection timeout
