### ISSUE TITLE
Interpolate function Laterals not implemented in API v3

### ISSUE THREAD

**Issue by lisannewapstra** [nens/threedi-results-analysis#510]
(not sure about the repo)

**Ticket by Arnold**
2010 0081 - 13-10-2020 Werkt de interpolate functie bij de Laterals in API v3?

**Analysis**
Lisanne asked in 3di Slack
Richard: ik zie dat de interpolatie bij laterals nog niet is aangesloten, deze werkt dus momenteel nog niet.

**Request**
Please implement this

**Comment by Jonasvsl** [comment]
Hi Lisanne,

It should be in the threedi-api repo. I understood from @RichardB9 that he already made a ticket. 

There is of course a sort of work around for users: they can densify the timeseries themself mimicking the interpolation of values. but keep in mind that the current max row limit is still 300.

**Comment by RichardB9** [comment]
Related issue: https://github.com/nens/threedi-api/issues/680
