### ISSUE TITLE
Turn on Laterals :  Error: {"point":["This field may not be null."]}

### ISSUE THREAD

**Issue by lisannewapstra** [nens/threedi-results-analysis#511]
Via Maud en Martine Topdesk 2011 0134 Qgis plugin

**Original Ticket Topdesk**
Het lukt mijn en Martine nog niet om de laterals aan te zetten van uit de 3Di toolbox. De error die we krijgen is: Error: {"point":["This field may not be null."]}

Is er iets wat wij misschien niet meegenomen hebben? Op zich hebben we de handleiding gevolgd van de 3di documentatie
En onze csv ziet er ook hetzelfde uit: "K:\M_vDelden\DW-model\laterals_simple_dw.csv"

**Response 3Di support**

Remo van Tilburg November 17, 2020 10:01 AM 
Ha Maud,

Ik heb naar je .csv gekeken en deze ziet er goed uit. Deze zou je nu moeten invullen in je v2_1d_lateral. Houd hiermee rekening mee dat de timeseries overal exact hetzelfde moet zijn. Dus als je boundary conditions hebt moeten deze hetzelfde format hebben als je laterals. Hoe zorgt je er nu voor dat je de .CSV in de v2_1d_lateral tabel krijgt?

Gr,
Remo

**Analysis 3Di support**
Remo

Ik heb met Maud hierover gesproken. Het heeft te maken met een bug in de modeler interface. Als je dus laterals inlaadt, gaat hij er automatisch van uit dat die coordinaten zijn die je opgeeft. Terwijl er ook de mogelijkheid moet zijn om de laterals te koppelen aan connection nodes. (deze ook doorzetten aan 3Di team).

@Jonasvsl

**Comment by Jonasvsl** [comment]
is gefixt
