### ISSUE TITLE
Schematisatiechecker - Rasternaam maximum 60 tekens

### ISSUE THREAD

**Issue by lisannewapstra** [nens/threedi-results-analysis#514]
**Topdesk 2009 0109 toevoegen check aan schematisatiechecker**

Ivar Lokhorst September 15, 2020 10:31 AM
Namens wie wil je een ticket aanmaken?
- Mezelf

Beschrijf hier je melding:
- Ik kwam er gisteren achter dat de naam van een raster maximaal 60 tekens mag zijn. Zou dit als check opgenomen kunnen worden in de schematisatiechecker?

**Comment by RichardB9** [comment]
Do you know which rasters? The table + column which have this limitation?

We might want to fix this in the calculation-core instead of adding it as a check.

**Comment by lisannewapstra** [comment]
I asked him, hopefully he remembers after 4 months.

**Comment by lisannewapstra** [comment]
He is not sure, but see his response below: 


Hoi Lisanne,

Fijn dat hier naar gekeken wordt, wel jammer dat de vraag om extra informatie pas 4(!) maanden na indienen van het ticket komt. Ik weet niet meer precies waar het om ging en heb ook geen zin om dat uit te zoeken. Ik denk dat het gaat om het totaal aantal karakters in het DEM veld (global_settings dem_file) danwel het aantal karakters in de naam van de DEM. Het verschil zit hem dus in de vraag of het stukje "rasters/" en ".tif" wordt meegenomen in de karakter telling. Ik gok dat dit voor alle raster velden geldt (dus ook friction_file, infiltration_file, interception_file, etc.).

Ik snap dat heel lange namen niet logisch zijn maar zie aan de andere kant zelf niet echt een reden om hier vanuit 3Di een limitatie op te zetten dus wat dat betreft zou een fix in de calculation core misschien logischer zijn.

**Comment by RichardB9** [comment]
@martijn-siemerink @nvolp Do you know about max raster-name length in the calculation-core?

**Comment by RichardB9** [comment]
The raster-names are prepended with the mercurial-repository-path. The total length can be 1024 characters but we do not know the lenght of the mercurial-repository therefore we can't check for this in the threedi-modelchecker .
