### ISSUE TITLE
Raster checker - errors op het initieel waterstandsraster 

### ISSUE THREAD

**Issue by lisannewapstra** [nens/threedi-results-analysis#515]
**Topdesk 2011 0194 Leendert - Rasters kloppen niet, maar raster checker ziet het niet**
(2 issues aangemaakt van 1 Topdesk ticket, andere is  516)

Leendert:
Ik heb een model door de raster checker gehaald, daar krijg ik alleen errors op het initieel waterstandsraster (heeft veel nodata waar DEM wel data heeft, mag wel van inpy maar niet van rasterchecker - dit is een known issue toch?).

- geen known issue

**Comment by RichardB9** [comment]
Can you provide the model where this issue happening?

**Comment by lisannewapstra** [comment]
Hi Richard,
I am afraid the revision is not available anymore on INPY.
I do have the logging of the checker and inpy (see attached)
[stadspark_2d_20201119_2116.log](https://github.com/nens/ThreeDiToolbox/files/5776847/stadspark_2d_20201119_2116.log)
[stadspark-2d_7_c89dabe09af7a84d3c534020f563a8bc3e34e046_20201123_192306.log](https://github.com/nens/ThreeDiToolbox/files/5776848/stadspark-2d_7_c89dabe09af7a84d3c534020f563a8bc3e34e046_20201123_192306.log)

. 

error, 01, 16, rasters/iniwaterstandco_stadspark_hybrid.tif count of data/nodata pixels differs from dem. dem: 88215072/42417642 data/nodata, while rasters/iniwaterstandco_stadspark_hybrid.tif: 9507869/121124845 data/nodata

**Comment by RichardB9** [comment]
I find this issue difficult to decide what to do. According to the documentation all the NO_DATA pixels must be the same in all rasters (see point 8, https://docs.3di.live/d_rasters.html?highlight=raster#raster-requirements). Therefore, I'm not sure if it's just coincidence that inpy accepts this model. I'm also not sure if the model is working properly or not.

According to this issue it seems that the NO_DATA pixels constrain is too strict, but I don't know what the more loose constraint would be.

@martijn-siemerink Is the NO_DATA pixels constraint too strict?

**Comment by martijn-siemerink** [comment]
Only for initial waterlevels the NODATA restraint is not necessary. It is common practice to only assign pixels where an user wants to set an initial waterlevel.
