### ISSUE TITLE
Raster checker - erroneous coordinates

### ISSUE THREAD

**Issue by lisannewapstra** [nens/threedi-results-analysis#516]
**Topdesk 2011 0194 Leendert - Rasters kloppen niet, maar raster checker ziet het niet**
(2 issues aangemaakt van 1 Topdesk ticket, andere is  515)

In inpy krijg ik echter deze melding, wat ook blijkt te kloppen als ik naar de betreffende pixels kijk in QGIS.

  ** ERROR  : File rasters/friction_stadspark.tif and DEM are not aligned, erroneous coordinates are:  235566.2500 578833.7500
  ** ERROR  : File rasters/friction_stadspark.tif and DEM are not aligned, erroneous coordinates are:  235589.7500 578775.7500

Met deze melding heb ik het probleem natuurlijk zo opgelost, maar blijkbaar mist de raster checker soms iets?

**Comment by RichardB9** [comment]
According to the description in the raster-checker this is already checked:
"18: Are pixels correctly aligned (data and nodata locations) with the dem?"

Can you provide an example where this is not working correctly?

**Comment by lisannewapstra** [comment]
You are right. This was found in the raster checker log:


error, 01, 18, rasters/iniwaterstandco_stadspark_hybrid.tif data and nodata are not aligned with the dem. Wrong pixels are not written too .shp as too many wrong pixels were found 

This is the same right?

**Comment by RichardB9** [comment]
Yes, that seems to be the right response!

I'm closing this issue.
