### ISSUE TITLE
Schematisatiechecker -  v2_1d_boundary_conditions timeseries errors

### ISSUE THREAD

**Issue by lisannewapstra** [nens/threedi-results-analysis#517]
**Topdesk 2008 0173 v2_1d_boundary_conditions timeseries errors in schematisation checker**
Wout Lexmond
August 31, 2020 02:50 PM

For whom do you want to create a ticket?
- For myself

Describe your issue:
- The schematisation checker gives very poor feedback whenever you make a mistake in entering the v2_1d_boundary_conditions timeseries.

I made two mistakes in the timeseries of the model Maastricht Oost:
1. I provided discharge bc timeseries with a timestep of 4 mins between 0 mins and 1560 mins, while my waterlevel bc timeseries only contained the first (0mins) and the last timestep (1560mins) and not all the intermediate steps.
2. I entered numbers with scientific formatting as values into the discharge timeseries (for example: 3.2E-5), which isn't supported.
The error message that is given by the schematisation checker in both cases is: "Invalid timeseries", which of course could be anything.

namely:
- Schematisation checker

If applicable: what error message did you receive?
- See v2_1d_boundary_conditions in csv  <--- [kan ik niet uploaden in Zenhub - Lisanne. hier de bovenste regels]

![image.png](https://images.zenhubusercontent.com/5ef5e8f83e5d5435204918ce/e3419a62-3e9e-44f5-8aef-20ed9ded2cb7)

**Comment by RichardB9** [comment]
Issue moved to [nens/threedi-modelchecker #44](https://github.com/nens/threedi-modelchecker/issues/44) via [**ZenHub**](https://www.zenhub.com/)
