### ISSUE TITLE
toolbox crashes qgis and other plugins upon activating in QGIS 3.16

### ISSUE THREAD

**Issue by Jonasvsl** [nens/threedi-results-analysis#518]
and this is an issue, since QGIS 3.16 is going to be the LTR

There is no logging because QGIS simply crashes.

What I did:

Clean install of QGIS 3.16
connect plugin manager to plugins.lizard.net/plugins.xml

tried installing 3Ditoolbox. at first got version 1.10
then did an update to 1.14.1 
then tried activating the plugin
upon click qgis just closes

**Comment by RichardB9** [comment]
Cannot be reproduced on Linux, this is likely a mismatch between the supplied h5py binaries for Windows and the HDF5/python version used in Qgis 3.16

**Comment by Jonasvsl** [comment]
ticket https://github.com/nens/ThreeDiToolbox/issues/523 related
