### ISSUE TITLE
Schematisatiechecker - empty geometry

### ISSUE THREAD

**Issue by lisannewapstra** [nens/threedi-results-analysis#520]
Please add the following check to the schematization checker:
Do all features have a geometry where a geometry is required?

Error on Inpy now:

    File "/home/buildout/eggs/Django-1.6.5-py2.7.egg/django/contrib/gis/geos/geometry.py", line 90, in __init__
      raise TypeError('Improper geometry input type: %s' % str(type(geo_input)))
  TypeError: Improper geometry input type: <type 'NoneType'>

**Comment by Jonasvsl** [comment]
What happens is that users either enter data in an attribute table without drawing a geometry, or they somehow delete only the geometry and not the data from the attribute table.


The following features require a geometry:

- v2_connection_nodes
- v2_cross_section_location
- v2_culvert
- v2_channel
- v2_obstacle
- v2_levee
- v2_grid_refinement
- v2_impervious_surface
- v2_surface
- v2_2d_boundary_conditions
- v2_2d_lateral

**Comment by RichardB9** [comment]
There is already a check which validates that the geometry in the table is valid and that the geometry is the expected geometry type. Some of these geometries can be null, this is done according to the schema created by Renier. 

Can you tell me in which of these tables the geometry cannot be null?

**Comment by lisannewapstra** [comment]
Hi Richard. 
My impression is that in all tables presented by Jonas, there can not be any feauture without a geometry.
Maybe that is an incorrect assumption then, but I think Jonas can better answer that.

**Comment by Jonasvsl** [comment]
@RichardB9 in all of them the geometry cannot be NULL I think. What is the list that Renier used? 
It makes me also wonder whether the check in the schematisation checker may not be working properly. Is that possible?

**Comment by RichardB9** [comment]
Ok, I will configure these fields so that they cannot be null.
I don't think the geometry and geometry-type checks are not working properly, but if you can give me a counter-example (sqlite) I will have a look.

**Comment by Jonasvsl** [comment]
@lisannewapstra can you provide this?
would be interesting to check

**Comment by RichardB9** [comment]
For reference, here are some tests which ensure the Geometry and GeometryType checks are valid: https://github.com/nens/threedi-modelchecker/blob/cb8c1117f0291c2266a34f5e93955cb5a203607e/tests/test_checks_base.py#L225

**Comment by lisannewapstra** [comment]
Hi, I have found an sqlite with that error:
v0217_lange_weeren - lange_weeren_1d2d_ghg - #34 
I place the sqlite in this folder: F:\Projecten intern (2020)\ServiceDesk\Sqlite_error_geometry
