### ISSUE TITLE
schematisatie checker --> check for unwanted  0 values in v2_numerical table

### ISSUE THREAD

**Issue by Jonasvsl** [nens/threedi-results-analysis#521]
When people use the dutch version of QGIS the values in the following fields in the v2_numerical table are set to 0. This can cause models to crash on start or never finish a time step:

The values in the following columns should not be 0:
convergence_eps
convergence_cg
general_numerical_threshold 
flow_direction_threshold

**Comment by RichardB9** [comment]
Are my following assumptions correct about these fields:
1. This field can still be NULL
2. When this field is not NULL, it must be **larger** than 0

**Comment by Jonasvsl** [comment]
yes assumption is correct
