### ISSUE TITLE
h5py build issue for LTR  QGIS 3.10.12

### ISSUE THREAD

**Issue by nvolp** [nens/threedi-results-analysis#523]
In the release of LTR  QGIS 3.10.12, they seem to have updated the h5py library. Our custom made build does not work anymore.

**Comment by RichardB9** [comment]
The following hdf5 version are supplied in qgis:

Qgis version | HDF5 version
------------ | -------------
3.4.8 | 1.10.4
3.10.2-2 | 1.10.4
3.10.8 | 1.10.4
3.10.10 | 1.10.4
3.10.13 | 1.10.5

The h5py version we supply as external dependency is build against HDF 1.10.4. 
The h5py version on pypi (h5py==2.10.0) is build against HDF 1.10.5.

As soon as you import the h5py package in Qgis and the package isn't build against the HDF5 version supplied by Qgis, Qgis will crash.

I can get the hdf5 version supplied by Qgis but I'm not sure how I can get the h5py version without first importing it. Without this knowledge it will be difficult (or impossible?) to detect if we need to upgrade the h5py package or not.
