### ISSUE TITLE
Schematisation checker: 2 projections

### ISSUE THREAD

**Issue by lisannewapstra** [nens/threedi-results-analysis#525]
2101 0057 Wayne 8-1

Wayne used ESPG 28992 (Netherlands) in his global settings on a model in Taiwan
https://api.3di.live/v3.0/threedimodels/14807/

The schematisation checker did not give an error.
The check should be if the raster ESPG and global settings are the same. 

@Jonasvsl

**Comment by RichardB9** [comment]
Issue moved to [nens/threedi-modelchecker #43](https://github.com/nens/threedi-modelchecker/issues/43) via [**ZenHub**](https://www.zenhub.com/)
