### ISSUE TITLE
adjustments to waterdepth script in processing toolbox

### ISSUE THREAD

**Issue by Jonasvsl** [nens/threedi-results-analysis#531]
In the drop down menu, the user can select quite a few options. The following ones need to be removed:
![image](https://user-images.githubusercontent.com/1453159/105873149-776d1680-5ffb-11eb-9b68-f8aff66ddad0.png)

lineair interpolated water depth
lineair interpolated water level

Water depth, rename to: non-interpolated water depth
Water level, rename to: non-interpolated water level

lizard interpolated water depth rename to interpolated water depth
lizard interpolated water level rename to interpolated water level

please make the 'interpolated water depth' the default option that is active when users open the tool

Also: when selecting a:
raster
result
or gridadmin file qgis defaults to defaiult location for all qgis files. is there a way to continue from the last used directory? it is highly confusing for users the way it works now. 

Nice to have:
When selecting a timestep in the simulation and creating a raster with waterdepth there is no default name suggested. I feel we have to help our users by suggesting filenames with at least either the timestep in it. Is that something that can be done?

For comparison: this is how lizard exports their rasters:
noordpolder_testwaterdepth_calculations_jonas-water-depth-timeseries_20210126T155501Z.tif

**Comment by RichardB9** [comment]
> Also: when selecting a:
> raster
> result
> or gridadmin file qgis defaults to defaiult location for all qgis files. is there a way to continue from the last used directory? it is highly confusing for users the way it works now.

The behavior seems a bit strange. On Linux with Qgis 3.10.14 this is already the default behavior. However, on Windows this isn't for the "gridadmin.h5" and "results_3di.nc". But the "DEM" does remember the last selected folder. I'm still looking into it but so far I can't see an easy way to set/fix the default-folder.

**Comment by RichardB9** [comment]
> Nice to have:
When selecting a timestep in the simulation and creating a raster with waterdepth there is no default name suggested. I feel we have to help our users by suggesting filenames with at least either the timestep in it. Is that something that can be done?

I tried several things but I don't know how this can be done.
