### ISSUE TITLE
lizard connector python package is abandoned per feb 17

### ISSUE THREAD

**Issue by Jonasvsl** [nens/threedi-results-analysis#532]
From internal email of Joeri:

> Op 17 februari gaan we afscheid nemen van Lizard API v2. Deze versie is sterk verouderd. De laatste gebruikers zijn nu over op de nieuwere versies van de Lizard API.
> Het is nog belangrijk om te vermelden dat de python library Lizard Connector, die hier en daar nog in oud cursusmateriaal terug te vinden is, nog gebruik maakt van API v2. Deze library gaan we niet updaten en zal dus niet meer werken. De reden hiervoor is dat we willen dat gebruikers direct gebruik maken van onze API ipv via deze connector. 
> Mocht je hier nog vragen over hebben, neem dan contact op met de servicedesk.

Slack conversation:

> > Daan van Ingen  3:44 PM
> hee Jonas, FYI: het bericht van Joeri klopt niet helemaal, de lizard-connector gebruikt per default v3, maar het is mogelijk om v2 te gebruiken. Ik heb een maand geleden een deprecation warning toegevoegd in de connector als iemand v2 gebruikt :slightly_smiling_face:

> Jonas van Schrojenstein  4:44 PM
> https://github.com/nens/ThreeDiToolbox/search?q=connector
> 4:44
> we gebruiken lizard connector versie 0.6
> 4:45
> @Daan van Ingen dan zitten we goed denk ik als standaard v3 wordt gebruikt toch? (edited) 
> 
> Daan van Ingen  4:49 PM
> in 0.6 wordt alleen v2 gebruikt zo te zien
> 4:50
> laatste versie is nu 0.7.3

I guess this means we have to update the lizard connector to version 0.7.3 In the toolbox it is pinned to 0.6. 

Not sure if we can simply pin it to a higher version or that this remark about abandoning python code means we have to simply abandon the feature and incorporate the downloading in the api qgis client by lutra

Please advise

**Comment by RichardB9** [comment]
I was able to update the lizard-connector to 0.7.3 without too much effort this morning. It seems to be working fine now.

However, the current implementation of downloading lizard results is limited and not very user-friendly. A rewrite of this tool would be nice (maybe as a processing algorithm?). Its code is currently also intertwined in the result-selection-tool, which adds unnecessary complexity to both tools.

**Comment by Jonasvsl** [comment]
I think we should separate lizard interaction in a different plugin. that would make it way more maintainable. 

I understand now that Lizard servers have been logging the use of API v2, apparently this part of the plugin is barely ever, if not never used

@RichardB9 
My proposal is to simply implement 0.7.3 and make a seperate ticket in which we discuss how to better solve this

**Comment by daan** [comment]
fyi @daan is not part of your projectOn Jan 29, 2021, at 11:19, Jonasvsl <notifications@github.com> wrote:I think we should separate lizard interaction in a different plugin. that would make it way more maintainable.I understand now that Lizard servers have been logging the use of API v2, apparently this part of the plugin is barely ever, if not never used@RichardB9
My proposal is to simply implement 0.7.3 and make a seperate ticket in which we discuss how to better solve this—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.
