### ISSUE TITLE
toolbox latest version for users within the plugins panel is 1.10 should be 1.15

### ISSUE THREAD

**Issue by Jonasvsl** [nens/threedi-results-analysis#541]
![image](https://user-images.githubusercontent.com/1453159/109141414-00dc4980-775e-11eb-8b49-ca8b8d42a98a.png)

**Comment by Jonasvsl** [comment]
a similar issue occurs for the qgis threedi api client.

When googling I found this handy site with an explainer:
https://reinout.vanrees.org/weblog/2016/08/29/qgis-plugin-repo.html

It might be that something has changed in how qgis handles these plugins. But I can't find this in their documentation.

If not fixable an acceptable work around (if this works) would be to move the previous versions of the plugins and only leave the latest version available on https://plugins.lizard.net/ and the archived ones on a different url. Just in case a user needs them for whatever reason

**Comment by reinout** [comment]
The same happens with the "3Di API client": `2.0.2` is the latest version according to qgis, but a `2.0.2` is available.

It looks like qgis picks the last matching one in the `plugins.xml` and that it disregards the actual version numbers.
=> I'll have to adjust the `plugins.xml`-generation.

**Comment by Jonasvsl** [comment]
I think it is a typo in the last comment you meant 2.4.0, right?

**Comment by reinout** [comment]
Yes, typo. (Well, 2.2.0 was the first newer one I saw, but anyhow, I can reproduce it :-) )

See https://github.com/nens/artifact-handler/pull/11

**Comment by Jonasvsl** [comment]
Oh Nice! That means I can sentence a bit it of a different message to our users Tuesday (I wanted to include a bug message but this might be more of a bug fix message instead)

**Comment by reinout** [comment]
Tadaah:

![Screenshot 2021-03-18 at 17 41 24](https://user-images.githubusercontent.com/121433/111663568-3cc07700-8811-11eb-86c7-9721bcbca0ad.png)

**Comment by reinout** [comment]
3di api client heeft nu ook de juiste versie.
