### ISSUE TITLE
Logging error when using GridH5ResultAdmin class

### ISSUE THREAD

**Issue by BlueUmbrella51** [nens/threedi-results-analysis#556]
Hi there, 

I've been working on a plugin for HHNK and I am trying to make sure it is compatible with the 3diToolbox. However, it uses the GridH5ResultAdmin object to load results and I am beginning to suspect there is an issues with its implementation in the ```3diToolbox``` plugin. I'm just posting this here so that you can verify if you have the time! (FYI: it seems to work fine if I just import the ```threedigrid``` package outside of the 3diToolbox)

The issue: (```threedigrid version 1.0.24, h5py version 2.10.0```, clean ```OSGeo4W``` installation with just the 3diToolbox installed)
```
from threedigrid.admin.gridresultadmin import GridH5ResultAdmin

h5_path = [some_path_to_h5_file]
nc_path = [some_path_to_nc_file]

res = GridH5ResultAdmin(h5_path, nc_path)
```

Running this code from the Python console in QGIS (3.16.1) gives the following error:

[error_log.txt](https://github.com/nens/ThreeDiToolbox/files/6480731/error_log.txt)

I have tried suppressing the error to see if that was the only issue by adding this line:

```threedigrid.admin.gridresultadmin.logging.disable()```

This gave me an error saying the results object (```res = GridH5ResultAdmin```) ```res.lines``` does not have a ```line_geometries``` attribute. (I checked by printing dir(res.lines))

This seemed wrong to me, so I created a clean python 3.7 environment and pip installed ```threedigrid==1.0.24``` and ```h5py==2.10.0```. Then I ran the same code as pasted above, and from printing the attributes of lines, I can see that it doen have the ```line_geometries``` attribute (it does not when printing the attributes in QGIS).

We have (not so thoroughly but still) checked this behaviour with versions 1.0.6 and 1.1.1 of threedigrid too.

I was wondering if you could verify this behaviour or you know of something else that might be causing it. If you have any questions or something is unclear, let me know!

Best,

Laure

**Comment by leendertvanwolfswinkel** [comment]
This is not an issue for the 3Di Toolbox, but for https://github.com/nens/threedigrid
