### ISSUE TITLE
Graph Tool dysfunctional on second screen

### ISSUE THREAD

**Issue by leendertvanwolfswinkel** [nens/threedi-results-analysis#563]
In Windows, if the display zoom settings of the second screen are > 100%, the graph is not rendered correctly

**Comment by leendertvanwolfswinkel** [comment]
Same cause as #590

**Comment by leendertvanwolfswinkel** [comment]
Apparently, there more is going on here. If I set the scale / zoom to 125%, the graph is ok. However, if in Windows Settings > Display Settings I choose the option 'Extend these displays', the graph area is not rendered correctly (y-axis is shifted upwards):
![image](https://user-images.githubusercontent.com/26224299/170208769-0bf6baf2-6374-4d9f-8593-0506e0ceec89.png)

![image](https://user-images.githubusercontent.com/26224299/170208620-60af283e-875d-493c-ab41-4c724108afcf.png)

If I set it to "Duplicate these displays", the graph is rendered fine:
![image](https://user-images.githubusercontent.com/26224299/170209354-a358d8d7-cfa9-44c2-b89c-0706f3950892.png)

**Comment by ldebek** [comment]
@leendertvanwolfswinkel I checked that, but I can't reproduce this issue anymore - no matter which configuration for a screen I pick (duplicate or extend).

**Comment by leendertvanwolfswinkel** [comment]
I also have issues reproducing it. Sometimes I can reproduce it, sometimes I can't. Closing this issue now, otherwise we'll risk spending to much time haunting a ghost
