### ISSUE TITLE
Include dependencies

### ISSUE THREAD

**Issue by leendertvanwolfswinkel** [nens/threedi-results-analysis#564]
Currently, dependencies are downloaded after installing the plugin. This has several disadvantages, i.e. system administrators may not allow communication with PyPI. If possible, the dependencies should be part of the plugin.

**Comment by leendertvanwolfswinkel** [comment]
@reinout probably has a clearer idea about why this what set up the way it is

**Comment by reinout** [comment]
The download issue should have been fixed quite a while ago. We collect all our dependencies and bundle them with the zipfile. It might be that, when **developing** locally, you don't yet have those bundled packages in the `external_dependencies/` folder, so in that case, pip has to download them.

Pip itself is called by dependencies.py with `--no-index`, which means "don't talk to pypi unless absolutely necessary".
Also with a `--find-links external_dependencies/` option, which means "first try to find everything in our directory with all the downloaded wheels".
See https://github.com/nens/ThreeDiToolbox/blob/master/dependencies.py#L304-L314

So... it shouldn't really be happening. Unless it is a local dev environment where the Makefile isn't used (which might be so on windows). And where, thus, dependencies might not have been downloaded. On linux, the docker/makefile setup ensures the needed wheels are downloaded, so perhaps windows needs a bit of attention.

I guess that the behaviour goes away when the wheels from a recent .zip are copied into the external_dependencies folder.
