### ISSUE TITLE
Generate water depth outputs for multiple timesteps

### ISSUE THREAD

**Issue by leendertvanwolfswinkel** [nens/threedi-results-analysis#565]
The water depth/water level processing tool has already been extended with this functionality (ac95ad8), but it does not work correctly yet.

It may be easier (code but also for the user) to have two separate processing tools (1 for single timestep, another one for multiple timesteps (output as set of rasters or netcdf))

**Comment by ldebek** [comment]
@leendertvanwolfswinkel Could you attach testing model (with DEM) to check the alghorithm. And also would it be possible to add details about why do you think that tool is not working correctly?

**Comment by leendertvanwolfswinkel** [comment]
Test data (w/ DEM): https://drive.google.com/drive/folders/16tLQEmPwQEzghEvUuZiR8_AhCTiFLApT?usp=sharing

Why it is not working correctly: depending on the settings, you should be able to generate three different types of output:

1. One tiff for a single timestep
2. A series of tiffs for a range of timesteps
3. A netcdf for a range of timesteps

(1) works fine. (2) generates only one tiff, no matter how large a time range you choose. (3) also works, but the output file has a .tif extension instead of .nc and is not interpreted by QGIS as a Mesh but as a tif. If you manually change the extension to .nc and load it as mesh, it works fine.

**Comment by leendertvanwolfswinkel** [comment]
As discussed just now, there is also a small UI issue, probably related to the SizePolicy of the end timestep slider widget. Please look into this also

**Comment by leendertvanwolfswinkel** [comment]
When multiple timesteps are requested, threedidepth produces a multiband tif, where each timestep is stored in a separate band. This is probably not the most easy to understand format for most users. However, I propose that we stick with this for the upcoming release and put the 'folder of separate tif files' output on the wishlist. Agree @Jonasvsl?

**Comment by Jonasvsl** [comment]
I thought we have netcdf as an output? The multiband tif is new to me

**Comment by leendertvanwolfswinkel** [comment]
Possible outputs of the Processing tool would now become:
- 1 Singleband Tif for 1 timestep
- 1 Multiband tif for multiple timesteps
- 1 Netcdf for multiple timesteps

That would be sufficient for this release right?

**Comment by Jonasvsl** [comment]
yes more than enough
the multiband is for qgis animations?

**Comment by ldebek** [comment]
PR ready for the review and testing: https://github.com/nens/ThreeDiToolbox/pull/579

**Comment by leendertvanwolfswinkel** [comment]
Exporting multiple timesteps to multiband tiff works well. But if I enable the 'export to netcdf' option, QGIS crashes after the algorithm is finished.

Please fix this if it is a simple bug. If it helps, you could also not load the netcdf to the map canvas but just let the user know it is finished and where it can be found. If it is too complex to fix, please let me know

**Comment by ldebek** [comment]
Can't reproduce it on QGIS 3.16.8. It seems that it might be hardware limitation, because example NetCDF file contains over 5 million faces and needs spatial indexes creation on first load which is time and memory consuming. Anyway QGIS shouldn't just crash, so @leendertvanwolfswinkel please follow those steps:
1. Try to load mesh using latest QGIS LTR version.
2. If crash still occur then please attach QGIS crash report, so we can debug it.

**Comment by leendertvanwolfswinkel** [comment]
@ldebek I installed QGIS 3.16.8, but am unable to install 3Di Toolbox ([ThreeDiToolbox-master.zip](https://docs.3di.live/threeditoolbox-dev/ThreeDiToolbox-master.zip)                          15-Jul-2021 13:59            39953359)

I created a new empty user profile before installing from zip and received the error below

I also tried this with the current production version (1.19), and run into the same issue. Made a separate ticket for it (#584 )

```
Traceback (most recent call last):
  File "C:\PROGRA~1/QGIS31~1.8/apps/qgis-ltr/./python\qgis\utils.py", line 312, in loadPlugin
    __import__(packageName)
  File "C:\PROGRA~1/QGIS31~1.8/apps/qgis-ltr/./python\qgis\utils.py", line 793, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\Users/leendert.vanwolfswin/AppData/Roaming/QGIS/QGIS3\profiles\3Di Toolbox 1.20/python/plugins\ThreeDiToolbox\__init__.py", line 26, in 
    dependencies.ensure_everything_installed()
  File "C:\Users/leendert.vanwolfswin/AppData/Roaming/QGIS/QGIS3\profiles\3Di Toolbox 1.20/python/plugins\ThreeDiToolbox\dependencies.py", line 85, in ensure_everything_installed
    _ensure_h5py_installed()
  File "C:\Users/leendert.vanwolfswin/AppData/Roaming/QGIS/QGIS3\profiles\3Di Toolbox 1.20/python/plugins\ThreeDiToolbox\dependencies.py", line 125, in _ensure_h5py_installed
    hdf5_version = _get_hdf5_version()
  File "C:\Users/leendert.vanwolfswin/AppData/Roaming/QGIS/QGIS3\profiles\3Di Toolbox 1.20/python/plugins\ThreeDiToolbox\dependencies.py", line 375, in _get_hdf5_version
    process = subprocess.Popen(
  File "C:\PROGRA~1\QGIS31~1.8\apps\Python39\lib\subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\PROGRA~1\QGIS31~1.8\apps\Python39\lib\subprocess.py", line 1420, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified
```

**Comment by leendertvanwolfswinkel** [comment]
@ldebek I had a meeting with Peter; conclusion was that we first need to narrow down in which cases the crash occurs and that we need logging, for which I should install the 'debugging symbols' through the OSGeo4W installer. I have not been able to do this before my holiday and my assessment is that this issue isn't going to go away with a simple adjustment. 

Therefore I propose that we leave out the 'export as netcdf' option for now and release it like that.

**Comment by Jonasvsl** [comment]
Isn’t it a better solution for now to mark the netcdf export as experimental by addjng the word experimental to the export option?

That would give us the option to test it better and also it is clear for users that it might not work

**Comment by Patrick-Nijman** [comment]
![image](https://user-images.githubusercontent.com/86961942/131324117-934f6e5d-7cf6-4a33-bbc4-4bd9d0613124.png)

@ldebek Please add (Experimental!) next to the highlighted part.

Thanks!
