### ISSUE TITLE
SideView & Statistics tool: Feedback to user when manhole surface level is not filled in

### ISSUE THREAD

**Issue by leendertvanwolfswinkel** [nens/threedi-results-analysis#570]
the surface_level in the table v2_manhole is not a required field (you can run a simulation without filling it in). However, if you want to draw a sideview in a model that has some surface levels not filled in, it will give an error (difficult to understand for most users what it means).

Solution: give a clear error message, stating which manhole lack a surface level and instructing the user to fill them in and start the tool again.

**Comment by leendertvanwolfswinkel** [comment]
Same problem exists for the Statistics tool

**Comment by leendertvanwolfswinkel** [comment]
SideView tool now works as required for missing surface_level values

The Statistics tool now gives no results at all for manholes if one manhole has no surface level (tested on the Tuindorp dataset)

**Comment by leendertvanwolfswinkel** [comment]
I still get the same behaviour when running the Statistics tool on a sqlite in which one `v2_manhole `row has `surface_level` `NULL`. All the result layers for manholes use the same data source (`manhole_stats_view` in gridadmin.sqlite), which is a join between `manhole_stats` and `nodes`. If I set one surface level to NULL, the `manhole_stats` is not filled at all, so that's why the view is also empty.

BTW I noticed that when loading the results_3di.nc, a huge number of critical errors are raised (not shown except for the message log). See this file: [message.log](https://github.com/nens/ThreeDiToolbox/files/8808055/message.log) Not sure if this is related?

**Comment by leendertvanwolfswinkel** [comment]
I looked into it a little bit and the errors in the log are not super relevant and not related to this issue. I created a PR to fix it (#637) anyway

**Comment by leendertvanwolfswinkel** [comment]
Turns out I had been testing with the wrong version... to be continued

**Comment by leendertvanwolfswinkel** [comment]
It works, I get a warning popup message. But I still also get a Python error. Can you catch that error?

```
Er is een fout opgetreden bij het uitvoeren van Python code: 

IndexError: index 0 is out of bounds for axis 0 with size 0 
Traceback (most recent call last):
  File "C:\Users/leendert.vanwolfswin/AppData/Roaming/QGIS/QGIS3\profiles\test 3Di Toolbox 20220523/python/plugins\ThreeDiToolbox\tool_statistics\tools\statistics.py", line 172, in run
    self.get_manhole_attributes_and_statistics()
  File "C:\Users/leendert.vanwolfswin/AppData/Roaming/QGIS/QGIS3\profiles\test 3Di Toolbox 20220523/python/plugins\ThreeDiToolbox\tool_statistics\tools\statistics.py", line 343, in get_manhole_attributes_and_statistics
    ri = int(np.where(manhole_idx == idx)[0][0])
IndexError: index 0 is out of bounds for axis 0 with size 0


Python versie: 3.9.5 (tags/v3.9.5:0a7dcbd, May  3 2021, 17:27:52) [MSC v.1928 64 bit (AMD64)] 
QGIS versie: 3.22.3-Białowieża Białowieża, 1628765ec7 

Python pad:
C:/PROGRA~1/QGIS32~1.3/apps/qgis/./python
C:/Users/leendert.vanwolfswin/AppData/Roaming/QGIS/QGIS3\profiles\test 3Di Toolbox 20220523/python
C:/Users/leendert.vanwolfswin/AppData/Roaming/QGIS/QGIS3\profiles\test 3Di Toolbox 20220523/python/plugins
C:/PROGRA~1/QGIS32~1.3/apps/qgis/./python/plugins
C:\Program Files\QGIS 3.22.3\bin\python39.zip
C:\PROGRA~1\QGIS32~1.3\apps\Python39\DLLs
C:\PROGRA~1\QGIS32~1.3\apps\Python39\lib
C:\Program Files\QGIS 3.22.3\bin
C:\PROGRA~1\QGIS32~1.3\apps\Python39
C:\PROGRA~1\QGIS32~1.3\apps\Python39\lib\site-packages
C:\PROGRA~1\QGIS32~1.3\apps\Python39\lib\site-packages\GDAL-3.4.1-py3.9-win-amd64.egg
C:\PROGRA~1\QGIS32~1.3\apps\Python39\lib\site-packages\win32
C:\PROGRA~1\QGIS32~1.3\apps\Python39\lib\site-packages\win32\lib
C:\PROGRA~1\QGIS32~1.3\apps\Python39\lib\site-packages\Pythonwin
```

**Comment by ldebek** [comment]
@leendertvanwolfswinkel Which schematisation gives you such error?

**Comment by leendertvanwolfswinkel** [comment]
[tuindorp_with_missing_surface_level.zip](https://github.com/nens/ThreeDiToolbox/files/8813059/tuindorp_with_missing_surface_level.zip)

**Comment by leendertvanwolfswinkel** [comment]
Error seems to be dataset-related, moving it to #638 and closing this one
