### ISSUE TITLE
Raster solver/fixer

### ISSUE THREAD

**Issue by leendertvanwolfswinkel** [nens/threedi-results-analysis#574]
***Introduction***
3Di Schematisations may include rasters. If any rasters are part of the schematisation, this will at least be a DEM and possibly other rasters as well. These rasters have to conform to a list of requirements. Some of these requirements apply to individual rasters (e.g. data type = Float32). Other requirements apply to the combination of the rasters with one another (all should have the same resolution). In the latter case, the DEM will always be regarded as the 'standard' to compare the others to (e.g. if the resolution of the friction raster is different than of the DEM, the friction raster should be corrected).

If the set of rasters does not meet all requirements, it may take quite a bit of skill and time from modellers to fix this. This ticket outlines a tool that does those fixes for the user where possible.

NB Please do not use `rasterio`; will be a nightmare to have as a dependency. Preferably a gdal-only implementation, exposed to the user via Processing Algorithms in QGIS.

*Rasters*
For reference: a list of possible rasters in 3Di
("dem_file", "Digital elevation model [m MSL]"),
("frict_coef_file", "Friction coefficient [-]"),
("initial_groundwater_level_file", "Initial groundwater level [m MSL]"),
("initial_waterlevel_file", "Initial water level [m MSL]"),
("interception_file", "Interception [m]"),
("infiltration_rate_file", "Infiltration rate [mm/d]"),
("max_infiltration_capacity_file", "Max infiltration capacity [m]"),
("equilibrium_infiltration_rate_file", "Equilibrium infiltration rate [mm/d]"),
("groundwater_hydro_connectivity_file", "Hydraulic conductivity [m/day]"),
("groundwater_impervious_layer_level_file", "Impervious layer level [m MSL]"),
("infiltration_decay_period_file", "Infiltration decay period [d]"),
("initial_infiltration_rate_file", "Initial infiltration rate [mm/d]"),
("leakage_file", "Leakage [mm/d]"),
("phreatic_storage_capacity_file", "Phreatic storage capacity [-]"),
("hydraulic_conductivity_file", "Hydraulic conductivity [m/d]"),
("porosity_file", "Porosity [-]"),

***Features*** 
What should the raster fixer be able to fix
*Single raster*
- [ ] #686 :
- Assign CRS of DEM if raster has no CRS
- Convert raster data type to float 32
- Nodata value: Any other nodatavalue than -9999 should be converted to -9999. Give the user the option to also change the pixel nodata values (opt-out, default is Yes)
- Use compress=deflate as compression method
- Round pixel size to max three decimal places

The following fixes have more impact on the data itself - also these problems are less common (lower priority)
- Make pixels square (ask users if they want to use width or height for this)
- Set extreme values to a user defined value (normal values are: DEM: -10kmMSL<x<10kmMSL, other rasters: 0<x<10k)

*Relative to the DEM*
These fixes are interrelated (i.e. first make pixel size the same before clipping to DEM extent), so they should be implemented as different processing algorithms:
- [x] #689
- [x] #687
- [x] #688
- [x] #690
- [x] #691

**Comment by leendertvanwolfswinkel** [comment]
Processing tool to fix the issues in 3Di model rasters.

Raster checker does 18 checks:
1: Are all filenames of rasters within one setting_id unique? (3Di can handle this, but RC not).


2: Do the referenced rasters (in all v2_tables) exist on your machine?


3: Is the raster file extension .tif / .tiff?


4: Is the raster filename valid? (no special characters, no space, max one '.' and '/')
`-- In theorie mag hier nu gewoon een padverwijzing instaan (met meerdere slashes)`


5: Is the raster single- (not multi-) band?


6: Is the raster nodata value -9999?


7: Does the raster have a projected coordinate system (unit: meters)
Yep belangrijk


8: Is the raster data type float 32
`-- Niet noodzakelijk. Wel wenselijk idd!`


9: Is the raster compressed? (compression=deflate)
`-- Niet noodzakelijk wel wenselijk`


10: Does the pixelsize have max three decimal places?
`-- Lastige omdat dit in combinatie met de oorsprong moet uitlijnen. Minder decimaal wel handig. Ook voor de oorsprong.`


11: Are the pixels square
`-- Yep. Belangrijk!`


12: Are there no extreme pixel values? (dem: -10kmMSL<x<10kmMSL, other rasters: 0<x<10k)


13: Is the cumulative number of pixels of all rasters per setting_id lower than 1.000.000.000
`-- Niet meer strict noodzakelijk. We hebben wel nog geheugen beperkingen maar die liggen inmiddels wel verder.`


14: Is the projection equal to the dem projection
`-- Wel wenselijk`

15: Is the pixel size equal to the dem pixel size?
`-- Welke pixel size is dit??`


16: Is the number of data/nodata pixels equal to the dem.
`-- Wat is het verschil met 18??`

17: Is the number of rows-colums equal to the dem


18: Are pixels correctly aligned (data and nodata locations) with the dem?

19: Check min/max values of DEM in combination wit table_step_size  (max-min)/table_step_size niet meer dan `~10.000/100.000`

**Comment by Jonasvsl** [comment]
There is one more case that needs to be covered: 

1.  if the DEM has a value then most rasters are required to contain a value. 
2.  if the DEM has a nodata value then most raster need to gave a nodata value as well


Case 2 is easy to implement. But for Case 1 we need a way to decide what values to implement. My proposal is to have a popup window or a setting in the toolbox itself that contains the values that need to be used for case 1. 

e.g. 

default values for rasters
friction = 0.02
interception = 1000
infiltration = 14
etc

A nice to have would be an extra raster or pointshapefile containing the locations and what change was made. My guess is that most if not all users are not interested in that. It is mostly one or 2 pixels missing or a misaligned raster that caused issues and users simply want their model to run

**Comment by leendertvanwolfswinkel** [comment]
@Jonasvsl agree that users should be able to set the fill value for each raster. However, I think defaults (other than 0) are always arbitrary. I added a list of all possible rasters to the top of the ticket, makes it a bit easier to think about this. 

The only case where 0 would possibly be a bad idea is friction. It is also difficult to choose another value that makes sense. We also need to deal with the difference between Manning and Chezy for this. Perhaps the average of all non-nodata pixels in the raster?

**Comment by Jonasvsl** [comment]
not sure about the 0 as a default. you need to check that with nici or martijn. I can imagine we will get division by zero errors

**Comment by caspervdw** [comment]
Ik heb een lijstje gemaakt op basis van deze thread. Alle niet noodzakelijke dingen heb ik eruit gelaten.
> 
> Raster checker does 18 checks: 1: Are all filenames of rasters within one setting_id unique? (3Di can handle this, but RC not).

What is RC? For 3Di there is no problem indeed.
> 
> 2: Do the referenced rasters (in all v2_tables) exist on your machine?

Already covered by threedi-modelchecker
> 
> 3: Is the raster file extension .tif / .tiff?

Can be added to threedi-modelchecker
> 
> 4: Is the raster filename valid? (no special characters, no space, max one '.' and '/') `-- In theorie mag hier nu gewoon een padverwijzing instaan (met meerdere slashes)`

Can be added to threedi-modelchecker
> 
> 5: Is the raster single- (not multi-) band?

Can be added to threedi-modelchecker (and upload processor)
> 
> 7: Does the raster have a projected coordinate system (unit: meters) Yep belangrijk

This is only important for the DEM. Can be added to threedi-modelchecker (and upload processor)
> 
> 11: Are the pixels square `-- Yep. Belangrijk!`

Only for DEM.  Can be added to threedi-modelchecker (and upload processor)
> 
> 12: Are there no extreme pixel values? (dem: -10kmMSL<x<10kmMSL, other rasters: 0<x<10k)

Good to have santity checks indeed.  Can be added to threedi-modelchecker (but only locally, this is heavy to check server-side)
>  
> 18: Are pixels correctly aligned (data and nodata locations) with the dem?

see #691 - we are going to solve this serverside
> 
> 19: Check min/max values of DEM in combination wit table_step_size (max-min)/table_step_size niet meer dan `~10.000/100.000`

https://github.com/nens/threedi-tables/issues/154
