### ISSUE TITLE
NetCDF file not correctly exported from waterdepth processing tool

### ISSUE THREAD

**Issue by Jonasvsl** [nens/threedi-results-analysis#576]
Het installeren van de versie die je op de transfer had gezet was nog wel gelukt, maar ik krijg met die tool nog niets anders geproduceerd dan één waterdieptetifje. Ook als ik opgeef dat ik een range wil. Als ik range aanvink en netcdf, dan maakt ie wel een netcdf, maar die heet dan .tif en wordt daardoor ook niet correct ingeladen. Als ik de extensie zelf verander naar .nc en die dan als mesh inlaadt doet ie het wel.

probably needs also a change in the gui, user needs to define a location for the netcdf and change the code accordingly

**Comment by leendertvanwolfswinkel** [comment]
duplicate of #565
