### ISSUE TITLE
Batch calculation water depth maps different timesteps raises error

### ISSUE THREAD

**Issue by lisannewapstra** [nens/threedi-results-analysis#583]
**Topdesk 2107 0090 vraag over batch-berekening waterdieptekaart - Nynke Vellinga (Wetterskip fryslan)**

We have a waterdepth-tool, which also has a batch processing funtion. 
Water depth raster without batch works fine. For batch processing it raises an error. See attachment for the full error. 

_Settings caller_
[batch_waterdieptekaarten.docx](https://github.com/nens/ThreeDiToolbox/files/6862894/batch_waterdieptekaarten.docx)

![image](https://user-images.githubusercontent.com/33685743/126655496-66d7fea7-3b3c-4607-88fe-ba5a85c88c41.png)

Can be reproduced with any model and also with 1 line and t=1.

Something goes wrong with the data type, maar not sure what the tool wants. 

@leendertvanwolfswinkel 

_Original ticket_

> Beste servicedesk,
> 
> Bij het waterschap zijn we begonnen aan een groot onderzoek naar overstromingen en de verschillende factoren die daarbij een grote rol spelen. We willen veel modelruns doen en van elke run meerdere kaarten maken, met de waterdiepte na 1 uur, 2 uur, 4 uur, 12 uur, 24 uur enz. De waterdiepte-tool van 3Di heeft daar een handige batch-functie voor, die ik op het eerste gezicht succesvol heb ingevuld, maar bij het uitvoeren van de tool krijg ik foutmeldingen. Kunnen jullie hierbij helpen? Heb ik iets verkeerd ingevuld, een verkeerde instelling gebruikt, of is er nog iets anders aan de hand?
> 
> De logfile van de tool zit in de bijlage, in dit geval wilde ik bij wijze van test een waterdieptekaart maken van tijdstap 10, 20, 30, 40 en 50. Als jullie meer info nodig hebben, laat het dan vooral weten, ik licht graag extra dingen toe of laat wat zien.
> 
> Alvast hartelijk dank voor de hulp!
> 
> Met vriendelijke groeten,
> Mei freonlike groetnis,
> 
> Nynke Vellinga
>

**Comment by ldebek** [comment]
Fix available on branch: `batch_water_depth_fix`
