### ISSUE TITLE
Checkbox Relative in animation default on

### ISSUE THREAD

**Issue by Patrick-Nijman** [nens/threedi-results-analysis#587]
When you load results and a model. The relative checkbox of animation should be defaulted to on. When you activate animation

![image](https://user-images.githubusercontent.com/86961942/130573079-18d930a5-8705-4109-8f2f-f3dc9e999c88.png)

**Comment by leendertvanwolfswinkel** [comment]
Why?

**Comment by Patrick-Nijman** [comment]
Because this will show you the differences over time. It produces a clearer overview. Please ask Jonas if you need more clarification on this.

**Comment by leendertvanwolfswinkel** [comment]
I understand what the checkbox does (I made it myself :) ). But I think that it really depends on the use case if it you want it checked or not. In some cases you are interested in the absolute water level, in other cases in the rise relative to T0.
