### ISSUE TITLE
Max degrees should also contain a 'free editing' option

### ISSUE THREAD

**Issue by Jonasvsl** [nens/threedi-results-analysis#591]
![degrees](https://user-images.githubusercontent.com/1453159/134958685-44a68512-f390-4fe2-9674-97fb85decd17.png)

The current implementation of the qml for the settings limits users in editing their max degree settings. There are cases where users need to edit these settings and change them, e.g. for speeding up a simulation. 
Can we adjust the qml so we still have the drop down but also a more free editing option?

**Comment by leendertvanwolfswinkel** [comment]
There is no such option in QGIS. It's either free editing _or_ value map, not a combination. In the current implementation it is possible to fill in custom values. Select 'max_degree' from the dropdown at the top, fill in the desired value in the top text input widget and click 'update selected' / 'update all'

It is probably possible to design a custom widget for this, but my feeling is that required effort >> expected gains.

**Comment by nvolp** [comment]
Are you it works, according to Maud it doesn't

**Comment by leendertvanwolfswinkel** [comment]
Works for me:

![max_degree](https://user-images.githubusercontent.com/26224299/135056407-8801a62e-5d1f-419c-b622-e2624c9e9744.gif)

**Comment by Jonasvsl** [comment]
why is the value between ()?

**Comment by leendertvanwolfswinkel** [comment]
QGIS does this to show that the value is not part of the value map for this field

**Comment by nvolp** [comment]
Did you check if this works? As in, does this model run? And is this value written in de .ini file?

**Comment by leendertvanwolfswinkel** [comment]
I did not check it but i am 100% sure that it works. This is a very normal way of editing values in any layer in QGIS.
