### ISSUE TITLE
Add a "migrate" tool to the toolbox

### ISSUE THREAD

**Issue by caspervdw** [nens/threedi-results-analysis#599]
The modelchecker requires a minimum spatialite version of ~201~206. To be able to make the checker work client-side, we need to migrate the spatialite before giving it to the checker.

Luckily, the modelchecker can do this for you (provided that the version is at least ~173~160):

```
from threedi_modelchecker import ThreediDatabase
from threedi_modelchecker.schema import ModelSchema

version = "head"  # this means 'latest', you can also give it a different version here like 204

database = ThreediDatabase(
    connection_settings={"db_path": sqlite_path}, db_type="spatialite"
)
schema = ModelSchema(database)
schema.upgrade(version)
```

This script should be embedded inside a new tool.  @Jonasvsl 

*edit Jan 10, 2022*: Updated version numbers to reflect the latest (0.22) threedi-modelchecker release

**Comment by Patrick-Nijman** [comment]
Added to the 3Di API client
