### ISSUE TITLE
Model checker: allow user to choose log level (info/warning/error)

### ISSUE THREAD

**Issue by caspervdw** [nens/threedi-results-analysis#600]
Recently, the modelchecker started to a accept a `level`, like this:

```
for check in model_checker.checks(level="warning"):
    ...
```

By default, the check level is `"error"`, which means that warning and info  checks will not be done. I think it is best to give the user the option to choose between `"info"`, `"warning"` and `"error"`. `"warning"` means that error + warning checks will be done, `"info"` mens that info + error + warning checks will be done.

@Jonasvsl

**Comment by leendertvanwolfswinkel** [comment]
fixed with https://github.com/nens/ThreeDiToolbox/pull/603
