### ISSUE TITLE
Rewrite raster checker to enable new checks

### ISSUE THREAD

**Issue by Patrick-Nijman** [nens/threedi-results-analysis#615]
There are a number of issues with the raster checker which we would like to solve on a short term base. I am bundling these so we can reserve time in a sprint and make sure we are adding all things we need so we don;t have to address the rasterchecker for some time.

**Comment by leendertvanwolfswinkel** [comment]
Related tickets:
#614
#515
#562
#597
#616
#623
#574
#467
#692
