### ISSUE TITLE
Add a check in the toolbox for spatialite file version

### ISSUE THREAD

**Issue by caspervdw** [nens/threedi-results-analysis#631]
QGIS 3.22 has spatialite library version 5 (on Windows). For this library version, our current spatialite files (which were created with lib version 3) do not work anymore.

- [x] Task: Notify the user about this when the spatialite file is opened. There is a convenient version-check function in `threedi_modelchecker.spatialite_versions`. Direct users to the upgrade tool (which already exists).
- [x] Task: The upgrade tool should call the modelchecker's `ModelSchema().upgrade()` with `upgrade_spatialite_version=True`.
- [x] Task: A possible `threedi_modelchecker.errors.UpgradeFailedError` should be caught and the user should get a message as follows:

> There are errors in the spatialite. Please re-open this file in QGIS 3.16, run the model checker and fix error messages. Then attempt to upgrade again. For questions please contact the servicedesk.

Epic: https://github.com/nens/threedi-api/issues/1627

**Comment by leendertvanwolfswinkel** [comment]
It all works like a charm. Minor improvement still needed:
- "Model" dropdown should be left in its original state (i.e. empty or with the same path as before) if the selected sqlite cannot be loaded due to wrong spatialite version.

**Comment by ldebek** [comment]
@leendertvanwolfswinkel After review fixes are now on master branch.
