### ISSUE TITLE
Add Watershed Tool

### ISSUE THREAD

**Issue by leendertvanwolfswinkel** [nens/threedi-results-analysis#641]
We would like to introduce the functionality of this repo https://github.com/nens/threedi-network-analyst/ to the 3Di Toolbox.

- Name of the tool should be "Watershed Tool"
- The tool should be available through an icon on the 3Di Toolbox Toolbar (@gijs could you please provide a png image for the button?)
- Not much needs to be changed to the code, but a quick review + feedback is definitely welcome
- In the current implementation, user inputs gridadmin.h5 file + results_3di.nc file + (optionally) spatialite file. When integrated in the 3Di Toolbox, it should instead use the files that the user already selected in the "Load model & results" dialog. If the user has selected >1 results, just use the first one (as most other tools do as well; we will redesign the whole results management in Q3, so no need for more fancy solutions now)

**Comment by gijs** [comment]
I'm working on a company-wide icons repository, but until that's ready...

[icon.zip](https://github.com/nens/ThreeDiToolbox/files/8890524/icon.zip) - contains an svg and png version

**Comment by leendertvanwolfswinkel** [comment]
Great stuff! 

Some minor feedback / points of improvement:
- [x] Tooltip for the button in the Toolbar should read 'Watershed Tool'
- [x] Button should also be enabled if no results are loaded, because this tool allows users to select results in the tool itself
- [x] Please remove the check boxes 'Single cells' and 'Flow Pattern' in the 'Outputs' section

After these changes you can merge with master

@gijs I think the icon works really well at this small size.
