### ISSUE TITLE
Migrate spatialite if necessary, instead of just telling users to do it themselves

### ISSUE THREAD

**Issue by leendertvanwolfswinkel** [nens/threedi-results-analysis#644]
Last bit of the user feedback ("Please migrate ... ") should be changed to: "Would you like to migrate the spatialite now?" OK | Cancel

**Comment by leendertvanwolfswinkel** [comment]
Message / implementation should be the same as in https://github.com/nens/threedi-schematisation-editor/issues/50

**Comment by ldebek** [comment]
Changes on branch: https://github.com/nens/ThreeDiToolbox/tree/migration_on_the_fly

**Comment by leendertvanwolfswinkel** [comment]
Tested. Excellent workflow. Please merge with master
