### ISSUE TITLE
MacOS compatibility

### ISSUE THREAD

**Issue by leendertvanwolfswinkel** [nens/threedi-results-analysis#648]
@gijs runs into issues when trying to install 3Di Toolbox 2.1 on MacOS.

To fix the issues, he made some changes to the method `_get_python_interpreter()` in `dependencies.py` (see below).

Please look into this and find out if these proposed changes can be implemented to fix the 3Di Toolbox for MacOS

```
def _get_python_interpreter():
    """Return the path to the python3 interpreter.
    Under linux sys.executable is set to the python3 interpreter used by Qgis.
    However, under Windows/Mac this is not the case and sys.executable refers to the
    Qgis start-up script.
    """
    interpreter = None
    executable = sys.executable
    directory, filename = os.path.split(executable)
    if "python3" in filename.lower():
        interpreter = executable
    elif "qgis" in filename.lower():
        interpreter = os.path.join(directory, "bin", "python3") # <--- Makes it work on MacOS
    else:
        raise EnvironmentError("Unexpected value for sys.executable: %s" % executable)
 #   assert os.path.exists(interpreter)  # safety check, disabled on MacOS
    return interpreter
```

**Comment by gijs** [comment]
Nice!

If needed I can assist (ie. debug, test stuff) on my Macbook.

Error message:
![Screenshot 2022-06-27 at 09 19 52](https://user-images.githubusercontent.com/7193/175882366-6e312bbf-360d-4319-aa69-6665c8c3b157.png)

QGIS About screen:
![Screenshot 2022-06-27 at 09 20 06](https://user-images.githubusercontent.com/7193/175882381-afaf68cb-8100-4fab-b79d-9e8bdb9afb5e.png)

**Comment by gijs** [comment]
For the sake of documentation:
```
import sys
import os
import platform
dir, file = os.path.split(sys.executable)
print(dir)
/Applications/QGIS.app/Contents/MacOS
print(file)
QGIS
print(platform.system())
Darwin
```

**Comment by benvanbasten-ns** [comment]
`python3` resides in `/Applications/QGIS.app/Contents/MacOS/bin/python3`

**Comment by gijs** [comment]
After some back & forth with @benvanbasten-ns it's fixed:

![Screenshot 2022-06-27 at 15 54 40](https://user-images.githubusercontent.com/7193/175958888-4d01dfb8-258a-4819-ace4-3fea1fbd9205.png)

👍

**Comment by benvanbasten-ns** [comment]
Still need to test the underlying mechanism (in particular whether the provided dependencies all work on Mac)

**Comment by gijs** [comment]
Tested with a model result from Leendert (tuindorp sim 75756.zip)

Loading the file (sqlite, nc) works, as do the Water Balance and Watershed Tool.

However, the Statistical Tool fails, see Stack Trace below.

![Screenshot 2022-06-28 at 14 06 56](https://user-images.githubusercontent.com/7193/176174638-5bca283d-e9d9-4fe7-a698-e9be1a6f0c4c.png)
![Screenshot 2022-06-28 at 14 07 15](https://user-images.githubusercontent.com/7193/176174647-24155d43-d085-4434-a50c-ec95451ccf41.png)


![Screenshot 2022-06-28 at 14 07 37](https://user-images.githubusercontent.com/7193/176174669-560f8363-a414-45f6-8384-93fbf8b19592.png)

**Comment by benvanbasten-ns** [comment]
Closed: not implementing
