### ISSUE TITLE
[3Di]: Total balance in water balance tool does not work in QGIS 3.22

### ISSUE THREAD

**Issue by Patrick-Nijman** [nens/threedi-results-analysis#659]
- [x] https://github.com/nens/servicedesk-issue-only/issues/67

### What happened?

The total balance option in the water balance tool gives no results, see pic. This only applies for MI 3.22

![image](https://user-images.githubusercontent.com/73856313/175312252-cb05cfc8-656e-4121-b6c0-479b341d9194.png)

### How to Reproduce?

Install the MI 3.22, download for example the model of https://management.3di.live/schematisations/5564/41024 and import the model+results in the MI. Open the waterbalance tool and draw a polygon. Close the polygon and the curves will show. Now press the total balance button. It's a zero. In 3.16 this is not the case.

### Additional info

I tried the water balance tool in the MI 3.16 for the exact same model+results, which worked:

![image](https://user-images.githubusercontent.com/73856313/175313028-f9fc2b24-9995-4920-9b29-1ad8342eb0c8.png)

**Comment by leendertvanwolfswinkel** [comment]
@Patrick-Nijman please add a download link to the simulation results

**Comment by Patrick-Nijman** [comment]
Rusults are too big to upload here. Everyone should be able to access: https://nelenschuurmans-my.sharepoint.com/:u:/g/personal/patrick_nijman_nelen-schuurmans_nl/EZVSvtq5iPZCl4ruoJbZvfIBjQHpMK90MDcdZYgIi8F9cA?e=MCh4U1

**Comment by ldebek** [comment]
Fix available on branch: `water_balance_and_sideview_fixes`
