### ISSUE TITLE
Results manager

### ISSUE THREAD

**Issue by leendertvanwolfswinkel** [nens/threedi-results-analysis#662]
**Introduction**
_Remove spatialite from results analysis_
All functionality in the 3Di Toolbox that has to do with visualisation and analysis of results currently requires loading the spatialite:
- Graph Tool: Graphs of timeseries 
- Animation Toolbar: Visualize results on map
- Sideview Tool: Sideview with water levels
- Water Balance Tool: Water balance for selected polygon
- Statistics Tool: Statistics / aggregations (currently for sewerage only)
- Watershed Tool: Upstream / downstream areas for selected point(s)
- Generate water depth/level rasters (processing algorithm)

In the 3Di Toolbox, results (.nc files) are linked to the spatialite. With the new 3Di results manager, there will no longer be any link to the spatialite. To be able to migrate this functionality, some form of results management needs to be implemented. Redesigning this is a good opportunity to improve the (buggy) results management as implemented in the 3Di Toolbox.

_Multiple results_
Users need to be able to interact with multiple 3Di results sets at the same time. As much as possible, we want the existing analytical tools (currently available in the 3Di Toolbox) to support multiple results. This also means that within the UI of each tool, users should be able to switch between results sets and/or toggle some result sets on and others off.

_UI design_
https://www.figma.com/file/U5KH82heuwdFW0hYBwwTNx/3Di-Results-Manager?node-id=104%3A196

**Relevant files**
3Di result sets consists of the following files:

- gridadmin.h5 (computational grid)
- results_3di.nc (results per element of the computational grid)
- aggregate_results.nc (optional) (time-aggregated results per element of the computational grid)

Several results_3di.nc files may be linked to a single computational grid. Users should be able to load multiple computational grids at the same time, and load multiple (aggregate_)results_3di.nc files for each of these computational grids.

**Loading / unloading a computational grid**
See #681 for details

**Loading / unloading result sets**
See #682 for details

**Closing/opening QGIS project**
The list/tree of computational grids and simulation results that have been added to the project should be saved in the project file, so that it is available again when loading the project

**Connection with Models & Simulations plugin**
The Models & Simulations plugin should be able to interact with the results manager, e.g. when a computational grid and/or simulation results have been downloaded, users should have the option to add them to their project from that same dialog

**Comment by Jonasvsl** [comment]
The computational grid is available in the netcdf

`Loading a result set does not add any extra layers to the QGIS project. It simply adds a reference to the .nc file(s) that is accessible for the analytical tools`
Why not? How would the user be able to see animations?


Can you add a section on the tools we use for analysis?
- graph tool
- stats tool
- water balance
- flow summary
Add an intuitive link to water depth over time from lizard geotiffs/wms?

**Comment by leendertvanwolfswinkel** [comment]
To use any of the analytical tools, the h5 file will be needed anyway, so the nc will never be enough. Also I'd prefer to have one single way to visualize / interact with the computational grid.

What I mean with "only adding reference to the .nc file", is that the results manager itself will not add any layers. Tools that interact with the netcdf may add layers. E.g. the Animation Toolbar reads from the results manager which files to use, and adds any needed layers to the project.

I have added a list of tools to be migrated from the 3Di Toolbox

**Comment by leendertvanwolfswinkel** [comment]
Test dataset (model spatialite + gridadmin + results) here: https://we.tl/t-1BVpleZZce

**Comment by leendertvanwolfswinkel** [comment]
Duplicate/related: #468

**Comment by leendertvanwolfswinkel** [comment]
Closing this now as any additional work on this will be defined in smaller tickets
