### ISSUE TITLE
Connect 3Di Custom statistics to the results manager

### ISSUE THREAD

**Issue by leendertvanwolfswinkel** [nens/threedi-results-analysis#669]
The ultimate goal is that the beta plugin that lives here https://github.com/threedi/beta-plugins/tree/master/threedi_custom_stats replaces the current "Statistics" tool. This ticket describes a very basic implementation.

A testing version of this tool can be installed using this zip file: https://github.com/threedi/beta-plugins/releases/tag/customstatistics_v0.6.0

- [x] Transfer beta plugin to statistics tool and do rudimentary clean up
- [x] Transfer processing algorithms
- [x] Tool name: "3Di result aggregation"
- [x] Tooltip: "Post-processing tool to make custom time aggregations of 3Di results and visualize the on the map canvas"
~~- [ ] Reshape test scripts into unit tests -> code no longer functional (no longer compatible)~~
- [x] In the UI of the tool, "Input" tab, replace the two input widgets "3Di results NetCDF" and "3Di gridadmin file" by a results dropdown that is populated by the results loaded through the results manager (similar to the Watershed tool).
- [x] Add the output layers to a subgroup "Result aggregation outputs", same level as the subgroup "Watershed tool outputs"

**Comment by benvanbasten-ns** [comment]
- [x] Refactor ogr2gis to utils (also used in watershed)
- [x] For this tool, layers should not be reused, but always newly created
