### ISSUE TITLE
Connect SideView Tool to new results manager and make independent from spatialite / gridadmin.sqlite

### ISSUE THREAD

**Issue by leendertvanwolfswinkel** [nens/threedi-results-analysis#670]
- [x] Connect to native QGIS Temporal Controller
- [x] Connect to results manager
- [x] All relevant data is gathered from gridadmin.h5 and 0 or more results_3di.nc (this requires quite some mapping)
- [x] Kill this: ![image.png](https://images.zenhubusercontent.com/62bedb7b667872a01ff3bdff/201ba734-fa4e-438e-9678-c8ccb8d0c3e9)

**Comment by leendertvanwolfswinkel** [comment]
@benvanbasten-ns you asked how we should visualize open cross sections. I took the question a bit wider and made some sketches of what I think the viz should look like:

EDIT: as discussed today, where it says bank level, it would be better to use the (lowest) `dpumax` of the 1D2D flowlines connected to that calculation node

Channel(s) and Weir:
<img width="576" alt="Channel and Weir" src="https://user-images.githubusercontent.com/26224299/228831631-fa8194cd-432c-4931-a0d3-df1710061011.png">

Pipes and Manholes:
<img width="576" alt="Pipes and Manholes" src="https://user-images.githubusercontent.com/26224299/228831657-ef7f227c-94ae-4d63-a803-02450247d91c.png">

Pipes and Manholes and Weir:
<img width="576" alt="Pipes, Manholes, Weir" src="https://user-images.githubusercontent.com/26224299/228831679-f173b709-c6a3-4855-93c3-07df383ba3eb.png">

**Comment by leendertvanwolfswinkel** [comment]
@benvanbasten-ns you asked how we should visualize open cross sections. I took the question a little bit broader and made some sketches of what I think the visualization should look like:

**Comment by leendertvanwolfswinkel** [comment]
@benvanbasten-ns if weir or orifice has a closed profile, viz could be like this: ![image.png](https://images.zenhubusercontent.com/62bedb7b667872a01ff3bdff/c9849251-a786-447f-b381-81a98038aa17)

**Comment by benvanbasten-ns** [comment]
@leendertvanwolfswinkel Your Paint-skills never cease to amaze me

**Comment by leendertvanwolfswinkel** [comment]
"And the crowd went absolutely bananas" https://www.youtube.com/watch?v=XbY8MH1TpEw

**Comment by benvanbasten-ns** [comment]
- [ ] Solve Python error on close
- [ ] Select route in grid (flowline layer)
