### ISSUE TITLE
Computational Grid: re-order processing algorithms

### ISSUE THREAD

**Issue by leendertvanwolfswinkel** [nens/threedi-results-analysis#672]
We currently have (in the dev version 2.3) the following processing algo's:
- Convert gridadmin to geopackage
- Generate gridadmin

Testers found this confusing / did not fit user needs. These two algorithms should be replaced by:

_Computational grid from schematisation_
This algo basically chains the two existing processing algorithms
Input = spatialite
Output = {user_defined_name}.gpkg
Layers from gridadmin.gpkg are added to the QGIS project.

_Computational grid from gridadmin.h5 file_
This is `Convert gridadmin to geopackage`, just with a different name

**Comment by ldebek** [comment]
Changes available on branch: https://github.com/nens/ThreeDiToolbox/tree/computational_grid_reordering
