### ISSUE TITLE
Computational Grid: save styling in geopackage

### ISSUE THREAD

**Issue by leendertvanwolfswinkel** [nens/threedi-results-analysis#673]
After generating the 'computational grid' geopackage, please save the stylings as default stylings for those layers.

This is a nice-to-have; if it is estimated to be more than 4 hours work, please skip it.

**Comment by ldebek** [comment]
Available on branch: `computational_grid_improvements`

**Comment by ldebek** [comment]
Available on branch: `computational_grid_improvements`
