### ISSUE TITLE
Add computational grid from the results manager

### ISSUE THREAD

**Issue by leendertvanwolfswinkel** [nens/threedi-results-analysis#681]
Please read #662 for the larger context of this ticket

To visualize the computational grid, it needs to be converted from HDF5 (.h5) to GeoPackage (.gpkg). This conversion may take several minutes. 

- [x] Users can load either the .h5 file or the .gpkg file.
- [x] Each computational grid should have a name/label. Users can change this name, but initially it should be filled automatically, e.g. if it is in the 3Di Models & Simulations local directory structure with the schematisation name + revision nr, or if not, just a number.
- [x] Upon loading the computational grid, the layers are added to the layer tree in a group
- [x] Users can add multiple computational grids
- [x] Users can remove computational grids. This also removes the associated data from the QGIS project and a signal is sent to be picked up by the different tools (e.g. Graph Tool) to remove associated data.
- [x] When user saves project and loads it again, the information about which computational grids are loaded is stored in the QGIS project file
- [x] Switching to another project (to new or existing project) does not lead to issues like this one: https://github.com/nens/threedi-api-qgis-client/issues/155

**Comment by benvanbasten-ns** [comment]
Some technical items that need to be done:

- [x] The startup sequence of the plugin (connecting signals/slots etc) needs to be moved from init() to initGUI() (as much as possible)
- [x] The folder "layer_styles" needs to be checked, and items need to be moved to the accompanying tools
- [x] The plugins' unload process needs to be checked to see if all resources/layers/signals/slots created in the main plugin module are properly destroyed (this also has to be done for the individual tools in a later stage). This allows reloading of the plugin.
- [x] In case a grid (file) is not valid, it should be shown in the tree
- [x] Make flow chart of signals
- [x] Removed compiled resources, no longer necessary
- [x] Remove travis references, no longer used
- [x] Clear results manager when project is cleared
- [x] Store last openened directory in QSettings and use when opening file
- [x] Result manager is now stored in qgis file with absolute paths. Make relative if required in project settings
- [x] Use figma icons
- [x] Check whether the grid (geopackage, or h5) is already loaded in the model, if so, don't load
- [x] Don't store the h5 path, but resulting gpkg path
- [x] Save computational grid name when modified

**Comment by leendertvanwolfswinkel** [comment]
I have tested this. Almost everything works exactly how it was described in this ticket, great work! 

The only exception is task #2 (each computational grid should have a name/label). If I load a gridadmin that is stored in my 3Di working directory, the name in the results manager is just a number (0, 1, 2, etc.).

**Comment by benvanbasten-ns** [comment]
@leendertvanwolfswinkel 
The code checks whether the directory structure containing the gridadmin is as follows:

- admin
- grid
- results
- schematisation / rasters

In case one of these folders is missing, it labels the grid with just a number. Is that correct, or should we relax this a bit?

**Comment by leendertvanwolfswinkel** [comment]
If the gridadmin is located in the 3Di working directory structure, its parent directory could be called "grid" or "results". The parent folder will be called "revision _n_" or "work in progress". The parent of those directories will have the name of the schematisation. 

I think the check should be (pseudo-code): `gridadmin_file.parent in ("grid", "results") and gridadmin_file.parent.parent in ("revision _n_", "work in progress")`

And then the name is `"{gridadmin_file.parent.parent.parent} #{revision_number}"`

**Comment by leendertvanwolfswinkel** [comment]
The naming of the groups still doesn't work for me. Another way to explain what I mean, using 3 examples (i.e. the only 3 possible valid locations for a gridadmin file in the 3Di working directory structure):

1. In the results folder. Location is `Fuerthen\revision 16\results\sim_89864_Fuerthen_rev16_no_rain_24h\gridadmin.h5`; Name should be `Fuerthen #16`

2. In the grid folder. Location is `Fuerthen\revision 16\grid\gridadmin.h5`; Name should be `Fuerthen #16`

3. In the grid folder of the work in progress folder. Location is `Fuerthen\work in progress\grid\gridadmin.h5`; Name should be `Fuerthen (WIP)`

If the gridadmin does not seem to be in the working directory, please use the name of the containing folder as name. Location is `C:\Temp\My best model\gridadmin.h5`; Name should be `My best model`
