### ISSUE TITLE
Add results from the results manager

### ISSUE THREAD

**Issue by leendertvanwolfswinkel** [nens/threedi-results-analysis#682]
Please see #662 for the full context of this ticket

- [x] Each result set should have a name/label. Users can change this name, but initially it should be filled automatically, e.g. the name of the parent directory of the results_3di file
- [x] Users select the results_3di file. It is assumed that the aggregate_results_3di file is located in the same directory. If it is not found, a warning message should be given to the user.
-  [x] If possible, it should be checked if the selected .nc files belong to the selected .h5 or .gpkg computational grid file (please ask  @jpprins1 for technical details). We probably need to store some unique identifier in the gpkg as well; if so, this should be added to the threedigrid export to Geopackage functionality.
-  [x] Loading a result set adds a reference to the .nc file(s) that is accessible for the analytical tools
-  [x] Users can remove result sets. A signal is sent to be picked up by the different tools (e.g. Graph Tool) to remove associated data.
-  [x] When user saves project and loads it again, the information about which result sets are loaded is stored in the QGIS project file

**Comment by leendertvanwolfswinkel** [comment]
Apparently I forgot to add this ticket to the 3Di Toolbox 3.0 epic. This is one of the most crucial steps in the refactor!

**Comment by benvanbasten-ns** [comment]
Technical requirements

- [x] LayerManager that controls and listens to layers in LayerPanel
- [x] In case the user drags a layer out of the layer group, it should still be removed when the grid is removed
- [x] This should all work when the project is saved and reloaded (use UUID to check whether layer should be loaded

**Comment by leendertvanwolfswinkel** [comment]
Tested, almost everything appears to work the way it should. One exception:

When saving & loading the project, the results manager panel still contains the grids, but the results are no longer there. Please fix this
