### ISSUE TITLE
Raster fixer: reproject rasters that have other CRS than DEM

### ISSUE THREAD

**Issue by leendertvanwolfswinkel** [nens/threedi-results-analysis#689]
For full context see https://github.com/nens/ThreeDiToolbox/issues/574

*Inputs*
- Digital Elevation Model
- A list of other rasters

*Outputs*
- Preferably, rasters are edited in-place; otherwise, let users choose a postfix (e.g. '_fixed_crs')

*Algorithm*
- Reproject rasters that have other CRS than DEM

*Feedback*
- The python method should accept a feedback object to report progress (0-100) using `.setProgress()` and logging. Please check with @ldebek for details.

**Comment by caspervdw** [comment]
Backend solution: https://github.com/nens/threedi-tables/pull/198
