### ISSUE TITLE
Raster fixer: match DEM data pixels

### ISSUE THREAD

**Issue by leendertvanwolfswinkel** [nens/threedi-results-analysis#691]
For full context see https://github.com/nens/ThreeDiToolbox/issues/574

Include checks: is the raster the same as the DEM in terms of:
- extent
- pixel size
- skew / rotation (should be 0)
- crs

*Inputs*
- Digital Elevation Model
- A list of other rasters
- For each raster in the list, a fill value (defaults to 0)

*Outputs*
- Preferably, rasters are edited in-place; otherwise, let users choose a postfix (e.g. '_fixed_data_pixels')

*Algorithm*
- Set all pixels to the user-defined fill value where the DEM has a value but the other raster does not
_Note: Initial (ground)water level rasters are an exception to this rule; probably relevant for user manual only, not for the algorithm_

*Feedback*
- The python method should accept a feedback object to report progress (0-100) using `.setProgress()` and logging. Please check with @ldebek for details.

**Comment by caspervdw** [comment]
This is so similar to #690 that I will close the other one and start discussion on the subject here.

**Comment by caspervdw** [comment]
Proposal discussed with @martijn-siemerink . Please let me know what you think @leendertvanwolfswinkel  and @Jonasvsl :

We will accept raster input with nodata where the DEM has data, or data where the DEM has nodata.

On reading the raster in tables, we 1) overwrite all nodata value with the global default (e.g. `v2_global_settings.frict_coef`) and 2) mask the result with the DEM nodata mask. There is little overhead there and it is perfectly explainable to the user. You could also imagine that the user wants `0` interception everywhere, except for a small region. In this proposal, the user only has to supply a raster for the small region.

For this to work, we need the global value, which is currently not compulsory. We should recommend the user to always supply default values. Making the columns `interception_global`, `frict_coef` compulsory is one step to far, but we can make warnings in the modelchecker saying something like:

- "Without a global friction value (frict_coef), model generation may yield errors in case the raster is missing data. We recommend always setting a global value.".

Stuff we need to do to make this work will be largely in threedi-tables:

- [ ] Insert global values (if present) into the rasters before building tables
- [ ] Mask rasters with the DEM before building tables; raise error if there are values missing. --> https://github.com/nens/threedi-tables/issues/199
- [ ] Add a check for the presence of all global raster values (threedi-modelchecker)

**Comment by Jonasvsl** [comment]
sounds good to me. I think that is what users want in almost all cases. And when they don't want this they'll have to supply a raster with data themselves.

@leendertvanwolfswinkel  curious what you think
