### ISSUE TITLE
Compatibility with schema version 208

### ISSUE THREAD

**Issue by leendertvanwolfswinkel** [nens/threedi-results-analysis#693]
- [x] bump the version of `threedi_modelchecker` to 0.28
- [x] set the minimum required schema version to 208
- [x]  Remove table_step_size_volume_2d from the `v2_global_settings` attribute form (tabs 'grid' and 'extra options 2D' respectively)
- [x] Add maximum_table_step_size to `v2_global_settings` attribute form (tab 'Grid') (both are float fields)

**Comment by ldebek** [comment]
Changes available under compatibility_with_schema_208 branch.

**Comment by leendertvanwolfswinkel** [comment]
Tested
