### ISSUE TITLE
Raster checker: accept backslashes in paths

### ISSUE THREAD

**Issue by Patrick-Nijman** [nens/threedi-results-analysis#696]
- [x] https://github.com/nens/servicedesk-issue-only/issues/80

### What priority should we assign to this submission?

Prio2 Urgent

### 3Di component

Modeller Interface (QGIS)

### What happened?

Sjon experiences problems when he tries to create a new schematisation and uses an existing spatialite. The problem comes down to incorrect raster location names, because of using a \ iso a /. 

![image](https://user-images.githubusercontent.com/73856313/181771414-41472617-bd39-4885-b3d7-84e86100b1ee.png)

### How to Reproduce?

1) Download any schematisation which contains one or more rasters.
2) Create a new schematisation and use the Choose file option for the spatialite
3) The rasters in the old schematisation are copied to the new one, but have a wrong filepath in the global settings

### What did you expect and what was the actual result?

One would expect the filepaths to be correct and the new schematisation to upload w/o problems

**Comment by leendertvanwolfswinkel** [comment]
This is an issue of the raster checker, users can still upload and process into a 3Di model.

Issue will be fixed when raster checker is refactored
