### ISSUE TITLE
[Bug]: pygeos is missing from the external_dependencies

### ISSUE THREAD

**Issue by caspervdw** [nens/threedi-results-analysis#707]
### Complexity

moderate

### Priority

medium prio

### What happened?

I installed the toolbox using the guide from the docs (qgis 3.22, some extra system packages like python3-h5py, then the toolbox).

I got an error complaining pygeos isn't there.

It seems that the installer is looking in the `external_dependencies` for pygeos, but it isn't there.

### How to Reproduce?

On Ubuntu 22.04:

- install qgis 3.22
- enable 3Di plugin repo
- `apt install python3-h5py python3-scipy python3-pyqt5.qtwebsockets`
- enable 3Di toolbox 

### What did you expect and what was the actual result?

pygeos installs automatically

### Relevant log output

```shell
Installed networkx into /home/casper/.local/share/QGIS/QGIS3/profiles/default/python/plugins/ThreeDiToolbox/deps
Trying to uninstalling dependency condenser
WARNING: Skipping condenser as it is not installed.

Installing 'condenser' into /home/casper/.local/share/QGIS/QGIS3/profiles/default/python/plugins/ThreeDiToolbox/deps
Looking in links: /home/casper/.local/share/QGIS/QGIS3/profiles/default/python/plugins/ThreeDiToolbox/external-dependencies
Processing /home/casper/.local/share/QGIS/QGIS3/profiles/default/python/plugins/ThreeDiToolbox/external-dependencies/condenser-0.1.1-py2.py3-none-any.whl
Installing collected packages: condenser
Successfully installed condenser-0.1.1

Installed condenser into /home/casper/.local/share/QGIS/QGIS3/profiles/default/python/plugins/ThreeDiToolbox/deps
Trying to uninstalling dependency pygeos
Found existing installation: pygeos 0.13
Uninstalling pygeos-0.13:
  Successfully uninstalled pygeos-0.13

Installing 'pygeos' into /home/casper/.local/share/QGIS/QGIS3/profiles/default/python/plugins/ThreeDiToolbox/deps
Looking in links: /home/casper/.local/share/QGIS/QGIS3/profiles/default/python/plugins/ThreeDiToolbox/external-dependencies
ERROR: Could not find a version that satisfies the requirement pygeos>=0.12.0 (from versions: none)
ERROR: No matching distribution found for pygeos>=0.12.0
```

**Comment by caspervdw** [comment]
Same issue with `threedigrid_builder`; I did this to fix the issue:

- `pip wheel threedigrid_builder`
- `cp threedigrid_builder-1.5.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl /home/casper/.local/share/QGIS/QGIS3/profiles/default/python/plugins/ThreeDiToolbox/external-dependencies`

**Comment by leendertvanwolfswinkel** [comment]
Fixed on `refactor` branch
