### ISSUE TITLE
Compatibility with schema version 209

### ISSUE THREAD

**Issue by leendertvanwolfswinkel** [nens/threedi-results-analysis#708]
- [x] bump the version of threedi_modelchecker to 0.31
- [x] set the minimum required schema version to 209
- [x] in the Check Schematisation processing algorithm, call the new method `threedi_modelchecker.schema.ModelSchema.set_spatial_indexes()` before running the schematisation checker
- [x] when loading a spatialite, after checking the schema version (and migrating if relevant), run `threedi_modelchecker.schema.ModelSchema.set_spatial_indexes()`

**Comment by ldebek** [comment]
Changes available on branch: https://github.com/nens/ThreeDiToolbox/tree/compatibility_with_schema_209

**Comment by leendertvanwolfswinkel** [comment]
@ldebek  I tried to run the processing algorithm "Check schematisation" on this spatialite 
[Meerssen Verwacht T25 Gebiedsbreed - Original.zip](https://github.com/nens/ThreeDiToolbox/files/9952657/Meerssen.Verwacht.T25.Gebiedsbreed.-.Original.zip), but I get the following error:

```
Traceback (most recent call last):
File "C:\Users/leendert.vanwolfswin/AppData/Roaming/QGIS/QGIS3\profiles\3Di MI testing/python/plugins\ThreeDiToolbox\processing\schematisation_algorithms.py", line 155, in processAlgorithm
schema.set_spatial_indexes()
File "C:\Users\leendert.vanwolfswin\AppData\Roaming\QGIS\QGIS3\profiles\3Di MI testing\python\plugins\ThreeDiToolbox\deps\threedi_modelchecker\schema.py", line 264, in set_spatial_indexes
raise MigrationMissingError(
threedi_modelchecker.errors.MigrationMissingError: Setting views requires schema version 209. Current version: 207.
```

Probably just a matter of changing the sequence of the performed actions?

If I run the Migrate spatialite tool first, it works perfectly.

**Comment by ldebek** [comment]
Issue should be fixed now.
