### ISSUE TITLE
Convert 'commands' to Processing Algorithms

### ISSUE THREAD

**Issue by leendertvanwolfswinkel** [nens/threedi-results-analysis#715]
Convert 'commands' to Processing Algorithms:
- [x] Remove raster checker (has been integrated into Schematisation Checker)
- [x] Remove schematization checker (is already available as Processing Algorithm)
- [x] Remove Create breach locations: New tooling will be developed in Breaches project.
- [x] Remove Add connected points: New tooling will be developed in Breaches project. 
- [x] Remove Predict calculation points: New tooling will be developed in Breaches project. 
- [x] Convert 'Import SufHyd' to processing algorithm (also include #726 )
- [x] Convert 'Guess indicators' to processing algorithm(s)
- [ ] ~~Control structures. Make separate tool (3Di Toolbox could also be released without this tool if needed)~~

**Comment by benvanbasten-ns** [comment]
- [x] Schematisation Checker still refers to raster-checker command -> Reorganize
- [x] Import sufhyd.  Should the sufhyd data still be imported to spatialite?

**Comment by leendertvanwolfswinkel** [comment]
> Remove raster checker (has been integrated into Schematisation Checker)

On `master`, this processing algorithm has already been removed, but on `refactor` it still exists. Please remove it here also

**Comment by benvanbasten-ns** [comment]
@benvanbasten-ns remove raster-checker from both Commands and Processing Algorithms

**Comment by leendertvanwolfswinkel** [comment]
@benvanbasten-ns can you implement the above to master as well?
