### ISSUE TITLE
Improvements for 3Di Results manager

### ISSUE THREAD

**Issue by leendertvanwolfswinkel** [nens/threedi-results-analysis#717]
- [x] Rename dock panel title from ThreeDiPlugin to "3Di Results Manager"
- [x] Add Tooltips to the buttons in the Result manager
- [x] If group is renamed in the layer panel, also rename in the results manager
- [x] Style and name the grid layers the same way as is done in the processing algorithm
- [x] Layer order must be: Pump (point), Node, Pump (line), Flowline, Cell
- [x] User feedback at the top: please make them all in the style: "3Di Results Manager: {message}"
- [x] The computational grid are added to a group called 'Toolbox'. Please rename to "3Di Results"

**Comment by arjanverkerk** [comment]
@leendertvanwolfswinkel  What is the scope of "all" in "User feedback at the top: please make them all" - all related to loading and removing models and results, or all messages throughout the plugin?

EDIT: I take it for now that you mean the latter.

**Comment by leendertvanwolfswinkel** [comment]
Yes, all user feedback related to loading & removing computational grids and simulation results

**Comment by leendertvanwolfswinkel** [comment]
Test results:

"If group is renamed in the layer panel, also rename in the results manager" does not work (so I unchecked it)

All the other stuff works!
