### ISSUE TITLE
Results manager: same look and feel as Models & Simulations plugin

### ISSUE THREAD

**Issue by leendertvanwolfswinkel** [nens/threedi-results-analysis#718]
My (Leendert) feedback on the current design:
- [x] I don't like the term 'Animation'. I think something like ‘visualization settings’ would be more appropriate, as the settings under this header determine how the results are visualized on the map canvas.
- [x] Remove the green checkmarks, they have no meaning
- [x] Remove LCD display
- [x] Add time since start of simulation (d hh:mm) to each simulation result (e.g. to the right on the same line/row)
- [x] Put the ‘relative’ checkbox below the Node variable dropdown menu, so there is more space for the variable name
- [x] Set vertical size to full screen when loading the plugin
- [x] Logo should not be allowed to be cut off (if we even keep the logo)
- [ ] Results manager panel as a whole should be as simple as possible and have the same look & feel as the Models & Simulations panel.

**Comment by gijs** [comment]
I wanted to update the design to reflect the feedback from @leendertvanwolfswinkel

But my QGIS situation is quite hairy(*) and I have no idea where to look to get the current state of this plugin.
I asked @arjanverkerk / @benvanbasten-ns to help me out via Teams.


(* I seem to have four 3Di plugins installed, don't know which is which anymore)

**Comment by arjanverkerk** [comment]
To automatically fill the screen vertically when loading the plugin is an interesting one. If there is no other dockwidget in the area, this happens automatically. Otherwise, a solution is to tabify with the existing dockwidgets in the right half of the window. That's what I tried to achieve now. I hope it is not too brittle.

**Comment by benvanbasten-ns** [comment]
> 

I think we should not force this. The preferred size policy is now to vertically expand as much as possible. I don't think we should move other widgets

**Comment by arjanverkerk** [comment]
But @leendertvanwolfswinkel said 'full screen' - I don't know how to that, other than using tabs, when there are existing dockwidgets in that area. Or do you mean we should not _move_, but _remove_ other widgets instead? Anyway, let him shine some light on this.

**Comment by leendertvanwolfswinkel** [comment]
Created a new separate ticket for the last checkbox (look & feel) https://github.com/nens/ThreeDiToolbox/issues/785
