### ISSUE TITLE
Prevent wrong model / results combination

### ISSUE THREAD

**Issue by jackieleng** [nens/threedi-results-analysis#72]
When switching and loading models using the result dialogue people often forget they're still in the old directory and will often just click on load and on e.g. 'subgrid_map.nc', and unknowingly loading an incorrect model-datasource combination. It might be helpful to analyse the path of the files and give a warning when loading from very different paths.

LOW PRIO.

**Comment by leendertvanwolfswinkel** [comment]
Should be solved in a more fool-proof way, i.e. add some sort of model id to the result files (gridadmin, results, aggregate results). @Jonasvsl is anything like this planned?

**Comment by leendertvanwolfswinkel** [comment]
Will no longer be relevant after v3.0
