### ISSUE TITLE
Unclear feedback about "Skipping setting project CRS"

### ISSUE THREAD

**Issue by leendertvanwolfswinkel** [nens/threedi-results-analysis#720]
When loading the Fuerthen grid ([gridadmin.zip](https://github.com/nens/ThreeDiToolbox/files/10097117/gridadmin.zip)), I get this message:

```
GeoPackage: Skipping setting project CRS - the source file C:\Users\leendert.vanwolfswin\OneDrive - Nelen & Schuurmans\Documents 1\3Di\fuerthen_de - fuerthen_fuerthen (1)\revision 16\results\sim_89864_Fuerthen_rev16_no_rain_24h\gridadmin.gpkg SRS codes are inconsistent.
```
I don't understand what why it says so and what I should do with this information. 

I don't think we should try to set the project crs at all when loading the geopackage. If it is the first thing the user adds to the project, QGIS will do this automatically; if not, we can assume the user has already added data with a crs that fits the project area. 

- [ ] Remove the code for setting project crs and warnings when this is not possible, unless there is some important reason for this that I am missing

**Comment by benvanbasten-ns** [comment]
@leendertvanwolfswinkel This CRS checking code was/is also present in the result_analysis processing algorithm... Should we omit it in the Results Manager?

**Comment by leendertvanwolfswinkel** [comment]
Please remove it from both implementations. Please also take into account my earlier comment "I don't think we should try to set the project crs at all when loading the geopackage."

**Comment by benvanbasten-ns** [comment]
@leendertvanwolfswinkel Does threedigrid's GeopackageExporter then set a CRS in the Geopackage? or is this something the user needs to do in the project?

**Comment by leendertvanwolfswinkel** [comment]
Each layer in the geopackage should have a CRS assigned. I think this is already the case. If not, this should be fixed in the GeopackageExporter. 

Another thing is the QGIS Project CRS - we do not need to do anything with that. I had the impression that currently, the tool(s) try to set the project CRS, but this is not necessary.
