### ISSUE TITLE
Add dialog for adding grids/results from the 3Di working directory

### ISSUE THREAD

**Issue by leendertvanwolfswinkel** [nens/threedi-results-analysis#721]
Currently, when clicking the `+` button, a file selector dialog opens to select a gridadmin.h5 file. And there is a separate button for adding results. 

I would like to make loading results from the 3Di working directory (the one that users set in the settings of the Models & Simulations plugin) the default / happy path, while loading from a custom location remains as a secondary option. 

My proposal how we could do this: have a single `+` button, and when it is clicked, a dialog appears that looks more or less like this (sorry for the horrible powerpoint/paint drawing):

![image](https://user-images.githubusercontent.com/26224299/204111078-54e7ef7c-e774-4bf8-8ee6-ce262d599e8e.png)

FYI The top part of the window is taken from the Models & Simulations plugin 'Load local schematisation' dialog; perhaps borrowing / sharing some code would be helpful.

@gijs please provide feedback / alternative ideas as you see fit

**Comment by gijs** [comment]
Door Corona en vakantie is het er nog niet van gekomen om hiernaar te kijken. Indien nog relevant, kunnen we het er na de lunch even over hebben @leendertvanwolfswinkel ?

**Comment by gijs** [comment]
Just discussed this with @leendertvanwolfswinkel 
I'll create a mockup of what we discussed

**Comment by gijs** [comment]
Just discussed this with @leendertvanwolfswinkel 
I'll create a mockup of what we discussed

**Comment by gijs** [comment]
It's a start, but can you [take a look at this](https://www.figma.com/file/U5KH82heuwdFW0hYBwwTNx/3Di-Results-Manager?node-id=514%3A101&t=yga6pW6UbNnzPo7d-1) @leendertvanwolfswinkel ? thx!

**Comment by leendertvanwolfswinkel** [comment]
Hi @gijs, looks nice & clean. I commented in Figma. I also did this in Paint for the Browse tab:

![Browse.png](https://images.zenhubusercontent.com/62bedb7b667872a01ff3bdff/147a0212-1066-4a79-ba85-1af149a4fa4f)

**Comment by gijs** [comment]
Will add that, thanks and see you in a second

**Comment by leendertvanwolfswinkel** [comment]
@benvanbasten-ns Please use a `QgsFileWidget` instead of a text input + browse button

**Comment by benvanbasten-ns** [comment]
- [ ] Check whether (same) grid is already loaded for other result
