### ISSUE TITLE
"Computational grid from h5 file": use file as input instead of containing folder

### ISSUE THREAD

**Issue by leendertvanwolfswinkel** [nens/threedi-results-analysis#722]
The 'computational grid from h5 file' processing algorithm now asks users to select the folder that contains the h5 file, instead of the file itself. We made this choice because Radek and @ldebek couldn't get it to work otherwise (i.e. not without large time investments or hacky workarounds). I noticed that the new Results Manager does this without problems. Is it possible to use the same trick for the processing algorithm?

**Comment by benvanbasten-ns** [comment]
User should now be able to select specific h5 file (and no longer needs to select directory)
