### ISSUE TITLE
Do not set default inputs for "Computational grid from schematisation" processing algorithm

### ISSUE THREAD

**Issue by leendertvanwolfswinkel** [nens/threedi-results-analysis#723]

**Comment by benvanbasten-ns** [comment]
Default input is no longer saved or set.

**Comment by leendertvanwolfswinkel** [comment]
This is on the `refactor` branch?

**Comment by benvanbasten-ns** [comment]
yes, generally, issue for this epic (toolbox 3.0) are on "refactor" branch

**Comment by leendertvanwolfswinkel** [comment]
My wording was a bit too specific I think. I meant that none of the widgets should be prepopulated. Now the "output computational grid file" still 'remembers' its value: 

![image.png](https://images.zenhubusercontent.com/62bedb7b667872a01ff3bdff/2ac3af52-a20d-4b19-b572-09c6d123885c)

**Comment by leendertvanwolfswinkel** [comment]
My wording was a bit too specific I think. I meant that none of the widgets should be prepopulated. Now the "output computational grid file" still 'remembers' its value: 

![image.png](https://images.zenhubusercontent.com/62bedb7b667872a01ff3bdff/2ac3af52-a20d-4b19-b572-09c6d123885c)

**Comment by benvanbasten-ns** [comment]
@leendertvanwolfswinkel #uvraagtwijdraaien

**Comment by leendertvanwolfswinkel** [comment]
Same applies to "Computational grid from h5 file"
