### ISSUE TITLE
Consistent code structuring in /processing

### ISSUE THREAD

**Issue by leendertvanwolfswinkel** [nens/threedi-results-analysis#724]
All algorithms in ThreeDiToolbox\processing are contained in {category}_algorithms.py, except for the computational grid algorithms, which are located in ThreeDiToolbox\processing\results_analysis. Should we make this consistent or is there a good reason not to?

**Comment by benvanbasten-ns** [comment]
Had a look, I don't think it has any particular reason except for tidiness. Made everything consistent

**Comment by arjanverkerk** [comment]
> Had a look, I don't think it has any particular reason except for tidiness. Made everything consistent

Me too.
