### ISSUE TITLE
Add schema version check to import sufhyd

### ISSUE THREAD

**Issue by leendertvanwolfswinkel** [nens/threedi-results-analysis#726]
Import Sufhyd and Import HydX should check the schema version of the target spatialite before starting the import. If the schema version is too low, user should be informed about this with the following message:

"The selected 3Di spatialite does not have the latest database schema version. Please migrate this spatialite and try again: Processing > Toolbox > 3Di > Schematisation > Migrate spatialite"

**Comment by arjanverkerk** [comment]
I added a check for the sufhyd import, but don't know where the gwsw-hyd import happens, or is that the same thing?

Edit: never mind, I see it is still in review.
