### ISSUE TITLE
modelchecker installs on every startup

### ISSUE THREAD

**Issue by Jonasvsl** [nens/threedi-results-analysis#729]
It doesn't take long, but it's not how it should be

![MicrosoftTeams-image (23)](https://user-images.githubusercontent.com/1453159/205059500-d6192afa-3746-4417-ae3b-b9af0904d62d.png)

Happens with this version:
https://docs.3di.live/modeller-interface-downloads/3DiModellerInterface-OSGeo4W-3.22.13-2-1-Setup-x86_64.exe

**Comment by benvanbasten-ns** [comment]
@leendertvanwolfswinkel this seems to be a 3DiToolbox issue. Could you move it to the relevant epic and project?

**Comment by benvanbasten-ns** [comment]
@leendertvanwolfswinkel Fixed on master branch
