### ISSUE TITLE
Upgrade threedi dependencies

### ISSUE THREAD

**Issue by leendertvanwolfswinkel** [nens/threedi-results-analysis#735]

**Comment by leendertvanwolfswinkel** [comment]
- [x] Bump threedi-modelchecker to == 1.0.0
- [x] Bump threedigrid-builder to 1.8.0
- [x] Include new package `threedi-schema==0.214.3`
- [x] Upgrade required schema version to 214

**Comment by ldebek** [comment]
@leendertvanwolfswinkel Currently schema version was upgraded with a threedi-modelchecker `ModelSchema.upgrade()` method. Is this workflow still valid? And if not - what is the desired way to validate schema and upgrade it if needed?

**Comment by leendertvanwolfswinkel** [comment]
See https://github.com/nens/threedi-schema#example

**Comment by ldebek** [comment]
@leendertvanwolfswinkel It seems that threedi-schema requires `alembic `and `SQLAlchemy`, so I have to ship it with plugins as well, right?

**Comment by ldebek** [comment]
@leendertvanwolfswinkel PR with requested changes: https://github.com/nens/ThreeDiToolbox/pull/762
