### ISSUE TITLE
Connect Graph Tool to 3Di Results Manager

### ISSUE THREAD

**Issue by leendertvanwolfswinkel** [nens/threedi-results-analysis#751]
- [x] Make independent from spatialite / gridadmin.sqlite
- [x] Make map tool for adding flowlines and pumps to the plot window. The map tool is accessible through a button on the Graph Tool dock panel
- [x] Make map tool for adding nodes to the plot window. The map tool is accessible through a button on the Graph Tool dock panel
- [x] Rename the 'H graph' tab to 'Nodes'
- [x] Rename the 'Q graph' tab to 'Flowlines & pumps'.  
- [x] When a results set is removed, the corresponding timeseries are removed from the plot
- [x] Requirement: can visualize timeseries for all variables present in the netcdf
- [x] Requirement: can visualize timeseries data for all types of flowlines and nodes, including embedded/breaches/pump

**Comment by Patrick-Nijman** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Modeller-Interface-61e574104cc38a001fb287de/issues/nens/ThreeDiToolbox/751?planning-poker) with Zenhub @arjanverkerk @benvanbasten-ns

**Comment by benvanbasten-ns** [comment]
- [x] when last result of grid is removed (and it was checked), the styling is not reverted
- [x] graph_view independently connects to Qt model signal, should use our defined signals for improved flow
- [x] ~Caching is currently based on result_item text, which can be changed by the user~ Changed to uuid
- [x] Resolve when results have different variables (intersection of all params)
- [x] Graph is not cleared when global "New Project" button is pressed
