### ISSUE TITLE
Graph Tool: improve legend

### ISSUE THREAD

**Issue by leendertvanwolfswinkel** [nens/threedi-results-analysis#752]
- [x] Multiple results for the same feature (e.g. T10, T25, T100 for flowline id 23) should have the same color & different dash/dot pattern
- [x] Legend should show for each line in the plot: which computational grid, which flowline/node/pump id, user-definable label for that feature, and which simulation result 
- [x] Option to change color and label for each flowline/node/pump

**Comment by Patrick-Nijman** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Modeller-Interface-61e574104cc38a001fb287de/issues/nens/ThreeDiToolbox/752?planning-poker) with Zenhub @arjanverkerk @benvanbasten-ns
