### ISSUE TITLE
Visualize all flowlines and nodes in animation

### ISSUE THREAD

**Issue by benvanbasten-ns** [nens/threedi-results-analysis#757]
Currently, not all flowlines (and maybe nodes) are visualized during animation when their corresponding results are small:

```
                <Option name="enabled" type="Map">
                  <Option name="active" type="bool" value="true"/>
                  <Option name="expression" type="QString" value="abs(result) > 0"/>
                  <Option name="type" type="int" value="3"/>
                </Option>
```

```
                    <Option name="enabled" type="Map">
                      <Option name="active" type="bool" value="true"/>
                      <Option name="expression" type="QString" value="($length /  @map_scale) > 0.0025 AND abs(result) > 0"/>
                      <Option name="type" type="int" value="3"/>
                    </Option>
```

This makes selecting these feature more difficult.

**Comment by benvanbasten-ns** [comment]
@leendertvanwolfswinkel Some stylings disable features when they are too small. In that case selecting them is difficult. 

Obviously we can remove this from the styling, but would you know of a better idea?

**Comment by leendertvanwolfswinkel** [comment]
I think the best solution would be:
- Use a threshold value (different flow variables should have different thresholds)
- When defining the bins, only use the values >= threshold
- Style all flowlines/nodes with values < threshold as a thin grey line/dot

**Comment by leendertvanwolfswinkel** [comment]
Related: Results manager: use legend subgroups when visualising results#769

**Comment by arjanverkerk** [comment]
Some things fixed:
- Include the bottom level in all s1 cases
- Use dmax for the bottom_level, instead of z_coordinate
- Small optimizations / simplifications in the array operations
