### ISSUE TITLE
Results Manager: Activate the temporal controller when results are loaded

### ISSUE THREAD

**Issue by leendertvanwolfswinkel** [nens/threedi-results-analysis#768]

**Comment by arjanverkerk** [comment]
@leendertvanwolfswinkel it is now activated when a result gets checked (that is also when the timerange is adjusted to include all checked results). Is that acceptable?

**Comment by leendertvanwolfswinkel** [comment]
@arjanverkerk Is is also possible to _show_ the temporal controller when a result gets checked?

**Comment by arjanverkerk** [comment]
Yes! Just pushed that.
