### ISSUE TITLE
UNDO Results manager: use legend subgroups when visualising results

### ISSUE THREAD

**Issue by leendertvanwolfswinkel** [nens/threedi-results-analysis#769]
Using legend subgroups (see image below) would allow us to make several improvements.
![image.png](https://images.zenhubusercontent.com/62bedb7b667872a01ff3bdff/862c0a58-369e-41fc-85d0-d25f4f8be765)

- We can apply separate classifications for groundwater and surface water, which is important because these are two very separate value distributions
- We give users more easy control over which subset of flowlines or nodes they want to visualise
- It is easier to find the Node of Flowline layer when they are not renamed all the time

Subgroups:
_Node layer_
1D
2D Surface water
2D Groundwater

_Cell layer_
2D Surface water
2D Groundwater

_Flowline layer_
1D
1D2D Surface water
2D Surface water
1D2D Groundwater
2D Groundwater
Vertical

**Comment by arjanverkerk** [comment]
Subgroups are now created, but groundwater classification remains to be applied to appropriate subgroups.

**Comment by arjanverkerk** [comment]
Performance on the machine of @benvanbasten-ns is very poor for unknown reasons. The sublegends are now disabled by default and added an option to enable them. Run this code in the python console to enable the setting:
```
from qgis.core import QgsSettings
from threedi_results_analysis.utils.constants import TOOLBOX_QGIS_SETTINGS_GROUP
QgsSettings().setValue(
    TOOLBOX_QGIS_SETTINGS_GROUP + "/animationSublegends", True
)

```
Not implementing seperate class bounds for ground- and surface water at this moment.

**Comment by leendertvanwolfswinkel** [comment]
It is unfortunate that this implementation is not performant, but I don't see how we can make it perform. Please remove this. I will make a new design to allow users to do the same things, but in a different way.
