### ISSUE TITLE
Results manager: results_3di.nc cannot be opened if it is in a directory with special character

### ISSUE THREAD

**Issue by leendertvanwolfswinkel** [nens/threedi-results-analysis#782]
E.g. if the path to the results file is  `C:\Temp\Méandre de quille\results_3di.nc`, it will not be possible to add the results to the project

**Comment by benvanbasten-ns** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Modeller-Interface-61e574104cc38a001fb287de/issues/nens/ThreeDiToolbox/782?planning-poker) with Zenhub @arjanverkerk
