### ISSUE TITLE
3Di Results Manager: UI finishing touch

### ISSUE THREAD

**Issue by leendertvanwolfswinkel** [nens/threedi-results-analysis#785]
Results manager panel as a whole should be as simple as possible and have the same look & feel as the 3Di Models & Simulations panel.

@gijs could you please make a Figma design for this? I guess you still have the 3Di Models & Simulations design somewhere. Please let me know if you need me to clarify anything in a meeting. 

This is what the 3Di Models & Simulations panel looks like:
![image](https://user-images.githubusercontent.com/26224299/220454006-48890a92-0989-4200-8bcd-5321c7e97c78.png)

This is the current design of the 3Di Results Analysis panel:
![image](https://user-images.githubusercontent.com/26224299/220454462-e92f3e5e-6cdd-4b7b-9406-b2f9c12145df.png)

**Comment by gijs** [comment]
Yes, putting it on my agenda for this week @leendertvanwolfswinkel

**Comment by gijs** [comment]
@leendertvanwolfswinkel Can you give feedback on the WIP in [this Figma project](https://www.figma.com/file/U5KH82heuwdFW0hYBwwTNx/3Di-Results-Manager?node-id=764%3A103&t=SLdV1h5vMcn1iPLm-1)?

Thx!

**Comment by benvanbasten-ns** [comment]
@leendertvanwolfswinkel What do you think?

**Comment by gijs** [comment]
Can you answer also in the [Figma page](https://www.figma.com/file/U5KH82heuwdFW0hYBwwTNx/3Di-Results-Manager?node-id=764-103)? I forgot to tag you with your actual username, so you might never have gotten a Figma notification.. maybe now you do? 🙈

![Screenshot 2023-03-17 at 15 06 22](https://user-images.githubusercontent.com/7193/225927844-625dd7ca-2ac8-4fe7-a053-c7993b8cd87b.png)

**Comment by benvanbasten-ns** [comment]
@gijs @leendertvanwolfswinkel I would like to suggest to redesign the M&S plugin instead, and keep the look&feel of our plugins close to the native QGIS look&feel.
