### ISSUE TITLE
Graph tool: let map tools use all layers, not just the top one

### ISSUE THREAD

**Issue by leendertvanwolfswinkel** [nens/threedi-results-analysis#787]
De graph tool selecteert alleen results uit de bovenste layer. Eigenlijk moeten we ze allemaal selecteren

**Comment by benvanbasten-ns** [comment]
- [ ] Only select up to 1 feature per grid (@arjanverkerk)
- [ ] Show warning when #features > 20 (@arjanverkerk)
- [x] Only set name for feature with same id (and same grid)
