### ISSUE TITLE
Graph Tool: do not select features when adding them to the plot

### ISSUE THREAD

**Issue by leendertvanwolfswinkel** [nens/threedi-results-analysis#792]
The current map tool for adding results for nodes to the plot also adds the clicked nodes to the selection. This is not necessary and potentially confusing.

**Comment by leendertvanwolfswinkel** [comment]
The graph layer map tool still affects the selection. E.g. if this is the situation before I use the "Add nodes" map tool (9 Selected nodes):
![image.png](https://images.zenhubusercontent.com/62bedb7b667872a01ff3bdff/64d56088-127e-4b69-8677-677e9b729a59)

This is the situation after I click on a node using the 'Add nodes' map tool:
![image.png](https://images.zenhubusercontent.com/62bedb7b667872a01ff3bdff/578fc64a-93fc-4617-9377-e5709c36ee2a)

**Comment by Patrick-Nijman** [comment]
Moet nog getest worden
