### ISSUE TITLE
3Di Toolbox Compatibility with schema version 216

### ISSUE THREAD

**Issue by leendertvanwolfswinkel** [nens/threedi-results-analysis#797]
- [x] bump the version of threedi_modelchecker to version ???
- [x] bump the version of threedi-schema to 0.216.* 
- [x] bump the version of hydxlib to ???
- [x] set the minimum required schema version to 216
- [x] check if import hydx still works (add automated test?)
- [x] check if import sufhyd still works (add automated test?)

**Comment by arjanverkerk** [comment]
What about the tests? Hydxlib tests hydx import / export to the latest schema on its own. So I would think that is not needed. There appear to be some sufhyd read tests that do not run in the plugin codebase, but they appear very outdated and not in a usable state. So no automated tests for that one. I tried to import `HWA_Borax.hyd` that was on my machine somewhere, fixed some sqlalchemy deprecations and then it completed with a number of warnings and errors, but at least it did not crash.

**Comment by leendertvanwolfswinkel** [comment]
@arjanverkerk has this been implemented on `master` as well as `refactor` branches?

**Comment by arjanverkerk** [comment]
We're aiming for schema 214 in #793 as far as master is concerned.

**Comment by leendertvanwolfswinkel** [comment]
Please also implement on master
