### ISSUE TITLE
Create and implement threedi-mi-utils

### ISSUE THREAD

**Issue by leendertvanwolfswinkel** [nens/threedi-results-analysis#805]
The 3Di Models & Simulations plugin uses a working directory with a fixed structure. This dir is used for uploading/downloading schematisations and simulation results.

For users, it is much more convenient if the 3Di Schematisation Editor and the 3Di Results Analysis plugin all use the same working directory, for easy access to available schematisations, computational grids and simulation results. In the future, this will also apply to the (3Di) Scenario Archive plugin.

To make sure all plugins access this working directory in the same way, without duplicating code between them, the code for dealing with this working directory should be managed in a separate python package, `threedi-mi-utils`. 

Tasks:
- [x] Create a new repo `threedi-mi-utils`
- [x] Move code from 3Di Models & Simulations (`threedi-qgis-api-client`) and 3Di Results Analysis (`ThreeDiToolbox`, `refactor` branch)
- [x] Publish this as a package on PyPI
- [x] Include this package as a dependency of 3Di Models & Simulations and 3Di Results Analysis

**Comment by leendertvanwolfswinkel** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Modeller-Interface-61e574104cc38a001fb287de/issues/nens/ThreeDiToolbox/805?planning-poker) with Zenhub @ldebek

**Comment by leendertvanwolfswinkel** [comment]
@ldebek  3Di Models & Simulations plugin seems to work fine, tested a few things like create new schematisation, download schematisation.

3Di Results Analysis / `ThreeDiToolbox` does not work though. I get the following error at startup:

```
AttributeError: 'LocalRevision' object has no attribute 'results_dirs' 
Traceback (most recent call last):
  File "C:\PROGRA~1/3DIMOD~1.28/apps/qgis-ltr/./python\qgis\utils.py", line 448, in startPlugin
    plugins[packageName].initGui()
  File "C:\Users\leendert.vanwolfswin\AppData\Roaming\3Di\QGIS3\profiles\From the developers desk/python/plugins\threedi_results_analysis\threedi_plugin.py", line 109, in initGui
    self.dockwidget = ThreeDiPluginDockWidget(None, iface)
  File "C:\Users\leendert.vanwolfswin\AppData\Roaming\3Di\QGIS3\profiles\From the developers desk/python/plugins\threedi_results_analysis\gui\threedi_plugin_dockwidget.py", line 63, in __init__
    self.dialog = ThreeDiPluginGridResultDialog(self)
  File "C:\Users\leendert.vanwolfswin\AppData\Roaming\3Di\QGIS3\profiles\From the developers desk/python/plugins\threedi_results_analysis\gui\threedi_plugin_grid_result_dialog.py", line 66, in __init__
    self.refresh()
  File "C:\Users\leendert.vanwolfswin\AppData\Roaming\3Di\QGIS3\profiles\From the developers desk/python/plugins\threedi_results_analysis\gui\threedi_plugin_grid_result_dialog.py", line 207, in refresh
    for result_dir in local_revision.results_dirs:
AttributeError: 'LocalRevision' object has no attribute 'results_dirs'
```

**Comment by ldebek** [comment]
@leendertvanwolfswinkel Changes pushed - your issue should be fixed now.

**Comment by leendertvanwolfswinkel** [comment]
@ldebek  I don't get errors anymore, but it does not work correctly. This is the list of simulation results in the version of 3Di Results Analysis with `threedi-mi-utils`: 

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNjZpQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--bd07bce5815aeb7d4b47019215277560e6d9a43f/image.png)

And this is the same dialog with the production version:

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNitpQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7a7be87aad2f945da83d7c358240508a68b0743a/image.png)

**Comment by ldebek** [comment]
@leendertvanwolfswinkel It turned out that there were changes in a working dir logic within 3Di Results Analysis, so I had to merge those changes with 3Di MI Utils repo. New version of the plugin should display complete list of availalble schematisation. Feel free to give it an another test round :)

**Comment by leendertvanwolfswinkel** [comment]
I tested it, works as expected now. But I would like @benvanbasten-ns to review the ThreeDiToolbox PR before we release it
