### ISSUE TITLE
Sideview: show user that the sideview is being made 

### ISSUE THREAD

**Issue by leendertvanwolfswinkel** [nens/threedi-results-analysis#814]
After the user has added a point to the sideview trajectory, it may take some time before the sideview shows up. The user should see that something is happening, e.g. a progress bar or a 'something is going on' bar

**Comment by benvanbasten-ns** [comment]
![image](https://github.com/nens/ThreeDiToolbox/assets/97883955/863a795e-ea90-49c3-b431-3da51a950961)
