### ISSUE TITLE
Graph tool: default variable for pump should be 'discharge pump'

### ISSUE THREAD

**Issue by leendertvanwolfswinkel** [nens/threedi-results-analysis#819]
When adding a pump to an empty flowlines/pump plot, set variable to Discharge pump instead of Discharge

**Comment by leendertvanwolfswinkel** [comment]
I added a pump to the plot, but I can't even select 'Discharge pump' from the dropdown menu: ![image.png](https://images.zenhubusercontent.com/62bedb7b667872a01ff3bdff/0f0e8af2-7122-4c96-86b8-6f9af774b0fa)

**Comment by benvanbasten-ns** [comment]
Problem is that Graph Tool shows intersection of lists of parameters in results. In your particular case one of the results did not contain "Discharge Pump" so it was not added to the combobox. 

Don't take intersection but union. Showing nothing in case a result does not contain a specific param.

**Comment by benvanbasten-ns** [comment]
@leendertvanwolfswinkel  Preferable test with results containing different parameters (pumps, for example)
