### ISSUE TITLE
Result manager: add "align simulation start times" option

### ISSUE THREAD

**Issue by leendertvanwolfswinkel** [nens/threedi-results-analysis#823]
Example: user has loaded two simulation results, A and B. simulation A starts at `2000-01-01 00:00`, simulation B starts at `2023-05-11 14:09`. The user wants to compare the simulations in the sideview tool or map canvas visualisation. To make this possible, the user should be able to override the simulation start datetime of simulation B and set it to `2000-01-01 00:00`.

This override is probably what users want in 90% of cases.

Proposed implementation:
- [x] Add a checkbox to the result manager "Align simulation start times". It is checked by default, i.e. opt-out.
- [x] Tooltip of the checkbox and its label should be "Let all simulation use the start time of the simulation that starts first"
- [x] If it is checked, use the start time of the first-starting simulation instead of reading it from the NetCDF
- [x] Make sure that all tools that use the simulation start time get it from the results manager instead of retrieving it from the NetCDF themselves
- [x] Results Manager: show time since start of simulation for all result sets. now it is just for the ones for which the 'visualise on map canvas'

@benvanbasten-ns please add requirements/info as you see fit

- [ ] Provide global utility function that converts temporal controller time to result (netcdf) index.

PS. I would call the option "Ignore temporal offset"

**Comment by benvanbasten-ns** [comment]
@leendertvanwolfswinkel @arjanverkerk I would call the option "Ignore temporal offset"

**Comment by leendertvanwolfswinkel** [comment]
I wouldn't

**Comment by arjanverkerk** [comment]
Until now we only based the temporal controller range on _visualized_ results - but I will change that into _all_ loaded results, so that other-than-animation tools also have access to an appropriate timeline.

**Comment by arjanverkerk** [comment]
Most logic is now in a TemporalManager. It takes care of updating a `timedelta` for each result that respresents the simulation time "local" to that result. Tools such as sideview and map animation use that get their temporal data.
