### ISSUE TITLE
Graph/Sideview: unset map tool when tab is switched

### ISSUE THREAD

**Issue by benvanbasten-ns** [nens/threedi-results-analysis#824]
When the user:

- is adding data to Tab 1 via the maptool,
- switches to Tab 2,
- clicks to add additional data,

The data will not be added to Tab 2, but to Tab 1, as the map tool of that tab is still active. To prevent confusion the maptool should be disabled when the user switches tabs

@leendertvanwolfswinkel Please add functionality if you see fit.

**Comment by leendertvanwolfswinkel** [comment]
Sounds good to me
