### ISSUE TITLE
Add processing algorithm Maximum Waterdepth

### ISSUE THREAD

**Issue by leendertvanwolfswinkel** [nens/threedi-results-analysis#827]
Implementation depends on addition of this feature to `threedidepth`

**Comment by leendertvanwolfswinkel** [comment]
Other things needed to make this work:
- [x] release threedigrid as version 0.6.1
- [x] bump threedigrid to 0.6.1 in ThreeDiToolbox dependencies.py
- [x] make PR to trigger github action that generates zip file of new 3Di Toolbox plugin

**Comment by elisalle** [comment]
Threedigrid 0.6.0 has been released on GitHub, but the package is registered on PyPi under Arjan's name, so unfortunately I can't release it there. @arjanverkerk would you be able to add nens (https://pypi.org/user/nens/) and reinout (https://pypi.org/user/reinout/) as a maintainer?

edit: thanks for adding

**Comment by Jonasvsl** [comment]
@elisallenens does the documentation also need to be updated with the new possibility to create a max waterdepth ?
https://threedigrid.readthedocs.io/en/latest/history.html

**Comment by Jonasvsl** [comment]
I'm looking for more information on how to use the max water depth algorithm. Can you help me with that?

**Comment by elisalle** [comment]
@Jonasvsl Sure.
It's almost a copy of the normal waterdepth tool, so you open the Processing Toolbox sidebar in QGIS (top bar > Processing > Toolbox), go to 3Di > Post-process results > Maximum water depth/level raster
Click on that, and a window opens, where you can fill in the paths to gridadmin.h5, results_3di.nc, the DEM, and the destination file path for the water depth/level raster.
In the Interpolation mode dropdown (which should perhaps be named differently), you can choose what to calculate;
- interpolated water depth
- interpolated water level
- non-interpolated water depth
- non-interpolated water level.

Then click Run, and a raster with the calculation results will be written to the output path you specified.

**Comment by leendertvanwolfswinkel** [comment]
@Jonasvsl  Not sure if this is what you mean, but user manual for these tools is available here: https://docs.3di.live/i_water_depth_level_rasters.html
