### ISSUE TITLE
Graph: pump can be added both as line feature and as node feature

### ISSUE THREAD

**Issue by benvanbasten-ns** [nens/threedi-results-analysis#829]
This causes the same info to potentially be added to the graph twice.

Only add pump line features

@leendertvanwolfswinkel 

![MicrosoftTeams-image.png](https://images.zenhubusercontent.com/61e6a23133cb1e468595d74d/7b8ab562-22e8-451b-b58b-1c9d9b47630c)

**Comment by leendertvanwolfswinkel** [comment]
This implementation is not correct. Now, if a pump does not have an end node (i.e. there will be no line, only a point feature), users won't be able to add them to the plot. I think this is just another case of 'the same objects cannot be added to the plot twice'.

**Comment by benvanbasten-ns** [comment]
- [x] Add internal test that pump can not be added both as point or line feature.
- [x] Add internal test that node cannot be added both as node or cell (not the case for all nodes, only 2D)
