### ISSUE TITLE
Compatibility with schema 217

### ISSUE THREAD

**Issue by leendertvanwolfswinkel** [nens/threedi-results-analysis#830]
- [x] bump the version of threedi_modelchecker to version 2.2.0
- [x] bump the version of threedi-schema to 0.217.* 
- [x] bump the version of hydxlib to 1.5.1
- [ ] ~set the minimum required schema version to 217~
- [x]  bump the version of threedigrid-builder to at least 1.11.4 _(added by @arjanverkerk)_
	
*CHANGES SHOULD BE APPLIED TO BOTH `MASTER` AND `REFACTOR` BRANCHES*

**Comment by leendertvanwolfswinkel** [comment]
@arjanverkerk  threedi_modelchecker 2.1.2 has not yet been released. Will be done a.s.a.p. (waiting for review by @caspervdw)

**Comment by leendertvanwolfswinkel** [comment]
@arjanverkerk  The new version of the threedi_modelchecker has been released now, but as 2.2.0, not as 2.1.2

**Comment by leendertvanwolfswinkel** [comment]
@arjanverkerk A yet newer version of the threedi_modelchecker will be released today (2.2.1)

**Comment by arjanverkerk** [comment]
`threedigrid-builder` is not included in your list. Is that OK?
Does "set the minimum required schema version to 217" require a separate action on top of bumping threedi-schema?

**Comment by leendertvanwolfswinkel** [comment]
`threedigrid-builder` should be bumped to the most recent version as well
Your second question: I don't think so

**Comment by arjanverkerk** [comment]
Bumped threedigrid-builder as well.
