### ISSUE TITLE
Sideview: small issues

### ISSUE THREAD

**Issue by leendertvanwolfswinkel** [nens/threedi-results-analysis#837]
- [x] SideView: automatically activate first simulation result in 'grid' dropdown menu when opening the sideview plot panel
- [x] SideView: change y axis label from "Height (m NAP)" to Height (m MSL)"
- [x] SideView: draw lines at bottom and top of cross section *over* the water fill
- [x] SideView: if you reset sideview trajectory, the yellow 'tree' layer, marking the possible places you can go to, should disappear. same for when 'choose sideview trajectory' is de-activated
- [x] SideView: once user has started drawing the trajectory, change name of the button from "Choose SideView trajectory" to "Continue SideView trajectory". Change it back when user clicks "Reset sideview trajectory"
- [x] SideView: please make the water fill 50% darker but 50% transparent, so that it is easier to see the difference when comparing two results
- [x] SideView: loading takes a long time; it is a known issue that each data request to the netcdf has quite a bit of overhead; it is usually much faster to request all data (perhaps too much data) in one request and store it in e.g. a dict, than to request all data points separately.

**Comment by benvanbasten-ns** [comment]
- [ ] SideView: make water levels react to temporal controllor also when its box in the results manager is not checked. this issue occurs when in the results manager, the result has never been activated. once it has been activated, it keeps working (also after de-activating it)

@leendertvanwolfswinkel Probably because results are not temporally aligned (see #823)

**Comment by benvanbasten-ns** [comment]
SideView: draw lines at bottom and top of cross section over the water fill

Water fill has z-value of 0 (lowest, so it is drawn first). I changed the default z-values of the other plots to 10. So everything should now be drawn over the water fill.
