### ISSUE TITLE
Time series plotter: small issues

### ISSUE THREAD

**Issue by leendertvanwolfswinkel** [nens/threedi-results-analysis#839]
- [x] Time series plotter: when you click on a 2D node (i.e. where a cell is also present), the node should be added only once. More generally, it should not be possible to add the same object twice
- [x] Time series plotter: Add some spacing between the buttons / widgets at the top of the panel
~- [ ] Time series plotter: When I open a new plot window and I do *not* change the variable to something other than the default "Net cumulative discharge", I get really weird plot for my Meerssen model~
-> This seems to be a problem in the file. q_cum seems to contain weird results, see below
- [x] Remove DELETE button

**Comment by benvanbasten-ns** [comment]
Directly reading the aggregate netcdf via threedigrid/GridH5AggregateResultAdmin (ga.lines.filter(id=bla).q_cum also shows these weird values:

@leendertvanwolfswinkel  I think this is a backend issue

![image](https://github.com/nens/ThreeDiToolbox/assets/97883955/799787d2-ab72-4f50-9e4a-56725825571a)
