### ISSUE TITLE
Result aggregation: add preset "Water on street duration"

### ISSUE THREAD

**Issue by leendertvanwolfswinkel** [nens/threedi-results-analysis#845]
By far the most used feature of the 'old' Statistics tool is generating a layer that shows how long the water level in each manhole is on the street.

How we define 'on the street' needs some thought. For models without 2D (`has_2d` in model meta is `False`), the manhole `drain_level` can be used for this. For models with 2D, it is a bit more complicated:
- If the manhole calculation type is _Isolated_, there can not be any water on the street; these manholes should be ignored.
- If the manhole calculation type is _Connected_, water is 'on the street' when the lowest 1D-2D exchange level is reached. This 1D-2D exchange level is not a property of the node/manhole, but of the 1D-2D flowlines that connect to it. I am not sure if the `drain_level` property of the node is the drain_level that was filled in by the user (attribute of the manhole feature), or if it is actually the lowest exchange level of all 1D-2D flowlines connected to the node.

Things that need to be done to include this in the Result aggregation tool:
- [x] Expand the possibilities of the aggregation method "time above threshold". Currently, only a global value can be used as threshold. It should also be possible to use a property of the node or flowline as threshold.
- [x] Check with @jpprins1 or @caspervdw what the value of the drain_level (dpumax?) in the gridadmin means exactly. This may be a bit tricky, because I think this value might be filled in by `threedigrid-builder`, to be updated later by `threedi-tables` 
- [x] Filtering / subsetting: allow users to limit the aggregation to nodes with `is_manhole = True`. May be easier to include this in the styling instead, but that requires that this attribute is included in the output layer.
- [ ] Make a styling (qml) file and python function to load that style
- [x] Define a preset 'Water on street duration'

**Comment by arjanverkerk** [comment]
Just discussed with @leendertvanwolfswinkel - We want to know, for models with 2D, if the drain_level that ends up on the manholes in the gpkg is the _actual exchange level used in the calculation_, so not only the lowest exchange level of connected 1D2D lines. What do you think @caspervdw ?

**Comment by caspervdw** [comment]
The actual exchange level used in the calculation is the “dpumax” dataset on the “lines” group in the gridadmin.  

The source of this column is a piece of rather complex logic in threedigrid_builder.Grid.add_1d2d_lines. It involves the manhole.drain_level. Then in threedi-tables, this level is in some cases adapted. In the end the correct value is written to the dpumax field in the gridadmin.

**Comment by arjanverkerk** [comment]
@caspervdw thanks for your part of the story. @leendertvanwolfswinkel I'll assume the dpumax is the value you are looking for and assume that this dpumax ends up in my 2d manhole drain_level. So that I can then focus on the rest of this issue. If this is not okay I expect @leendertvanwolfswinkel to undertake some further action.

**Comment by leendertvanwolfswinkel** [comment]
Correct assumptions!

Verzonden vanaf Outlook voor Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by caspervdw** [comment]
It’s the other way around: the dpumax gets filled with the manhole drain_level (amongst others). A manhole can have multiple 1D2D lines with different dpumax. For instance if one line goes over a levee.

Verzonden vanuit Outlook voor iOS<https://aka.ms/o0ukef>
________________________________
Van: leendertvanwolfswinkel ***@***.***>
Verzonden: Tuesday, June 27, 2023 9:06:31 AM
Aan: nens/ThreeDiToolbox ***@***.***>
CC: Casper van der Wel ***@***.***>; Mention ***@***.***>
Onderwerp: Re: [nens/ThreeDiToolbox] Result aggregation: add preset "Water on street duration" (Issue #845)


Correct assumptions!

Verzonden vanaf Outlook voor Android<https://aka.ms/AAb9ysg>
________________________________
