### ISSUE TITLE
Surface sources and sinks does not show in water balance tool

### ISSUE THREAD

**Issue by leendertvanwolfswinkel** [nens/threedi-results-analysis#846]
@hoanphungt 

Example data:

see Teams

This is what the flow summary says:

        "volume_due_to_surface_source_and_sink_discharges": {
            "units": "m3",
            "value": -97480.0102
        },

But this is what the water balance tool says:

<img width="1178" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMjZ5QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--99b4be65555cd60959ba6ee64df7e7af6f57e7f0/image.png" alt="image.png" />

**Comment by leendertvanwolfswinkel** [comment]
Note to self: asked Sjon for test data

**Comment by hoanphungt** [comment]
When I log the values of surface sources and sinks in the graph, I see that they are all 0 and that's why it doesn't show up in the chart. It seems logical to me and I couldn't find any issue with the code:

```
{
  'in': array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]), 
  'out': array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])
}
```

**Comment by hoanphungt** [comment]
q_sss_cum is not available in the aggregate_results_3di.nc file and that's why it's not showing up in the graph.
