### ISSUE TITLE
cumulative discharge shows something else, not sure what...

### ISSUE THREAD

**Issue by kasperlange** [nens/threedi-results-analysis#85]
The cumulative discharge graph doesn't show cumulative discharge (both for pumps and in other cases). See pictures as illustration.

Normal discharge:
![image](https://cloud.githubusercontent.com/assets/12894576/19477429/5fb0bb28-953e-11e6-99d5-b04d71dc6efd.png)

Cumulative discharge: 
![image](https://cloud.githubusercontent.com/assets/12894576/19477438/6b455bf6-953e-11e6-9334-d5cfa7d17226.png)

**Comment by jackieleng** [comment]
That's correct. The so-called "cumulative discharge"  is basically q*dt summed together for a specific time interval (the one in your aggregate.ini). So it's basically telling you the volumes for specific time intervals.

So plotting it in a graph is not very useful. The only thing it's useful for is summing all values together and getting the real cumulative volume.

**Comment by jackieleng** [comment]
TODO: to make cumulative discharge useful, we need to sum the volume values per time interval ('cumulative discharge') w.r.t. time to get a real cumulative graph.

**Comment by Jonasvsl** [comment]
out of date
