### ISSUE TITLE
Results aggregation: make variables list dynamic based on model meta

### ISSUE THREAD

**Issue by leendertvanwolfswinkel** [nens/threedi-results-analysis#851]
First do #865 

Several variables are only present in the NetCDF if the model has specific meta properties (available in the gridadmin):

- qp: `has_interflow`
- up1: `has_interflow`
- infiltration_rate_simple: `has_simple_infiltration`
- infiltration_rate_simple_mm: `has_simple_infiltration`
- intercepted_volume: `has_interception`
- intercepted_volume_mm: `has_interception`

Related issue: #857

**Comment by benvanbasten-ns** [comment]
Some models miss information for specific aggregations (infiltration, interception). This causes the specific aggregation to crash.

Disable incompatible aggregations when a model is loaded (and show a warning when a preset is selected containing incompatible aggregations)

**Comment by leendertvanwolfswinkel** [comment]
I have a model without interception, but the "Intercepted volume" options are still available from the dropdown
![image.png](https://images.zenhubusercontent.com/62bedb7b667872a01ff3bdff/34a152c0-c6a2-480b-8e9e-ab93d33b96ca)

![image.png](https://images.zenhubusercontent.com/62bedb7b667872a01ff3bdff/e403479e-ee97-453d-aee5-e2d7a5d66981)
