### ISSUE TITLE
Watershed tool: Result Flowlines (1D) layer is empty for 2D models

### ISSUE THREAD

**Issue by leendertvanwolfswinkel** [nens/threedi-results-analysis#854]
The Result Flowlines (1D) layer is empty, probably related to the message 2023-06-06T21:34:06 CRITICAL Laag Result flowlines (1D) : Kon attribuut "kcu": Waarde "2d line" is geen getal niet opslaan

Test data to reproduce:

https://we.tl/t-cVVQTKncif

**Comment by benvanbasten-ns** [comment]
@leendertvanwolfswinkel 

can you upload the test data again? My model works and I cannot reproduce the errormessage either

![image](https://github.com/nens/ThreeDiToolbox/assets/97883955/7f64da9c-c3a6-4893-bdb4-f9d4d7494033)
