### ISSUE TITLE
Water balance: show only relevant flows

### ISSUE THREAD

**Issue by leendertvanwolfswinkel** [nens/threedi-results-analysis#857]
Related issue: #851

- [x] In the legend and in the plot, only show relevant items. I guess the easiest is to let this subset of legend items depend on the gridadmin meta properties:

- "2D Flow" when `has_2d`
- "2D Boundary flow" when `has_2d`
- "1D Flow" when `has_1d`
- "1D Boundary flow" when `has_1d`
- "2D Flow to 1D (domain exchange)" when `has_1d AND has_2d`
- "2D Flow to 1D" when `has_1d AND has_2d`
- "Pumps" when `has_pumpstations`
- "Rain on 2D" when `has_2d`
- "Lateral flow to 1D" when `has_1d`
- "Lateral flow to 2D" when `has_2d`
- "Simple infiltration" when `has_simple_infiltration`
- "Volume change 2D" when `has_2d`
- "Volume change 1D" when `has_1d`
- "Groundwater flow" when `has_groundwater_flow`
- "Volume change groundwater" when `has_groundwater`
- "Leakage" when `has_groundwater`
- "In/exfiltration (domain exchange)" when `has_groundwater`
- "Interception" when `has_interception`
- "0D rainfall runoff on 1D" when `has_0d`
- "Surface sources and sinks" when `has_2d`

- [x] In the "Total balance" window, only plot bars for relevant balance terms (same logic as previous comment)

**Comment by arjanverkerk** [comment]
In the code I based the logic on the "name" items of the graph series and the "label_name" items of the barchart series, which are close to what @leendertvanwolfswinkel wrote above, but not exactly the same. It may be a good check to see if the logic above translated properly to the code: https://github.com/nens/ThreeDiToolbox/blob/fa33a3d74b18ef71a9847f5423d7d5a3b68b8006/tool_water_balance/utils.py#L229
