### ISSUE TITLE
pumpstation show both discharge and discharge_pump in graph

### ISSUE THREAD

**Issue by kasperlange** [nens/threedi-results-analysis#86]
When I select discharge_pump I see what I would expect (only the values for the pumpstation). However, when I select discharge I see an apparently random discharge where I would expect to see nothing for the pumpstation (because a pumpstation should only shows discharge_pump).

Discharge_pump:
![image](https://cloud.githubusercontent.com/assets/12894576/19477771/07ee32a6-9540-11e6-9327-8a168a38e0ec.png)

Discharge van pump en culvert:
![image](https://cloud.githubusercontent.com/assets/12894576/19477783/16f12e98-9540-11e6-8da9-2933ba6d8a2c.png)

**Comment by Jonasvsl** [comment]
out of date
