### ISSUE TITLE
Results manager: If you add results too fast, things go wrong

### ISSUE THREAD

**Issue by leendertvanwolfswinkel** [nens/threedi-results-analysis#860]
I have two result sets for my Paramaribo model (both rev. 13) 

If I double click them both immediately after one another (the second before the first has loaded), the model grid gets added to the results manager twice. This causes other issues later on.

**Comment by benvanbasten-ns** [comment]
Hmm, I think the UI needs to be disabled until the grid/result is added to the model OR is invalid.
