### ISSUE TITLE
Result aggregation & Watershed tool: copy features from gridadmin.gpkg instead of generating them

### ISSUE THREAD

**Issue by leendertvanwolfswinkel** [nens/threedi-results-analysis#862]
This allows filtering on a more extensive set of properties, and makes them consistent with the computational grid layers

I propose to implement this in the 'backend' part of the code that does not rely on the pyqgis api, i.e. use `ogr` to copy the features

**Comment by leendertvanwolfswinkel** [comment]
I would expect the node outputs of 3Di Results Aggregation to have the same attributes (plus 1 or more extra) as the computational grid "Node" layer. But they still have very different attributes. E.g.:
- connection_node_id in the tool output is called "spatialite_id"
- tool output has a "node type description"

Nodes layer attributes: 

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcHFSIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--68792205a4ce6e947eb9a964ac18276546b60887/image.png)

3Di Results Aggregation node output attributes:

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcVdSIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--db18eeb10dc5a81ae9eef61e7f7783bc6dd1d0f4/image.png)

**Comment by benvanbasten-ns** [comment]
@leendertvanwolfswinkel this was an easy implementation, all attributes of the grid are now also in the tool output.. I left the original attributes in the tool output as well..

**Comment by benvanbasten-ns** [comment]
@leendertvanwolfswinkel  redundant attributes might be used in styling

**Comment by benvanbasten-ns** [comment]
@leendertvanwolfswinkel  Removed spatialite_id, node_type_description and z_coordinate from generated layers
