### ISSUE TITLE
`threedi_result_aggregation` is duplicated

### ISSUE THREAD

**Issue by leendertvanwolfswinkel** [nens/threedi-results-analysis#865]
- [ ] Merge `ThreeDiToolbox\tool_statistics\threedi_result_aggregation` and `ThreeDiToolbox\tool_watershed\result_aggregation` and processing/deps/discharge/

Important to do this before making changes/additions to this code

@leendertvanwolfswinkel  please also test proc algorithms from custom statistics

**Comment by benvanbasten-ns** [comment]
Better do this before #851
