### ISSUE TITLE
Temporal controller:  default used timestep doesn’t (always?) automatically equal the output-timestep

### ISSUE THREAD

**Issue by benvanbasten-ns** [nens/threedi-results-analysis#880]
The default used timestep doesn’t (always?) automatically equal the output-timestep. I tested it with a simulation that had an output-timestep of 300 sec, but the step-size in the panel is 297 sec.  Example data on sharepoint

**Comment by arjanverkerk** [comment]
That is on purpose. The simulation timesteps are not necessarily equidistant, and moreover it is possible to have multiple results with different timesteps controlled by one temporal controller. To be able to visualize any result timestep, the controller timestep is set to the minimum of the per-result-minimuim intervals. Downside is that there may be duplicate frames when animating. In this example the minimums are 297-ish (I think there is some rounding-to-integer of the individual timesteps going on as well):

```
$ ncdump -v time sim_135128_demo_rev10_40mm/results_3di.nc
netcdf results_3di {
dimensions: ...
variables: ...
data:

 time = 0, 300, 600, 903.724, 1200.223, 1501.755, 1800.434, 2101.526, 
    2402.306, 2703.777, 3002.819, 3302.819, 3602.819, 3902.819, 4202.819, 
    4502.819, 4802.819, 5102.819, 5402.819, 5702.819, 6002.819, 6302.819, 
    6602.819, 6902.819, 7202.819, 7502.819, 7802.819, 8102.819, 8402.818, 
    8702.818, 9002.818, 9302.818, 9602.818, 9902.818, 10202.82, 10502.82, 
    10802.82 ;
}

$ ncdump -v time sim_135224_demo_rev10_70mm/results_3di.nc
netcdf results_3di {
dimensions: ...
variables: ...
data:

 time = 0, 300, 602.4885, 900.3083, 1200.9, 1502.122, 1800.022, 2102.161, 
    2402.263, 2700.41, 3000.247, 3300.723, 3601.706, 3900.395, 4203.603, 
    4504.708, 4803.361, 5103.361, 5403.361, 5703.361, 6003.361, 6303.361, 
    6603.361, 6903.361, 7203.361, 7503.361, 7803.361, 8103.361, 8403.36, 
    8703.36, 9003.36, 9303.36, 9603.36, 9903.36, 10203.36, 10503.36, 10803.36 ;
}


```
