### ISSUE TITLE
Watershed: use markers instead of styling to denote analyzed nodes

### ISSUE THREAD

**Issue by benvanbasten-ns** [nens/threedi-results-analysis#882]
- Load data (grid and 1 result)
- Toggle eye icon of result for animation, note that computational grid layers are restyled
- Enable watershed tool and select result
- Note that  Computational Gris -> Node layer has been restyled by watershed tool
- Close watershed tool (upper-right x of panel)
- Note that computational grid styling is restored (and animation styling is not restored)

**Comment by benvanbasten-ns** [comment]
Solution is to let watershed use markers to indicate analyzed nodes. In that case there is no styling conflict

**Comment by leendertvanwolfswinkel** [comment]
@benvanbasten-ns  This is great!
