### ISSUE TITLE
3Di Toolbox Sunset version

### ISSUE THREAD

**Issue by leendertvanwolfswinkel** [nens/threedi-results-analysis#887]
To facilitate the transition from 3Di Toolbox to 3Di Result Analysis, please make a version of 3Di Toolbox with (only) the following features:
- During startup, it removes any leftover dependencies (this is existing functionality, right?).
- After installation, show an info popup dialog with the following message:  

"Thank you for installing the sunset version of 3Di Toolbox.

3Di Toolbox has been replaced by the 3Di Schematisation Editor (for viewing and editing schematisations) and 3Di Result Analysis (for analysing simulation results). Please install these two plugins through the Plugin Manager.

You may still need to load layers from the 3Di spatialite to fix errors reported by the schematisation checker. For this purpose, the 3Di Toolbox sunset version still allows you to add the spatialite layers to your project. This is a temporary situation, while the 3Di team is preparing the phasing out of the spatialite and transitioning to geopackage entirely."

- The toolbar should have two buttons: one with a  [3Di sunset logo](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcTliIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--9ec3b05cb406c7f4053594542150c98c974bb4fa/3Di%20Sunset%20logo.png) and one with the "database with a plus" image
- When the user clicks on the 3Di Sunset logo, display the info message displayed above.
- When the user clicks on the database icon, open a file dialog (filter = .sqlite). User browses to the sqlite file they want to open, layers are added to the project and styled as in the legacy 3Di Toolbox.

**Comment by benvanbasten-ns** [comment]
- [ ] Update metadata to indicate sunset?

**Comment by leendertvanwolfswinkel** [comment]
@benvanbasten-ns when switching the plugin off in the plugin manager, I get the following error:

```
Error while unloading plugin ThreeDiToolbox 

AttributeError: 'ThreeDiResultSelection' object has no attribute 'on_unload' 
Traceback (most recent call last):
  File "C:\PROGRA~1/3DIMOD~1.28/apps/qgis-ltr/./python\qgis\utils.py", line 523, in unloadPlugin
    plugins[packageName].unload()
  File "C:\Users\leendert.vanwolfswin\AppData\Roaming\3Di\QGIS3\profiles\From the developers desk/python/plugins\ThreeDiToolbox\threedi_plugin.py", line 99, in unload
    tool.on_unload()
AttributeError: 'ThreeDiResultSelection' object has no attribute 'on_unload'
```
