### ISSUE TITLE
Result manager: Add result to computational grid that is already present in tree if possible

### ISSUE THREAD

**Issue by leendertvanwolfswinkel** [nens/threedi-results-analysis#890]
Situation: I have added a computational grid for a model with slug `my_model_rev3` and added results `rain_event_8`. I now add a new result set `rain_event_10`, from a simulation with the same model `my_model_rev3`. 

What I want to happen: I want the results manager to check the grids already present in the tree to see if any grid has the slug I am looking for, and if so, add the `rain_event_10` results to that grid.

What actually happens: the result manager adds a new grid and attaches the results for `rain_event_10` to that new grid

**Comment by benvanbasten-ns** [comment]
- [x] This requires support in the ThreediResult class for h5 files at arbitrary locations
