### ISSUE TITLE
SideView polishing

### ISSUE THREAD

**Issue by leendertvanwolfswinkel** [nens/threedi-results-analysis#891]
Show/hide nodes kost veel tijd --> apart ticket: "Set visible"
Water heeft niet dezelfde kleur als het lijntje
2e / 3e / n result moet random kleurtje krijgen, niet ook blauw
Pattern (kleur & dash/dot style) kan niet aangepast worden
Verticale lijnen weergeven op de assen
Geen verticale node-lijntjes weergeven, ook niet voor Manholes
Bolletjes een andere kleur geven als ze een storage area hebben. Of vierkantje ipv bolletje?
Node bolletjes zijn te licht.
Lichtgrijs is te licht

Culvert op dezelfde manier weergeven als weir & orifice: Donkergrijs onder en boven de buis, lichtgrijs in de buis
Choose sideview trajectory > Click > Pan/Zoom > Shit, nu moet ik opnieuw beginnen
Positie wordt niet meer weergegeven op de kaart nadat je een andere map tool hebt gebruikt

Kleuren:
	Weir
		donker: #e31a1c
		licht:  #ff999b (S 40%, V 100%)
	Orifice
		donker: #33a02c
		licht: #a5e6a1
	Culvert
		donker: #656565 (100, 100, 100)
		licht: #b3b3b3 (180, 180, 180)

**Comment by benvanbasten-ns** [comment]
- [x] verticale node stippellijnen weghalen, verticale gridlijnen terug
- [x]  water colors different color scheme, solid line
- [x]  ground fill -> 200, 200, 200 (don't forget bolletjes and randjes donkerder (3x150)
- [x]  water bolletjes zelfde kleur als water (niet transparant)
- [x]  stratosfeerlijntjes ook weg
- [x]  marker (x and line) remains when selecting different maptool
- [x]  keep path when selecting different maptool, only reset when clicking reset
- [x]  autoscale ook culverts meenemen
