### ISSUE TITLE
Time series plotter: all lines have the same colour

### ISSUE THREAD

**Issue by leendertvanwolfswinkel** [nens/threedi-results-analysis#895]
Each line should have a different colour per node/flowline.

I think this broke when implementing the "batch-add items" option

https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBa2VSIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--eafc256588af599218b74dc471ad0b96f8787937/image.png

**Comment by benvanbasten-ns** [comment]
@leendertvanwolfswinkel  This might as well be desired behavior. The same flowline in each result should have the same color?

**Comment by leendertvanwolfswinkel** [comment]
@benvanbasten-ns lines in the plot should always be distinguishable from one another. In this example, that is not the case: 

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdnFmIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--4176864ece5406a1dd5f9db5ea3c40577d4a4263/image.png)

I think the problem is that the colour is determined based on the id of the node that is clicked. In this case, the clicked node for Met and Zonder have the same id. But they are different features (because from a different layer), so they should actually get different colours.
