### ISSUE TITLE
Try installing 3Di Results Analysis in profile with all other plugins (incl. 3Di Toolbox) installed

### ISSUE THREAD

**Issue by leendertvanwolfswinkel** [nens/threedi-results-analysis#899]

**Comment by leendertvanwolfswinkel** [comment]
The only (potentially confusing) issue I encountered is that after installing 3Di Results Analysis, I get the popup "CRITICAL - 3Di Models & Simulations working directory not yet set"

Perhaps instead of giving a popup for this, we can add a text to the "3Di Working Directory" tab of the "Load Simulation Results" dialog? E.g. "Please set your 3Di working directory in the 3Di Models & Simulations settings to be able to load computational grids and results from your 3Di working directory."
"

**Comment by benvanbasten-ns** [comment]
Now shown as label at bottom of dialog
