### ISSUE TITLE
Sideview for culvert: add lower, middle, upper fills like weirs

### ISSUE THREAD

**Issue by benvanbasten-ns** [nens/threedi-results-analysis#900]

**Comment by benvanbasten-ns** [comment]
![image](https://github.com/nens/ThreeDiToolbox/assets/97883955/7df4234d-5c12-4c80-a506-5afdf8c79d14)

**Comment by benvanbasten-ns** [comment]
dark grey (100)
light grey (180)

**Comment by benvanbasten-ns** [comment]
waterfill needs to be drawn over opening fill (also for weirs and orifices). Means that these structures require 3 fills instead of 2

**Comment by benvanbasten-ns** [comment]
@leendertvanwolfswinkel  testing this issue also requires testing weirs and orifices (as the waterfill is now drawn on top of opening fill)

**Comment by leendertvanwolfswinkel** [comment]
@benvanbasten-ns It all looks really great. 

One thing that has also accidentally changed is that the water fill is now also drawn *over*  the soil (the part between the top of the pipe and the surface/exchange level). Only the water level line should remain visible, to indicate that it is a pressure line, not actual water volume.

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbi9BIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--94d223b10906ea49105f3d0cb897611de0e5faaa/image.png)

**Comment by benvanbasten-ns** [comment]
@leendertvanwolfswinkel fixed
