### ISSUE TITLE
Time series plotter: weird plots when simulations have different output time steps

### ISSUE THREAD

**Issue by leendertvanwolfswinkel** [nens/threedi-results-analysis#901]
I have two simulations with different output time steps (60 vs. 300 s). 

When I plot them together, one of them ( I think the 60 s one) shows as a 'blocky' line.

**Met** : 300 s
**Zonder**: 60 s

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcStkIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--824cfd4ccf170676443a5c3b77002eed6dee6332/image.png)

**Comment by benvanbasten-ns** [comment]
Also blocked when only one is selected:

![image](https://github.com/nens/ThreeDiToolbox/assets/97883955/91ae57db-cc91-4558-9242-fd1a89159229)

**Comment by benvanbasten-ns** [comment]
We writing the data to file, plotting in Excel also yields block data

![image](https://github.com/nens/ThreeDiToolbox/assets/97883955/b191c240-9b59-4dde-9bef-6ad56fb438dd)

**Comment by benvanbasten-ns** [comment]
inspection in file itself also shows staircasing

[2:53 PM] Daan 

>>> f["Mesh2D_s1"][:, 86823]
array([-9.9990000e+03,  8.6571198e+00,  8.6571198e+00,  8.6571198e+00,
        8.6571198e+00,  8.6571198e+00,  8.6600113e+00,  8.6603975e+00,
        8.6608982e+00,  8.6609316e+00,  8.6609335e+00,  8.6629715e+00,
        8.6629725e+00,  8.6629725e+00,  8.6629725e+00,  8.6629725e+00,
        8.6642513e+00,  8.6642523e+00,  8.6642523e+00,  8.6642523e+00,
        8.6642523e+00,  8.6652327e+00,  8.6652336e+00,  8.6652336e+00,
        8.6652336e+00,  8.6652336e+00,  8.6667423e+00,  8.6667414e+00,
        8.6667423e+00,  8.6667423e+00,  8.6667423e+00,  8.6679277e+00,
        8.6679277e+00,  8.6679277e+00,  8.6679277e+00,  8.6679277e+00,
        8.6690426e+00,  8.6690416e+00,  8.6690416e+00,  8.6690416e+00,
        8.6690416e+00,  8.6690416e+00,  8.6690416e+00,  8.6690416e+00,
        8.6690416e+00,  8.6690416e+00,  8.6667423e+00,  8.6667423e+00,
        8.6667423e+00,  8.6667423e+00,  8.6667423e+00,  8.6642523e+00,
        8.6642523e+00,  8.6642523e+00,  8.6642523e+00,  8.6642523e+00,
        8.6609812e+00,  8.6609344e+00,  8.6609335e+00,  8.6609335e+00,
        8.6609335e+00,  8.6583023e+00,  8.6575289e+00,  8.6573286e+00,
        8.6572533e+00,  8.6571875e+00,  8.6571245e+00,  8.6570654e+00,
        8.6570120e+00,  8.6569614e+00,  8.6569176e+00,  8.6568775e+00,
        8.6568375e+00,  8.6568031e+00,  8.6567707e+00,  8.6567411e+00,
        8.6567135e+00,  8.6566896e+00,  8.6566658e+00,  8.6566448e+00,
        8.6566257e+00,  8.6566076e+00,  8.6565914e+00,  8.6565752e+00,
        8.6565619e+00,  8.6565495e+00,  8.6565371e+00,  8.6565266e+00,
        8.6565161e+00,  8.6565065e+00,  8.6564980e+00,  8.6564903e+00,
        8.6564827e+00,  8.6564760e+00,  8.6564703e+00,  8.6564646e+00,
        8.6564598e+00,  8.6564550e+00,  8.6564503e+00,  8.6564465e+00,
        8.6564426e+00,  8.6564388e+00,  8.6564360e+00,  8.6564331e+00,
        8.6564302e+00,  8.6564283e+00,  8.6564255e+00,  8.6564236e+00,
        8.6564217e+00,  8.6564198e+00,  8.6564188e+00,  8.6564169e+00,
        8.6564159e+00,  8.6564140e+00,  8.6564131e+00,  8.6564121e+00,
        8.6564112e+00,  8.6564102e+00,  8.6564093e+00,  8.6564083e+00,
        8.6564083e+00,  8.6564074e+00,  8.6564064e+00,  8.6564064e+00,
        8.6564054e+00,  8.6564054e+00,  8.6564045e+00,  8.6564045e+00,
        8.6564035e+00,  8.6564035e+00,  8.6564035e+00,  8.6564026e+00,
        8.6564026e+00,  8.6564026e+00,  8.6564026e+00,  8.6564016e+00,
        8.6564016e+00,  8.6564016e+00,  8.6564016e+00,  8.6564016e+00,
        8.6564016e+00,  8.6564007e+00,  8.6564007e+00,  8.6564007e+00,
        8.6564007e+00,  8.6564007e+00,  8.6564007e+00,  8.6564007e+00,
        8.6564007e+00,  8.6564007e+00,  8.6564007e+00,  8.6564007e+00,
        8.6564007e+00,  8.6564007e+00,  8.6564007e+00, -9.9990000e+03,
       -9.9990000e+03, -9.9990000e+03, -9.9990000e+03, -9.9990000e+03,
       -9.9990000e+03, -9.9990000e+03, -9.9990000e+03, -9.9990000e+03,
       -9.9990000e+03, -9.9990000e+03, -9.9990000e+03, -9.9990000e+03,
       -9.9990000e+03, -9.9990000e+03, -9.9990000e+03, -9.9990000e+03,
       -9.9990000e+03, -9.9990000e+03, -9.9990000e+03, -9.9990000e+03,
       -9.9990000e+03, -9.9990000e+03, -9.9990000e+03, -9.9990000e+03,
       -9.9990000e+03], dtype=float32)
