### ISSUE TITLE
Include computational grid name in result selector comboboxes

### ISSUE THREAD

**Issue by leendertvanwolfswinkel** [nens/threedi-results-analysis#902]
In the water balance tool and the result aggregation tool, the result selector comboboxes shows only the name of the result (i.e. "bui08"). Please also include the name of the grid (i.e. "Met maatregelen | bui08").

**Comment by benvanbasten-ns** [comment]
- [ ] water balance
- [x] watershed
- [x] statistics

**Comment by benvanbasten-ns** [comment]
@arjanverkerk I changed this in statistics and watershed tool. Could you change this for the tabs of the waterbalance tool? I'm afraid to break something

@arjanverkerk fixed this tool as well
