### ISSUE TITLE
Rewrite `threedigrid_to_ogr` so that it copies all features from the gridadmin.gpkg

### ISSUE THREAD

**Issue by leendertvanwolfswinkel** [nens/threedi-results-analysis#914]
Currently, `threedi_results_aggregation.utils.threedi_result_aggregation.threedi_ogr.threedigrid_to_ogr()` get a `threedigrid` object, like `Nodes`, `Cells`, or `Lines`, and converts it to a `ogr.Layer`, using a specific logic with regard to which fields to include, how to name them, etc.

This was made before the "export to geopackage" functionality was added to threedigrid. This does almost exactly the same, but with a slightly different logic wrt which fields to include, how to name them, etc. 

Furthermore, the moment a user runs the Result aggregation tool, this export to geopackage has already been done, all the features we need already exist, so it makes little sense to create them again from the gridadmin source data. 

Important extra benefit for the user is that it allows filtering on a more extensive set of attributes.

I propose to implement this in the 'backend' part of the code that does not rely on the pyqgis api, i.e. use ogr to copy the features.

PS. This was actually what I wanted in #862. I hope this ticket explains it better.

**Comment by leendertvanwolfswinkel** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Modeller-Interface-61e574104cc38a001fb287de/issues/nens/ThreeDiToolbox/914?planning-poker) with Zenhub @arjanverkerk @benvanbasten-ns

**Comment by hoanphungt** [comment]
@benvanbasten-ns could you help me to explain what needs to be done in the threedigrid_to_ogr() function to achieve what Leendert wants here? I don't quite understand the requirement, especially how it is related to the GeopackageExporter from threedigrid.

**Comment by hoanphungt** [comment]
@leendertvanwolfswinkel this is ready to be reviewed and tested again
