### ISSUE TITLE
[Bug]: ImportErrors at version 2.5.5. using MI 2.28.11 

### ISSUE THREAD

**Issue by d2hydro** [nens/threedi-results-analysis#919]
### Contact Details

daniel@d2hydro.nl

### Complexity

easy

### Priority

low prio

### What happened?

I installed MI 2.28.11 on windows, after installation passed 3DiToolbox-plugin it kept re-installing threedigrid and scipy. Reinstalling Scipy fails as it is locked causing numerous exceptions

### How to Reproduce?

1. download MI 2.28.11 at: https://docs.3di.live/f_3di_instruments_and_downloads.html
2. install it on your windows-machine, both software and profile (make sure you don't have an existing profile)
3. wait till plugin is installed and reboot
4. restart and see threedigrid gets reinstalled
5. open python-console, deactivate, reactivate 3diplugin will provide the log attached:
[log-file.txt](https://github.com/nens/ThreeDiToolbox/files/12726836/log-file.txt)

### What did you expect and what was the actual result?

A smooth installation on Windows, where all dependent modules can be found after installation and reboot

### Add screenshots, video's etc

[log-file.txt](https://github.com/nens/ThreeDiToolbox/files/12726836/log-file.txt)

### Relevant log output

```shell
[log-file.txt](https://github.com/nens/ThreeDiToolbox/files/12726836/log-file.txt)
```

### Additional info

Anything else you would like to share?

**Comment by leendertvanwolfswinkel** [comment]
servicedesk issue
