### ISSUE TITLE
Time series plotter: support for structure_control_actions.nc

### ISSUE THREAD

**Issue by leendertvanwolfswinkel** [nens/threedi-results-analysis#925]
Since recently, the calccore logs structure control actions to a file called `structure_control_actions_3di.nc`. This file is already available for download via the files download API endpoint.
 
- [x] Let the Timeseries plotter check if there is a `structure_control_actions_3di.nc`
- [ ] Add the *action* time series to the combox, as "{structure type} ID {source_table_id / content_pk} | {action_type}", e.g.
        - 'Weir ID 23 | Crest level'
	- 'Weir ID 28 | Crest level'
	- 'Pump ID 54 | Capacity'
- [x] Plot a time series of the action value, based on a `threedigrid` query on the `structure_control_actions_3di.nc`, grouped by line_id and action_type

**Comment by benvanbasten-ns** [comment]
@leendertvanwolfswinkel please test

**Comment by leendertvanwolfswinkel** [comment]
The variable is now e.g. "set_crest_level". Can you show this as "Crest level" instead? So remove `set_`, remove all underscores, and use sentence case?

**Comment by benvanbasten-ns** [comment]
@leendertvanwolfswinkel added, please retest

**Comment by leendertvanwolfswinkel** [comment]
I have more feedback... clear case of voortschrijdend inzicht, sorry about that. 

I am using this test data:
https://nelenschuurmans-my.sharepoint.com/:u:/g/personal/leendert_vanwolfswinkel_nelen-schuurmans_nl/EbY4vbM4DIxCqAgAN3UBgr0BfeN-yTLI4jX_QbrmFBkVug?e=HjGVr9

I am looking at the crest level graph for flowline with ID 58778

It looks like this:
<img width="946" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeVFFQ0E9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--19559b3033b6539c8e5e988293f213b579c226b4/image.png" alt="image.png" />



And a close-up of the lowering limb:
<img width="944" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeUlFQ0E9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--6797bad663df595eda5344304f148a3a5caeec0b/image.png" alt="image.png" />

There are two issues with this graph:
- [ ] The graph suggests that the crest level goes back to its original value at the end of the simulation, but this is not the case
- [ ] The graph suggests that the changes in crest level are gradual, but this is also not the case. There should be sharp jumps/falls without interpolation each time a structure control action is fired.

**Comment by benvanbasten-ns** [comment]
@leendertvanwolfswinkel can you provide the test data?

**Comment by leendertvanwolfswinkel** [comment]
Added the link to my comment...

**Comment by benvanbasten-ns** [comment]
Tricky, this control action has a final last action at 172802.83 seconds (the very end of the simulation)

![image](https://github.com/user-attachments/assets/497bbf47-33f1-4435-b4cd-1ef29ea41397)

**Comment by leendertvanwolfswinkel** [comment]
Ok well if it is just the data than the graph is correct I suppose. If you can make the graph so that there is no interpolation, this won't be a problem anymore

**Comment by benvanbasten-ns** [comment]
@leendertvanwolfswinkel  please retest

**Comment by leendertvanwolfswinkel** [comment]
Love it. Please merge
