### ISSUE TITLE
Processing Algorithm "Extract structure control actions"

### ISSUE THREAD

**Issue by leendertvanwolfswinkel** [nens/threedi-results-analysis#926]
Since recently, the calccore logs structure control actions to a file called `structure_control_actions_3di.nc`. This file is already available for download via the files download API endpoint.

- [ ] Create a Processing Algorithm "Extract structure control actions", that generates a CSV from the structure_control_actions file (thin wrapper around the `threedigrid` functionality.

**Comment by benvanbasten-ns** [comment]
@leendertvanwolfswinkel please test

**Comment by leendertvanwolfswinkel** [comment]
If I try to save the CSV to a temporary location, I get

```Algorithm 'Convert structure control actions' starting…
Input parameters:
{ 'GRIDADMIN_INPUT' : 'C:\\Users\\leendert.vanwolfswin\\Documents\\3Di\\bwn_purmer_1d2d_ggg\\revision 1\\results\\Purmer T1000 piek met 1D initieel water gelabeld (223090)\\gridadmin.h5', 'OUTPUT_FILENAME' : 'TEMPORARY_OUTPUT', 'SCA_INPUT' : 'C:\\Users\\leendert.vanwolfswin\\Documents\\3Di\\bwn_purmer_1d2d_ggg\\revision 1\\results\\Purmer T1000 piek met 1D initieel water gelabeld (223090)\\structure_control_actions_3di.nc' }

Execution completed in 0.08 seconds
Results:
{'error': "[Errno 13] Permission denied: 'TEMPORARY_OUTPUT'", 'result': False}

Loading resulting layers
Algorithm 'Convert structure control actions' finished
```

Perhaps borrow some code from the Check Schematisation processing algorithm?

**Comment by leendertvanwolfswinkel** [comment]
Please also add the result to the QGIS project. Again: Perhaps borrow some code from the Check Schematisation processing algorithm

**Comment by benvanbasten-ns** [comment]
@leendertvanwolfswinkel added feedback on branch. please retest

**Comment by leendertvanwolfswinkel** [comment]
Good stuff! Please merge
