### ISSUE TITLE
Result aggregation: Water on street duration uses user-defined drain level instead of actual 1D2D exchange level

### ISSUE THREAD

**Issue by leendertvanwolfswinkel** [nens/threedi-results-analysis#935]
The algorithm currently calculates the time that the water level exceeds the `drain_level` of the node. This value is the drain level that the user defines in the schematisation (`v2_manhole.drain_level`).

However, often the drain level is set below the lowest pixel in the 2D cell the manhole is in; so effectively, the "street level" is the lowest exchange level (`dpumax`) of all 1D2D connections between the manhole and the 2D cell. Using the user-defined `drain_level` often overestimates the Water on street duration.

I think we should fix this in the following way:
- [x] Give two options in the GUI for threshold: 'Drain level', and 'Exchange level'. 'Drain level' uses the existing implementation, i.e. use the user-defined `drain_level` property of the node. 'Exchange level' uses the lowest `dpumax` of all 1D2D flowlines.
- [ ] The threshold option 'Exchange level' should be disabled in the GUI if the grid meta property `has_2d == False`
- [x] If the threshold is 'Exchange level', calculate for each manhole (node) the lowest `dpumax` of all 1D2D flowlines connected to it and use this as threshold value. For nodes that have 0 1D2D flowlines connected to them, use (pseudo) infinity as threshold.
- [x] Change the name of the existing preset to "Water on street duration (0D1D)", which uses threshold "Drain level"
- [x] Add a new preset "Water on street duration (1D2D)", which uses threshold "Exchange level"

**Comment by arjanverkerk** [comment]
We discussed to do no disabling of the exchange_level threshold or the 1D2D preset based on the selected result. The aggregation will work for results for models without 2D, but there will be no water on the street at all.

**Comment by leendertvanwolfswinkel** [comment]
@arjanverkerk  When I use the exchange level threshold, I get a python error for the (1D2D) Schiphol model: 

```
An error has occurred while executing Python code: 

ValueError: operands could not be broadcast together with shapes (120,15726) (1,33) 
Traceback (most recent call last):
  File "C:\Users\leendert.vanwolfswin\AppData\Roaming\3Di\QGIS3\profiles\From the developers desk/python/plugins\threedi_results_analysis\tool_statistics\statistics.py", line 161, in finished
    raise self.exception
  File "C:\Users\leendert.vanwolfswin\AppData\Roaming\3Di\QGIS3\profiles\From the developers desk/python/plugins\threedi_results_analysis\tool_statistics\statistics.py", line 105, in run
    self.ogr_ds, self.mem_rasts = aggregate_threedi_results(
  File "C:\Users\leendert.vanwolfswin\AppData\Roaming\3Di\QGIS3\profiles\From the developers desk/python/plugins\threedi_results_analysis\utils\threedi_result_aggregation\base.py", line 1148, in aggregate_threedi_results
    node_results[new_column_name] = agg_func(
  File "C:\Users\leendert.vanwolfswin\AppData\Roaming\3Di\QGIS3\profiles\From the developers desk/python/plugins\threedi_results_analysis\utils\threedi_result_aggregation\base.py", line 351, in time_aggregate
    result = aggregate_prepared_timeseries(
  File "C:\Users\leendert.vanwolfswin\AppData\Roaming\3Di\QGIS3\profiles\From the developers desk/python/plugins\threedi_results_analysis\utils\threedi_result_aggregation\base.py", line 308, in aggregate_prepared_timeseries
    is_over_threshold = np.greater(timeseries, threshold)
ValueError: operands could not be broadcast together with shapes (120,15726) (1,33) 


Python version: 3.9.5 (tags/v3.9.5:0a7dcbd, May  3 2021, 17:27:52) [MSC v.1928 64 bit (AMD64)] 
QGIS version: 3.28.5-Firenze Firenze, 50adba36f2 

Python Path:
C:\Users\leendert.vanwolfswin\AppData\Roaming\3Di\QGIS3\profiles\From the developers desk\python\plugins\threedi_results_analysis\deps
C:\Users\leendert.vanwolfswin\AppData\Roaming\3Di\QGIS3\profiles\From the developers desk/python/plugins\threedi_beta_processing
C:/PROGRA~1/3DIMOD~1.28/apps/qgis-ltr/./python
C:\Users\leendert.vanwolfswin\AppData\Roaming\3Di\QGIS3\profiles\From the developers desk/python
C:\Users\leendert.vanwolfswin\AppData\Roaming\3Di\QGIS3\profiles\From the developers desk/python/plugins
C:/PROGRA~1/3DIMOD~1.28/apps/qgis-ltr/./python/plugins
C:\PROGRA~1\3DIMOD~1.28\apps\grass\grass82\etc\python
C:\PROGRA~1\3DIMOD~1.28\bin
C:\PROGRA~1\3DIMOD~1.28\bin\python39.zip
C:\PROGRA~1\3DIMOD~1.28\apps\Python39\DLLs
C:\PROGRA~1\3DIMOD~1.28\apps\Python39\lib
C:\Users\leendert.vanwolfswin\AppData\Roaming\Python\Python39\site-packages
C:\PROGRA~1\3DIMOD~1.28\apps\Python39
C:\PROGRA~1\3DIMOD~1.28\apps\Python39\lib\site-packages
C:\PROGRA~1\3DIMOD~1.28\apps\Python39\lib\site-packages\win32
C:\PROGRA~1\3DIMOD~1.28\apps\Python39\lib\site-packages\win32\lib
C:\PROGRA~1\3DIMOD~1.28\apps\Python39\lib\site-packages\Pythonwin
C:\Users\leendert.vanwolfswin\AppData\Roaming\3Di\QGIS3\profiles\From the developers desk/python
.
```

**Comment by leendertvanwolfswinkel** [comment]
Other thoughts:
- We need to include the threshold name in the column name (i.e. `time_above_threshold_drain_level` instead of `time_above_threshold`)
- The preset description needs to be more elaborate

**Comment by arjanverkerk** [comment]
I don't get the error when I just select the result and then the 1d2d preset, however I get something similar to your error _when I deselect `Only manhole nodes`._ Can you give a more precise description of your steps in the stats dialog to arrive at the error? And maybe a proposal for the preset description.

edit: Added the cursive part (_when I deselect `Only manhole nodes`._)

**Comment by arjanverkerk** [comment]
The issue was caused by a threshold array being stored on the aggregation instance while the aggregation instances are not reinitialized when switching results. Solved by not storing the threshold at all.

I changed the column names by appending the threshold source, in the same manner as was done for the other thresholding aggregations.

What should the preset descriptions be?
