### ISSUE TITLE
Processing algorithms "Computational grid from ...": show warnings when using processing algorithm

### ISSUE THREAD

**Issue by leendertvanwolfswinkel** [nens/threedi-results-analysis#944]
There are two processing algorithms that use `threedi_gridbuilder`"
- ~~"Computational grid from gridadmin.h5 file"~~
- "Computational grid from schematisation"

`threedigrid_builder` logs warnings (and perhaps also info messages?). Please pass this logging to the processing algorithm so that they are shown to the user in the Processing Algorithm user feedback window.

**Comment by benvanbasten-ns** [comment]
"Computational grid from gridadmin.h5 file" does not use threedigrid_builder, but threedigrid
