### ISSUE TITLE
Results manager: pump (linestring) with one feature does not contain any features when added via Results manager

### ISSUE THREAD

**Issue by leendertvanwolfswinkel** [nens/threedi-results-analysis#947]
We have this gridadmin
[OUTPUT.zip](https://github.com/nens/ThreeDiToolbox/files/13214080/OUTPUT.zip)
 file that contains one pump (with end node). The gridadmin.gpkg also contains this feature. If you add the layer `pump_linestring` to QGIS with native QGIS tooling, you see the layer in your project with the one feature it contains.

However, if you add the same gridadmin via the Results Manager, the layer has no features.

**Comment by benvanbasten-ns** [comment]
display_name is too long: 

`Could not store attribute "display_name": String of length 36 exceeds maximum field length (32)`

**Comment by benvanbasten-ns** [comment]
![image](https://github.com/nens/ThreeDiToolbox/assets/97883955/59b566b9-5594-462d-b307-5cd2b5acf63c)

**Comment by benvanbasten-ns** [comment]
![image](https://github.com/nens/ThreeDiToolbox/assets/97883955/a628b7c3-be1c-4151-a5e7-d97c07755ea7)

**Comment by benvanbasten-ns** [comment]
So, the pump layer in the gpkg contains a value for display_name that is 36 characters, whereas the max string length is 32. Therefore the feature can not be added to the memory layer

**Comment by leendertvanwolfswinkel** [comment]
A fix is made in threedigrid: https://app.zenhub.com/workspaces/team-3di-5ef60eff1973dd0024268b90/issues/gh/nens/threedigrid/202, this needs to be released and the threedigrid version of 3Di Results Analysis needs to be bumped

**Comment by leendertvanwolfswinkel** [comment]
@benvanbasten-ns fix is available in `threedigrid 2.2.0`. Can you bump this requirement in 3Di Results Analysis and release a new version of the plugin?
