### ISSUE TITLE
Processing algorithm to create spatio-temporal forcings NetCDF from list of rasters

### ISSUE THREAD

**Issue by leendertvanwolfswinkel** [nens/threedi-results-analysis#957]
**Name**
Spatio-temporal NetCDF from rasters

**Inputs**
Rasters (list)
Start datetime
Time interval [s]

**Outputs**
Output NetCDF file

**Algorithm**
See the Jupyter Notebook that @PySjon will attach to this ticket

**Comment by PySjon** [comment]
[raster2netcdf_rain2023 (1).zip](https://github.com/nens/ThreeDiToolbox/files/13295603/raster2netcdf_rain2023.1.zip)

**Comment by leendertvanwolfswinkel** [comment]
Other example: 
[genNetCDF.zip](https://github.com/nens/ThreeDiToolbox/files/14493324/genNetCDF.zip)

**Comment by leendertvanwolfswinkel** [comment]
Duplicate #1029
