### ISSUE TITLE
Water balance tool: switching tabs resets the water balance terms checkboxes

### ISSUE THREAD

**Issue by leendertvanwolfswinkel** [nens/threedi-results-analysis#967]

**Comment by hoanphungt** [comment]
@leendertvanwolfswinkel which tab do you switch?

![image](https://github.com/nens/ThreeDiToolbox/assets/43402556/2d5b603f-7bf7-47b1-8b4d-7130a503dbd6)

**Comment by leendertvanwolfswinkel** [comment]
When you load > 1 simulation results, the water balance tool has a tab for each result


Met vriendelijke groet / Kind regards,


Leendert van Wolfswinkel

Product Owner 3Di Water Management<https://3diwatermanagement.com/>

Nelen & Schuurmans


Werkdagen: ma di wo do | Working Days: Mon Tue Wed Thu


+31 (0)30 233 0200   <tel:+31+(0)30+233+0200> |  +31 (0)6 <tel:+31+(0)6+----+----> 31 000 353
www.nelen-schuurmans.nl
Zakkendragershof 34-44, 3511AE, Utrecht
[Logo N&S]
[twitter]<https://twitter.com/nelenschuurmans>          [linkedin] <https://www.linkedin.com/company/245070/>

________________________________
