### ISSUE TITLE
Vector data importer: Import Pipes

### ISSUE THREAD

**Issue by leendertvanwolfswinkel** [nens/threedi-results-analysis#976]
Very similar to the import functionalities for Culverts, Weirs and Orifices.

Details for the layer Pipe have been added to this spreadsheet: https://nelenschuurmans-my.sharepoint.com/:x:/g/personal/leendert_vanwolfswinkel_nelen-schuurmans_nl/ETjOz94ZsbJOsKk18jfZZNMBWUkhxw3oVDim7wc9MlDydw?e=CndJSn

**Note**
Pipes can have only two vertices. Imported geometry should be a straight line from start vertex to end vertex, ignoring all in-between vertices in the input data.

- [ ] Processing algorithm "Import Manholes"
- [ ] GUI for "Import Manholes"

**Comment by leendertvanwolfswinkel** [comment]
@ldebek nice work! Some feedback:
- Pipes can have only two vertices. Imported geometry should be a straight line from start vertex to end vertex, ignoring all in-between vertices in the input data.
- In the GUI, Pipes have attributes "Pipe quality", "Profile number", and "Original length". These are old, deprecated fields that should not be shown here. You can delete those attributes entirely from the layer if necessary. They should've been removed from the spatialite a long time ago already, not sure why we didn't do that yet

**Comment by ldebek** [comment]
@leendertvanwolfswinkel Changes applied.

**Comment by leendertvanwolfswinkel** [comment]
@ldebek please merge :)
