### ISSUE TITLE
Visualize substance concentrations on map

### ISSUE THREAD

**Issue by leendertvanwolfswinkel** [nens/threedi-results-analysis#978]

**Comment by leendertvanwolfswinkel** [comment]
@hoanphungt, it works well, but one small issue (same as before in the time series plotter):

<img width="610" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOGx5QlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--5a9f18e392fd4b57d326da1d88ecdff30ff6870c/image.png" alt="image.png" />

**Comment by hoanphungt** [comment]
@leendertvanwolfswinkel  The fix for the timeseries plotter should also fix it in the layer menu but it wasn't merged yet at that time. It should be fixed now as I just merged refactor back to this branch.
