### ISSUE TITLE
RFC results on the map view functionality

### ISSUE THREAD

**Issue by bastiaan-roos** [nens/threedi-results-analysis#98]
In the current version, there is a experimental version which shows results on the map. This RFC shows what is required to finalize this function

*User functionality*

Flow for the user:
1. User switch on the map animation functionality
2. Through a popup the user selects: parameter + function for nodes and for links
3. on closing the popup, the result layers are showed (in the 'tool' folder of the model legend map. There are 2 time indicators, one for nodes and one for links (in case an aggregation is selected and so the time steps)
4. when moving one of the time sliders, the other one is also moving to the nearest available time-step
5. There is a button setting the scalling features (rescale now based on ..., auto-rescale, select min and max). In this popup also a color ramp can be selected.

functions are:
- current value 
- relative to initial value
- water depth (water level minus bottom level)
- absolute value
- relative to previous time step

*Todos:*
[] popup for selection of parameter and function
[] function support for layer visualization
[] initialization of layers in correct legend folder
[] Time identification for nodes and links, linked to time slider
[] popup for legend scalling functions
[] legend scalling functions

**Comment by Jonasvsl** [comment]
out of date
