### ISSUE TITLE
Water depth/level processing algorithm - remove popups

### ISSUE THREAD

**Issue by leendertvanwolfswinkel** [nens/threedi-results-analysis#981]
- If you edit the input for "Results 3Di file" by typing in the widget, you get two popup messages for each letter you type. Please remove this.

**Comment by hoanphungt** [comment]
@leendertvanwolfswinkel How do I edit the input for "Results 3Di file" and where is it located in the application?

**Comment by leendertvanwolfswinkel** [comment]
Processing > Toolbox > 3Di > Post-process results > Water depth/level rasters

For navigating the code for this feature, please consult with Ben


Met vriendelijke groet / Kind regards,


Leendert van Wolfswinkel

Product Owner 3Di Water Management<https://3diwatermanagement.com/>

Nelen & Schuurmans


Werkdagen: ma di wo do | Working Days: Mon Tue Wed Thu


+31 (0)30 233 0200   <tel:+31+(0)30+233+0200> |  +31 (0)6 <tel:+31+(0)6+----+----> 31 000 353
www.nelen-schuurmans.nl
Zakkendragershof 34-44, 3511AE, Utrecht
[Logo N&S]
[twitter]<https://twitter.com/nelenschuurmans>          [linkedin] <https://www.linkedin.com/company/245070/>

________________________________
